# encoding=utf-8

txt = '''Gustav Adolf Harnisch ist am 11.12.1906 in Schönborn im Kreis Luckau im heutigen Brandenburg geboren. Wie viele der hier Begrabenen, stammt Gustav Harnisch also nicht aus dem Rheinland, sondern kommt von weither. Harnisch war von Beruf Bergmann und Landwirt, der für die Eigenversorgung ca. 30 Morgen Land zuzüglich Vieh bewirtschaftete. Mit seiner ersten Frau Elsbeth Frieda Meta, geb. Schippan, hatte er die Söhne Karl Heinz und Günter Gustav sowie die Tochter Giesela Ingeburg.
 Die Kriegszeit traf Harnisch schwer. Im Juni 1940 kam es zu seiner ersten Einberufung zur 1. Kompanie des Infanterie-Regiments 663. Er war vom 07.08.1940 bis zum 03.02.1941 im Einsatz in der 5. Kompanie des Landesschützen-Bataillons 224. Im selben Jahr starb seine Frau Meta nach schwerer Erkrankung, wodurch die Vormundschaft des jüngeren, nicht einmal einjährigen Sohnes Günter auf eigenen Wunsch an die Familie seiner Schwester Emma und Reinhold Bachert übertragen wurde. Im Februar 1941 erfolgte dann Harnischs vorzeitige Entlassung aus dem Wehrdienst aus privaten Gründen. Offensichtlich setzten Harnisch der Tod der Ehefrau, die offenen Sorgerechtsfragen der Kinder oder der 1941 verstorbene Vater schwer zu.
Als Harnisch wieder in Brandenburg zuhause war, zog er gemeinsam mit seiner Nachbarin Elsbeth Altmann seine Kinder Heinz und Ingeburg groß. Die Beziehung zwischen Harnisch und Elsbeth entwickelte sich von einer Zweckgemeinschaft hin zu einer Ehe. Der Ehemann Elsbeths war bereits zuvor im Krieg gefallen. Die beiden heirateten am 12.06.1943. Die neue Ehefrau brachte einen älteren Sohn mit in die Ehe. Der zweite Sohn Günter verblieb auf Wunsch seines Vaters weiterhin in der Familie seiner Schwester und wurde bis zu seinem 16. Lebensjahr in deren Haus in Schönborn großgezogen.
Am 08.09.1944 erfolgte Harnischs zweite Einberufung nach Thorn zur 6. Kompanie des Grenadier-Regiments 696, das sich ab dem 20.11.1944 im Kampfeinsatz im Jülicher Brückenkopf im Verband der 340. Volksgrenadier-Division befand. Sogenannte Volksgrenadier-Divisionen wurden seit dem 20. Juli 1944 von der deutschen Wehrmacht zum Ausgleich der schweren Verluste im Zuge der Invasion in die Normandie gegründet und bestanden zum größten Teil aus Soldaten mit geringerer Ausbildung, was zu schweren Verlusten führte.  Der Jülicher Brückenkopf, eine Festungsanlage aus napoleonischer Zeit, war Ende 1944 bis Anfang 1945 der Schauplatz erbitterter Kämpfe zwischen deutschen und amerikanischen Verbänden. Harnisch kämpfte am Südteil des Brückenkopfes von Bourheim bis Kirchberg.
Am 23.11.1944 zogen sich die deutschen Sicherungen zurück, um sich für eine Gegenoffensive bereit zu machen. Harnischs Einheit ist dabei durch den amerikanischen Angriff in Bourheim zerstört worden. Harnisch selbst ist tags darauf als vermisst gemeldet worden.  Am 25.11.1944 wurde er dann durch Granatensplitter schwerverwundet geborgen und ins Kriegslazarett Knechtsteden abtransportiert, wo er am 26.11.1944 um 3:00 Uhr an den Folgen seiner schweren Verletzung verstarb. Seine Beisetzung fand im November 1944 auf dem Friedhof des Klosters Knechtsteden statt.  Heinz Harnisch, der Sohn Gustav Harnischs, besuchte das Grab seines Vaters zur Eröffnung der Kriegsgräberstätte am 27.10.1957.
 Seine letzte überlieferte Feldpost schrieb Harnisch an seine Nichte „Trautchen“ am 30.10.1944, also gut drei Wochen vor seinem Tod. In voller Erwartung an das Kriegsende schreibt er: „Wie Du schreibst willst Du mit dem Heiraten noch warten bis ich zu Hause bin, [das] [f]reu[t] mich aber. Denn wir wollen doch das Tanzbein tüchtig schwingen bei Deiner Hochzeit. […] [W]ir sollten erst zum 20. Oktober hier wegkommen, nun hat es sich aber noch verschoben, wann es nun wird[,] wissen wir auch nicht […]. Wann nun der Krieg zu Ende sein wird[,] ist noch nicht raus, ich denke aber es wird nun bald enden […].“ Seinen „Goldsohn Günter“, den Trautchen von ihm grüßen soll, konnte Gustav Harnisch nicht mehr wiedersehen.
'''

x = txt.replace("  ", " ")

x = x.replace("\n ", "\n")

print(x) 