# encoding=utf-8

txt = '''1898, also kurz nach der Übernahme des Klosters durch den Spiritaner-Orden, wurde der Klosterhof erbaut. Dieses Projekt leitete Bruder Aristobul. Damals sind die Förderer und Mitglieder des „Vereins für das Missionshaus Knechtsteden“ regelmäßig gekommen, um den Fortschritt des Wiederaufbaus Knechtstedens unter der Leitung des Baumeisters und Bruders Ansberi zu begutachten, den sie finanzierten. Weil jene Förderer gern Zeit dort vorbrachten, wo sie den Wiederaufbau unterstützten, und sich nach Feierabend gesellig austauschten, schien ein Gasthaus notwendig, wo auch die Vereinssitzungen stattfinden konnten. Die Knechtstedener Spiritaner wollten sich für die großzügige Unterstützung der Vereinsmitglieder erkenntlich zeigen und begannen deshalb den Bau eines Restaurants mit Herberge. Auch diente der Klosterhof als Unterkunft für die Verwandten der Patres und Brüder, insbesondere die weiblichen, die ihre Familienmitglieder nur einmal im Jahr in Knechtsteden besuchen durften. Übernachtungen und Besuche innerhalb des Klosters waren dabei untersagt, weshalb der Klosterhof als Gasthaus nötig war.
Weil Bruder Ansbert bereits aufgrund der anderen Restaurationen in Knechtsteden viel zu tun hatte, fragten die Spiritaner Bruder Aristobul Lülsdorf, der als Maurer gelernt hatte. Dieser stammte zwar aus Köln Langel, war aber in den Orden in Frankreich eingetreten und wirkte zu dieser Zeit in Paris und Portugal. Diese Rekrutierung aus dem Ausland war nicht unüblich, denn die Ordensleitung in Paris entsandte in der Anfangszeit Knechtstedens einige Brüder, um den Wiederaufbau zu unterstützen. Als der Bruder dann aus Portugal nach Knechtsteden gekommen war, konnte mit dem Bau begonnen werden. Geplant wurde der Klosterhof von dem Architekten Bruder Raffael. Dass der Bruder Aristobul Lülsdorf in Paris gelebt hat, wird durch den französischen Baustil deutlich, den man auch heute noch am Klosterhof bewundern kann.
1976 wurde die Gaststätte renoviert, da sich das Kloster an überregionaler Beliebtheit erfreute. Der Klosterhof dient bis heute als Herberge und beliebter Gasthof. Hier kehrten und kehren Touristen, Pilgernde, aber auch Patres und Schülerinnen und Schüler des Norbert-Gymnasiums gerne ein. Wir können Ihnen den Besuch des Klosterhofs nur wärmstens ans Herz legen. Treten Sie ein und bestellen Sie doch schon einmal, bevor wir uns verabschieden. Allen Bierliebhabern können wir das Knechtstedener Kellerbier empfehlen. Über den untenstehenden Button gelangen Sie zur Getränke- und Speisekarte, die auch Saisonales bietet. Kehren Sie aber zum Abschluss unbedingt zurück zur Klosterführer-App, sowie Sie bestellt haben!
'''

x = txt.replace("  ", " ")

x = x.replace("\n ", "\n")

print(x) 