name: klosterguide
description: Klosterguider for Knechtsteden

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/app2.png"
# flutter pub run flutter_launcher_icons:main für neues icon
flutter_native_splash:
  color: "FFFFFF"
  image: assets/icons/app.png
  android_disable_fullscreen: true
#flutter pub run flutter_native_splash:create Für neues SplashDing
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

# To see which dependencies have newer versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations: #language libary/String system
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_map: ^0.14.0
  latlong: ^0.6.1
  video_player: ^2.2.7
  flutter_map_location_marker: ^1.0.0
  geolocator_web: ^2.0.6
  flutter_launcher_icons: ^0.9.2
  flutter_native_splash: ^1.3.1
  flutter_swiper: ^1.1.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

# The following section is specific to Flutter.
flutter:
  generate: true # Strings

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/guideicons/
    - assets/home/
    - assets/guidevideos/
    - assets/strings/en.json #String system
    - assets/strings/de.json
    - assets/map/14/8498/
    - assets/map/14/8499/

    - assets/map/15/16997/
    - assets/map/15/16998/
    - assets/map/15/16999/
    
    - assets/map/16/33995/
    - assets/map/16/33996/
    - assets/map/16/33997/
    - assets/map/16/33998/

    - assets/map/17/67990/
    - assets/map/17/67991/
    - assets/map/17/67992/
    - assets/map/17/67993/
    - assets/map/17/67994/
    - assets/map/17/67995/
    - assets/map/17/67996/
    - assets/map/17/67997/

    - assets/map/18/135980/
    - assets/map/18/135981/
    - assets/map/18/135982/
    - assets/map/18/135983/
    - assets/map/18/135984/
    - assets/map/18/135985/
    - assets/map/18/135986/
    - assets/map/18/135987/
    - assets/map/18/135988/
    - assets/map/18/135989/
    - assets/map/18/135990/
    - assets/map/18/135991/
    - assets/map/18/135992/

  #   - images/a_dot_ham.jpeg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
