class StationInfo {
  final int position;
  final double xcoord;
  final double ycoord;
  final String name;
  final String iconImage;
  final String fulltext;
  final String video;
  final int next;

  final String zusatzvideo;
  final String zusatztext;
  final String mapvideo;

  StationInfo(
    this.position, {
    this.xcoord = 0,
    this.ycoord = 0,
    this.name = "",
    this.iconImage = "",
    this.fulltext = "",
    this.video = "",
    this.next = 0,
    this.zusatzvideo = "",
    this.zusatztext = "",
    this.mapvideo = "",
  });
}

List<StationInfo> stationen = [
  StationInfo(1,
      xcoord: 51.076410,
      ycoord: 6.754703,
      name: 'Torhaus',
      iconImage: 'assets/guideicons/torhaus.jpg',
      fulltext:
          '''Welch ein Anblick sich dem Besucher Knechtstedens bei seiner Ankunft offenbart! Das imposante Portal begrüßt ihn und weist ihm den Weg zum Gotteshaus, das schon aus der Ferne sichtbar ist und sich ihm in seiner vollen Pracht präsentiert. Dabei besuchten Pilgernde Knechtsteden bereits weit vor Errichtung dieses Torbogens, wie Sie ihn hier sehen.
Einer alten Legende nach soll ein unbekannter Knecht aus dem nahegelegenen Dieplinghoven, dem heutigen Delhoven, noch vor der Klostergründung im Wald ein aus Holz geschnitztes Muttergottesbild gefunden und mit nach Hause genommen haben. Am folgenden Tag stand das Bild jedoch wieder an derselben Stelle im Wald. Als ihm dies noch einmal geschah und das Bild auch ein drittes Mal verschwand, soll er am Fundort zu Ehren der Mutter Gottes eine Kapelle errichtet haben. Deshalb soll der Ort „Knechtstein“, heute „Knechtsteden“, genannt worden sein. Diese Geschichte bleibt allerdings nur eine Legende, denn Historiker leiten die Herkunft des Namens „Knechtsteden“ von dem Wort „Knightstadium“ oder „Ritterknechtstätte“ ab. Das Abbild der Muttergottes wurde außerdem nie gefunden. So oder so blickt Knechtsteden auf eine sehr lange Wallfahrtsgeschichte zurück. Der Ort gilt zwar nicht als der größte Marienwallfahrtsort des Rheinlandes, zählt aber wohl zu den ältesten. Pilgernde kamen seit jeher vor allem aus Köln, aber auch aus dem Jülicher Land, aus Neuss und Düsseldorf und sogar vom fernen Niederrhein.
Nun aber zum Torbogen: Das vor Ihnen befindliche zweistöckige barocke Torhaus ersetzte 1723 den ehemaligen romanischen Torbogen am Eingang des Klosterbezirks und wurde unter Abt Arnold Brewer (1703-1728), dessen Wappen am Portal eingearbeitet ist, als Teil der 
Umbauten im frühen 18. Jahrhundert errichtet. In Folge dieser Umbauten wurden die meisten Gebäude barockisiert, so auch das Torhaus.
Verziert ist der Torbogen mit drei Statuen, zwei an den Seiten und eine oben. Die obere zeigt die Gottesmutter Maria mit dem Jesuskind auf dem Arm. Sie grüßt die Pilgernden bei Ankunft in die ihr gewidmete Wallfahrtsstätte.
Die zwei Figuren an den Seiten stehen in gewisser Weise für zwei Epochen Knechtstedens. Links ist der Heilige Norbert dargestellt. Norbert von Xanten lebte von 1080 bis 1134 und ist der Ordensgründer der Prämonstratenser, die sich 1130 in Knechtsteden niederließen und 1138 mit dem Bau der Basilika begannen. Der Heilige Norbert, über den Sie gleich gern mehr in der App hören und lesen können, steht also für die Gründung des Klosters und seines Ordens. Vor Ihnen hält er in seiner linken Hand die Monstranz mit gewandelter Hostie. Seinerzeit galt der Heilige Norbert als deklarierter Gegner Tanchelms, der von der Kirche als Häretiker und Ketzer verurteilt wurde, weil er die wirkliche Gegenwart Jesu Christi in der gewandelten Hostie leugnete. So ist das Attribut Norberts als ein Symbol für sein Vertrauen auf die Heilige Kommunion zu verstehen.
Rechts zu sehen ist Franz Maria Paul Libermann, einer der beiden Gründer der Missionsgesellschaft vom Heiligen Geist und vom Unbefleckten Herzen Mariens, kurz und umgangssprachlich: des Spiritaner-Ordens. Das ausgehende 18. und das 19. Jahrhundert brachten Knechtsteden schwere Zeiten. Mit der Übernahme der Klosteranlage durch die Spiritaner 1895 beherbergte Knechtsteden endlich wieder Ordensmänner, nachdem die Französische Revolution und napoleonische Säkularisation der ehemaligen Abtei der Prämonstratenser 1802 den 
Garaus gemacht hatten. Mit der rechten Figur des Torbogens besinnen sich die Knechtstedener also auf den zweiten Orden, der in Knechtsteden ansässig wurde. Abgebildet ist Libermann mit einem Kreuz in seiner Hand. Dies ist ein Verweis auf seine besondere Spiritualität und die Kongregation, die er gegründet hat. Zur Erklärung: Eine Kongregation ist eine religiöse Vereinigung, die sich im Unterschied zu den älteren Ordensgemeinschaften, die hauptsächlich auf das innerklösterliche Leben ausgerichtet waren, vor allem Aufgaben außerhalb des Klosters widmet. Libermann verschrieb sich dabei der Missionierung in Afrika, auf die das Kreuz in seiner Hand hindeuten soll.
An den nächsten Stationen erfahren Sie über die beiden Epochen und Ordensgemeinschaften Knechtstedens mehr. Beginnen Sie hierfür die Navigation zur nächsten Station.''',
      video: "assets/guidevideos/Kapitel_1.mp4",
      mapvideo: "assets/navvideos/Nav_1.mp4",
      next: 1),
  StationInfo(2,
      name: 'Norbertpark',
      xcoord: 51.076585,
      ycoord: 6.753799,
      iconImage: 'assets/guideicons/norbertpark.png',
      fulltext:
          '''Wenden Sie Ihren Blick zunächst dem Norbertpark zu. Wurde die große weitläufige Grünfläche früher landwirtschaftlich genutzt, hat der Norbertpark heutzutage eine andere Funktion. Nicht selten findet gerade an warmen Sommertagen Unterricht des in Sichtweite befindlichen Norbert-Gymnasiums, zu dem wir später noch kommen, im Freien statt. Auch Veranstaltungen an der frischen Luft, etwa Gottesdienste oder zuletzt die Vergabe der Zeugnisse an die Abiturienten, erfreuen sich im Norbertpark besonderer Beliebtheit. Der Norbertpark fungiert als ein Ort, der zusammenführt. Seine Anziehungskraft bezieht er nicht zuletzt aufgrund des wunderschönen Ausblicks, den die Basilika offeriert.
Bitte wenden Sie sich nun der Klosterbasilika zu und lassen Sie die Hecken hinter sich, sodass Sie einen freien Blick auf das Gotteshaus werfen können. Sie sehen das Monument einer bewegten Zeit des 12. Jahrhunderts. Die Klostergründung in Knechtsteden von 1130 geht nämlich zurück auf die Schenkung des ererbten Fronhofs des Domdekans zu Köln, Hugos von Sponheim, an die Prämonstratenser. Dieser wurde zu seiner Schenkung durch den Kölner Erzbischof Friedrich I. angeregt.
Der Prämonstratenser-Orden ist nach einem Bekehrungserlebnis vom Heiligen Norbert von Xanten, einem Spross aus adeliger Familie, 1121 im namensgebenden Prémontré in Nordfrankreich gegründet worden und aus seiner Reformbewegung heraus entstanden, die sich dem Ideal des gemeinsamen Lebens im Stile der Urkirche verpflichtete. Jene Reform lehnte die Häufung an Besitz, Machtmissbrauch und sündhaftes, weltliches Verhalten in der Kirche zugunsten einer klösterlichen Gemeinschaft des Gebets ab. Wenn Sie nach Abschluss dieses Abschnitts auf Ihrem Gerät herunterscrollen, haben Sie die Möglichkeit, mehr über das aufregende Leben des Heiligen Norbert und seine bewegte Zeit zu erfahren. Sie können die aktuelle Wiedergabe aber auch pausieren und bereits jetzt den Heiligen Norbert kennenlernen.
Dass dem Kölner Erzbischof eine Klostergründung in Knechtsteden attraktiv erschien, ist vor dem Hintergrund der Organisation des Ordens zu erklären: Für das klösterliche Leben galt die Augustinusregel. Die Prämonstratenser verschrieben sich jedoch nicht nur dem kontemplativen monastischen Leben im Kloster, sondern übernahmen auch außerklösterliche Funktionen. Als „halbe Mönche und halbe Pastöre“ ermöglichten sie besonders in abgelegenen Gegenden die Seelsorge, für die sich adelige Priester kaum interessierten.       
Nach der Schenkung des Fronhofs Knechtsteden durch Hugo von Sponheim an die Prämonstratenser wurde 1134 zunächst eine Magdalenenkapelle errichtet, die nicht mehr erhalten geblieben ist. Auch genauere Hintergründe der Errichtung bleiben unklar. Sicher ist, dass 
die Mönche die Gründungskapelle erbauen ließen, da sie Gottesdienste zelebrieren wollten. Offensichtlich war die Kapelle nach wenigen Jahren zu klein für den aufstrebenden Orden geworden. Bereits 1138 begannen die Prämonstratenser dann mit dem Bau der Klosterkirche, die bis in die Gegenwart ein Wahrzeichen der Region darstellt. Übrigens: Den Grundstein für den Bau legte eine Frau namens Udalinde. Sie war vermutlich die Schwester oder Mutter des Schatzmeisters Christian an St. Andreas in Köln, mit dessen Mitteln der Bau der Basilika begonnen wurde. Jener trat unter dem ersten Knechtstedener Propst, dem seligen Heribert, in den Orden der Prämonstratenser ein und gab nach dem Vorbild seines Herkunfts-Stifts der Basilika ihren Patron Andreas. Der Sarkophag, den Sie, Ihren Blick leicht nach links auf den Boden wendend, erblicken, war womöglich der letzte Ruheort Udalindes. Sicher kann das Grab ihr zwar nicht zugeordnet werden, die Grabplatte aus Sandstein stammt jedoch erwiesenermaßen aus der Stauferzeit und stimmt somit mit der Lebens- und Todeszeit Udalindes überein.
Das Äußere der Basilika ist durch die drei Türme und das grauweiße Steinbild charakterisiert, die das Gebäude deutlich vom umliegenden Wald abheben und es so zu einem Wahrzeichen der Region machen. Die Klosterkirche ist 60 Meter lang und 19 Meter breit. Das Querschiff misst eine Länge von 26 Metern. Der Vierungsturm, unter dem sich das Langhaus und das Querschiff kreuzen, hat eine Höhe von 35 Metern. Gebaut wurde die Basilika aus Eifeler Sand- und Tuffstein. Einige Ecken sind hingegen aus dem stabileren Trachyt vom Drachenfels bei Bonn gefertigt worden. Diese und weitere bauliche Verschiedenheiten sind vor dem Hintergrund der unterschiedlichen Bauphasen zu erklären.
Die Basilika Knechtsteden ist ein kunsthistorisch überaus besonderes Gotteshaus. Dies wird nicht zuletzt durch die Verschmelzung der rheinisch-traditionellen Romanik sowie der durch die Prämonstratenser aus Nordfrankreich importierten Gotik verstärkt. Die Klosterkirche beurkundet so den Einfluss rheinischer und nordfranzösischer Kultur in ihrer Region. Am deutlichsten erkennbar scheint die Vereinigung der beiden architektonischen Epochen bereits von Ihrer Perspektive aus. Sind der Vierungsturm und die gesamte Drei-Türme-Anlage das Werk rheinischer Romanik, verweisen die Fenster des Ostchors eindeutig auf die Gotik. Jene auffällige architektonische Unterschiedlichkeit ist vor dem Hintergrund einer Erneuerung im 15. Jahrhundert, nach erheblichen Schäden durch Plünderungen während der Neusser Fehde 1474, einer kriegerischen Auseinandersetzung zwischen dem Erzbischof Ruprecht von Köln und den Landständen des Erzstifts, zu erklären. Doch auch der ursprüngliche Bau in seiner vorliegenden Form verweist auf jene Vereinigung von Romanik 
und Gotik. War die rheinische Romanik eher bestrebt, dem Beispiel profaner Repräsentativbauten nach großflächig in die Breite, in die Horizontalität zu bauen, möchte die Gotik den Blick zu Gott in die Höhe, in die Vertikalität lenken. Die Außenwände des Ostbaus sind gegliedert und mit Ornamenten versehen, wie sie in Nordfrankreich seinerzeit üblich gewesen sind. Das Langhaus und die Turmanlagen hingegen sind in niederrheinischen Bauformen gestaltet. Baulich besonders interessant sind die beiden Seitentürme: Die unteren beiden Geschosse sind französisch geprägt, die oberen niederrheinisch. Der Hang zur nordfranzösischen Vertikalität wird dabei durch den helleren Trachytstein betont, der das Bauwerk höher wirken lässt. Die Waagerechte betont hingegen der Tuffstein aus der Südeifel. Bauhistoriker erkennen in diesem französischen Einfluss erste gotische Elemente rheinischer Baukunst und zählen die Basilika Knechtsteden deshalb zu den bedeutendsten Bauwerken des 12. Jahrhunderts.
Gehen Sie nun links entlang der Basilika am Sarkophag vorbei Richtung Durchlass in der Mauer. Bevor Sie die Mauer durchlaufen, an der die 14 Stationen des Kreuzweges in Form gusseiserner Reliefs angebracht sind, blicken Sie rechts am Fuß der Basilika hinunter. 
Dort ist bewusst als letzte, erweiterte 15. Station des Kreuzweges an der Ostseite der Basilika ebenfalls eine alte Grabplatte drapiert, um an die Auferstehung nach dem Tod zu erinnern. Wem jenes Sarkophagfragment jedoch gehört, ist ungewiss. Durchqueren Sie nun die Mauer hin zur Südseite der Klosterkirche mit Blick auf das dreischiffige Langhaus. Achten Sie je nach Körpergröße auf Ihren Kopf, Personen über 1,85m stoßen sich hier gelegentlich.
Vor Ihnen befindet sich das südliche Nebenschiff mit dem Hauptportal. Jenes Portal ist nachträglich eingefügt worden, da der ursprüngliche Osteingang nach Anbau des Querschiffes nicht mehr zu nutzen gewesen ist. Schauen Sie genau hin: Das Hauptportal ist verziert mit viermal abgetreppten Gewänden. Die Basaltsäulen setzen sich in den Bögen als Rundstäbe fort. Den innersten Portalbogen ziert ein schöner Akanthusblattfries, der in der Ornamentik für Leben und Unsterblichkeit steht. Betrachten Sie nun die Wand des vor Ihnen befindlichen südlichen Nebenschiffes. Sie zeigt eindeutig Bogenspuren eines früher verbauten Kreuzganges, der nach den verschiedenen Formen dieser Bögen mehrmalige Umbauten erfahren haben muss. Vermutlich war das Kloster Knechtsteden ursprünglich als Doppelkloster mit männlichen und weiblichen Ordensleuten geplant, auf die die Umbauten zurückgehen könnten. Genauere Quellen dazu sind jedoch nicht überliefert.
Wenden Sie Ihren Blick nach rechts. In der Nische zum östlichen Querschiff ist ein Relief eingelassen. Es zeigt die Heilige Magdalena zu Füßen Jesu Christi in dem Moment, als sie ihn als Auferstandenen erkennt. Das Relief verweist auf die ehemalige Gründungskapelle, die 1134 errichtet worden war und aufgrund ihres schlechten Zustandes Mitte des 18. Jahrhunderts, genauer 1731, abgerissen wurde. Das Relief erinnert daher an die ersten Anfänge klösterlichen Lebens in Knechtsteden.''',
      video: "assets/guidevideos/Kapitel_2.mp4",
      zusatztext:
          '''Norbert von Xanten ist geboren in eine bewegte Zeit des Machtkampfes zwischen Papst und Kaiser.  Der Investiturstreit prägte die jungen Jahre des Heiligen Norbert, der 1080 vermutlich in Gennep, in den heutigen Niederlanden, geboren wurde – vermutlich, da nicht sicher überliefert ist, ob Norbert bereits zur Welt gekommen war, als sein Vater, Graf Heribert von Gennep, Burgvogt von Xanten wurde. Die Familie wechselte also den Wohnsitz von Gennep nach Xanten. Seine ersten von adeligem Stand privilegierten Lebensjahre verbrachte Norbert in Xanten.
 Sein Vater erwirkte für Norbert, Stiftsherr am Viktorstift in Xanten zu werden. Es handelte sich sozusagen um ein perfektes Absprungbrett, um eine kirchliche Karriere einzuschlagen. Aufgrund seines kirchlichen Rangs verbrachte Norbert unter anderem viel Zeit an den Höfen des Erzbischofs von Köln sowie des deutschen Königs Heinrich V. und kam in den Genuss des höfischen Lebens.  Norbert begleitete um das Jahr 1110 den König nach Italien, der in Rom vom Papst zum deutschen Kaiser gekrönt werden wollte.
Aufgrund der damaligen Spannungen zwischen weltlicher und geistlicher Gewalt weigerte sich der Papst, den Salier Heinrich V., Sohn Kaiser Heinrichs IV., zum Kaiser zu krönen. Heinrich nahm den Papst Paschalis II. gefangen und verlangte neben seiner Kaiserwürde das Recht der Investitur, also das Recht, Bischöfe zu ernennen und abzusetzen. Norbert von Xanten muss diese Vorgänge sehr intensiv erlebt und abgelehnt haben. 
Heinrich V. warb um Norbert und bot ihm sogar ein Bischofsamt an, das Norbert, vermutlich von den Vorgängen in Rom abgeschreckt, aber ablehnte. Wann Norbert einen inneren Wandel vollzog oder gar eine transzendentale Erfahrung machte, ist unklar.  Die Legende besagt, dass er im Jahre 1115 auf dem Ausritt nach Vreden in ein Unwetter geriet. Vor ihm soll ein Blitz eingeschlagen sein, sodass Norbert samt Pferd zu Boden stürzte und, dem Tode knapp entkommen, sein Leben hinterfragte. Für ihn stand fest: Es brauchte Erneuerung in ihm und in der Kirche. Um Vorbilder zu finden, ging er auf Wanderschaft. Auf seinen Wanderungen beherbergten ihn verschiedene Klöster. Norbert lernte die Klosterregeln, die Gemeinschaft und nicht zuletzt das asketische Leben kennen. Er ließ sich zum Diakon und daraufhin zum Priester weihen.
Zurück in Xanten, versuchte er die dortigen Stiftsherren zu St. Viktor von einem Lebenswandel im Sinne des Urchristentums zu überzeugen, den er in der Kirche anstrebte. Seine modische Seidenkleidung legte Norbert ab, verschenkte seinen Besitz und beschaffte sich eine raue Kutte, um mit gutem Beispiel voranzugehen. Norbert erntete dennoch lediglich Spott.
 Unverrichteter Dinge verließ Norbert sodann Xanten wieder und erkannte, dass Reform und Wandel nicht mit Weltfremdheit und Rückzug zu erreichen sind, sondern geistlichen Handelns bedürfen. Norbert von Xanten wurde Wanderprediger. 1118 begab er sich in seine niederländische Heimat und predigte auf Wanderschaft bis nach Belgien.
Norbert zeichnete sich als Prediger aus. Er begeisterte. Er ermunterte zu Demut und Bescheidenheit und prangerte Streit, Missgunst sowie Geiz und Habgier an. Dabei kam auch Kritik gegen Kirche und Fürsten nicht zu kurz. Jene Kirche hörte selbstredend nicht gern von einem Kritik übenden Wanderprediger, sodass Norbert in das Visier geriet und 1118 angeklagt wurde.  Auf der Synode, die über Norberts Schicksal verhandeln sollte, rechtfertigte er sich erfolgreich und erlangte sogar im Nachgang die Predigtvollmacht des Papstes in Nordfrankreich.
So versuchte die Kirche, Norbert und seine unangenehme Beliebtheit in der einfachen Bevölkerung für sich zu nutzen.  Man ließ ihn gewähren und erlaubte ihm 1120 die Gründung eines eigenen Klosters im Tal von Prémontré bei Laon in Frankreich. Der Prämonstratenserorden, dessen Namensherkunft unschwer erkennbar vom Namen des Gründungsortes rührt, wurde gegründet. Dabei hat auch der Name des Gründungsortes mit Norbert zu tun: Schließlich soll er eine Vorsehung oder einen göttlichen Hinweis, im weitesten Sinne aus dem lateinischen locus praemonstratus übersetzt, gehabt haben, an jenem Ort sein Kloster zu gründen. Das weiße Bußgewand aus ungebleichter Schafswolle wurde zur Ordenskleidung. In erstaunlicher Schnelle verbreitete sich der Orden der Prämonstratenser und gewann Begeisterte für sich – ob Mann, ob Frau. Klöster wurden schnell auch in Belgien, Frankreich und Deutschland gegründet.  Das erste deutschsprachige Kloster der Prämonstratenser wurde 1122 in Cappenberg bei Dortmund errichtet. Der Graf von Cappenberg hatte nach einer persönlichen Begegnung mit Norbert von Xanten zuvor seinen gesamten Besitz übergeben und sich dem Orden angeschlossen. Ende des 12. Jahrhunderts zählten die sogenannten „Weißen Mönche“ 500 Niederlassungen.
 1126 begab sich Norbert nach Rom, um die offizielle Anerkennung seines Ordens zu erwirken. Die Verbindung asketischer Zurückgezogenheit mit der praktischen Seelsorge beeindruckte Papst Honorius II.. Die Ordensregel, die auf der Augustinusregel fußt, wurde vom Papst bestätigt. Auf seiner Rückreise wurde Norbert sogar in Würzburg festgehalten, um zu bleiben – Norbert war ein Superstar. Im Sommer berief der Reichstag ihn schließlich zum Bischof von Magdeburg. Norbert wurde gedrängt, die Wahl anzunehmen. Er gab nach, seine Anhänger blieben enttäuscht zurück und fühlten sich im Stich gelassen. 
 Mit der Annahme der Verantwortung wollte Norbert seinen Einfluss zur Reform nutzen. Barfuß und im Büßerhemd ritt er in die Stadt Magdeburg ein. Laut Legende soll ihm zunächst sogar der Einlass in den Bischofspalast verweigert worden sein. Das Volk jubelte ihm zu. Die Reformen, die Norbert aber anstrebte, waren gerade für die alten kirchlichen Eliten des Bistums Magdeburg unangenehm. Der neue Bischof kontrollierte Rechnungen und beendete Geldverschwendungen. Ein missglückter Mordanschlag ist auf ihn verübt worden.
Während seines Pontifikats nahm sich Norbert von Xanten unterschiedlicher Aufgaben an. Er trieb die Missionierung der Slawen im Osten voran, als Erzkanzler begleitete er 1132 sogar König Lothar nach Italien auf dessen Romzug. 1134 kehrte er, vermutlich an Malaria erkrankt, zurück und verstarb am 6. Juni. 1582 sprach ihn Gregor XIII. heilig. 
Der Heilige Norbert von Xanten war Zeuge einer bewegten Zeit. So wie auch sein Zeitgenosse, Bernhard von Clairvaux, Gründer des Reformordens der Zisterzienser. Beide Ordensgemeinschaften – Prämonstratenser und Zisterzienser – fanden von Frankreich aus eine erstaunlich schnelle Verbreitung. Ohne den Lebenswandel Norberts, seinen Entschluss zur inneren und äußeren Reform, aber auch ohne sein Verantwortungsbewusstsein, doch das Bistum Magdeburg zu übernehmen, wäre dies wohl nicht möglich gewesen.
''',
      zusatzvideo: "assets/guidevideos/Zusatz_Norbert.mp4",
      mapvideo: "assets/navvideos/Nav_2.mp4",
      next: 2),
  StationInfo(3,
      xcoord: 51.07669594480124,
      ycoord: 6.752454033913944,
      name: 'Basilika',
      iconImage: 'assets/guideicons/basilika.png',
      fulltext:
          '''Sie haben die Kirche nun von ihrer Westseite betreten. Halten Sie sich gleich beim Eintritt links, sodass Sie an der Westapsis stehend Halt machen. Lassen Sie das Innere der Klosterbasilika gern eine Weile auf sich wirken, bevor Sie sich dem großen Wandgemälde 
an der Westapsis widmen.
Welch ein imposantes Fresko die Westapsis doch schmückt! Bei dem Kunstwerk handelt es sich um eines der ältesten Fresken des Rheinlandes. Da es vermutlich kurz nach Errichtung des Langhauses im Jahr 1160 angefertigt wurde, ist es sogar das älteste des Niederrheins sowie das größte zwischen Rhein und Maas. Es ist kaum zu glauben, mit welchem Glücksfall sein Erhalt verbunden ist. Schließlich hat es gerade, weil es als unschön betrachtet wurde, überlebt. Im 17. Jahrhundert, als es dem Kloster in seiner Blütezeit finanziell gut ging, wurde Knechtsteden weitgehend barockisiert. Die romanische Kunst und das sehr auffällige Fresko wurden als nicht zeitgemäß betrachtet. In der Folge übertünchte man das Fresko mit einer weißen Kalkschicht. Als die Basilika 1869 einem Brand zum Opfer fiel, blieb das Fresko aufgrund jener schützenden Kalkschicht erstaunlich gut erhalten. In der Folge des Wiederaufbaus und der Erneuerungen von 1882 trat das Fresko unter der abplatzenden Kalkschicht wieder zutage – eine Sensation.
Durch das Fresko wird die alte Bedeutung der Apsis als Bogen und Tor zum Himmel sichtbar, denn es zeigt den Heiland mit dem Buch des Lebens in seiner Linken vor dem gestirnten Himmel. Mit seiner Rechten segnet er. Das Buch des Lebens ist in der christlich-jüdischen Tradition eine Art des göttlichen Verzeichnisses aller ihm gefälligen Menschen. Christus ist von der sogenannten Mandorla umgeben, einer leuchtenden Aura. Er sitzt auf dem Sphärenbogen, seine Füße ruhen auf dem Bogen des Erdkreises. Die Mandorla umgeben und tragen die vier Wesen der Geheimen Offenbarung Johannes‘. Sie sind Symbole der vier Evangelisten: Der Mensch bzw. Engel oben links steht für Matthäus, der Adler rechts für Johannes. Der geflügelte Löwe unten links verkörpert Markus, während Lukas durch den Stier symbolisiert wird. Die Spruchbänder, die die vier Wesen halten, zeigen die ersten Worte der jeweiligen Evangelien. Links und rechts umschließen die Szenerie Petrus und Paulus. Inschriften bezeichnen Petrus als „princeps apostolorum“, den Ersten der Apostel, Paulus als „doctor gentium“, den Lehrer der Völker. Unter dem Ornamentband, das die raum- wie zeitlose, jenseitige Seinsebene von dem Diesseits trennt, sind die übrigen Apostel abgebildet. Mit dem Buch der Frohbotschaft in der Hand werden alle Apostel durch Christus entsandt, um das Evangelium zu verkünden. Das phantasievolle, ordnende Ornamentband zeigt außerdem ein Schriftband: „Majestas atque figura Christi signatur per quem mundus reparatur.“ Zu Deutsch: Größe und Gestalt Christi werden bezeichnet, durch ihn wird die Welt erneuert.
Der Künstler dieses Werks scheint weit herumgekommen zu sein, denn für das Rheinland im 12. Jahrhundert ist die Darstellung der Apostel unüblich, gar innovativ. Sie stehen nicht jeder für sich getrennt, sondern bilden eine Einheit. Sie befinden sich im Gespräch oder legen ihre Hand auf die Schulter des Nebenmannes. Nicht nur die Körperhaltung verbindet die Apostel, auch die übereinander gemalten Füße verweisen auf die Einheit der Jünger Jesu.
Womöglich ist es Ihnen aufgefallen: Eine Figur ist ausgelassen worden. Zu Füßen Christi liegt ein betender, weißgewandeter Mönch. Bei diesem handelt es sich um den Stifter des zweiten Bauabschnitts, Albert von Aachen. Bislang ist vom Baustifter Christian und seiner Frau Udalinde die Rede gewesen. Christian prägte den ersten Bauabschnitt der Basilika. Er ließ zeit seines Lebens den Ostchor, den Altarraum und das Querhaus samt Gewölben und Dächern errichten. Nachdem er allerdings 1151 verstorben war, waren die Arbeiten nicht fertiggestellt. Albertus Aquensis, Albert von Aachen, „vollendete die von Christian begonnene Kirche, zog beide Seiten hoch, errichtete drei Türme mit Giebeln und Dächern, ließ Glocken gießen und tat alles zur prächtigen Ausstattung des Baus.“ So heißt es in den historischen Quellen. Albert war zu jener Zeit von 1152 bis 1155 Domdechant in Köln, von 1155 bis 1158 außerdem Propst des Münsters in Aachen. Er entstammt dem Geschlecht der Sponheimer und tritt so in die familiäre Tradition der Stiftung. Zweifellos machte sich Albert verdient. 1155 erwirkte er mithilfe der guten Beziehungen zum Kölner Erzbischof die volle Anerkennung der Besitztümer und den kaiserlichen Schutz bei Kaiser Friedrich I. Barbarossa. Es folgt sogleich die Anerkennung des Papstes. Albert von Aachen erwies sich als bedeutsame Figur in der Blütezeit Knechtstedens bis in das 13. Jahrhundert hinein. Obwohl er 1164 verstorben war, wirkten seine Verdienste nach. Nicht zuletzt wird Knechtsteden spätestens 1185 durch den Generalabt in Prémontré zur Abtei erhoben und gelangt so zu einer finanziellen und rechtlichen Unabhängigkeit von seinem nordfranzösischen Mutterkloster. Die schillernde Figur Alberts von Aachen ließ sich daher wohlverdient in diesem Apsisgemälde als Stifter zu Diensten Christi abbilden. Seine letzte Ruhestätte, die Sie gleich bestaunen können, wurde 1962 hinter dem Hauptaltar im Zuge von Fußbodenarbeiten wiederentdeckt.
Übrigens: Der Taufstein, der vor Ihnen steht, ist in etwa so alt wie die Kirche selbst. Er stammt aus dem 12. Jahrhundert. So können die Taufrechte der Kirche ebenfalls in das 12. Jahrhundert datiert werden. Geschmückt ist der aus Basalt geschlagene Taufstein mit doppeltem Zinnenfries. Sein Sockel hingegen entstand deutlich später.
Widmen wir uns den weiteren Schätzen der Knechtstedener Basilika. Wenden Sie sich hierfür Richtung Altar von der Westapsis ab und richten Sie den Blick nach oben. Sicher ist Ihnen bereits aufgefallen, dass die Decke in vier quadratische Joche unterteilt ist. Jene Räume des Langhauses sind mit Rundwülsten auf Gurtbögen, die optisch an den Pfeilern bis zur Erde verlängert sind, markant voneinander getrennt. Dem Besucher scheint es fast so, als schreite er von Raum zu Raum. Die vier Joche sind überwölbt mit Kreuzgratgewölben. In den Räumen im Ostteil sind hingegen französische Bauideen zum Tragen gekommen. Sie sind mit Kuppeln überwölbt. Im gesamten niederrheinischen Raum gibt es kein Bauwerk aus dieser Zeit mit so vollendeten und zahlreichen Kuppeln. Nicht zuletzt deswegen ließen sich Baumeister im gesamten Rheinland von der Knechtstedener Basilika und ihren Kuppeln bei folgenden Kirchenbauten inspirieren.
Auch der Wechsel von Pfeilern und Säulen lädt den Besucher dazu ein, das Langhaus andachtsvoll zu durchschreiten. Dieser für das Rheinland typische Stützenwechsel wurde in Knechtsteden mit besonderer Kunst versehen. Um den vor Ihnen liegenden Stifts-Chor im Osten vom Pfarr-Chor im Westen hinter Ihnen abzuheben, verändern sich die Säulen in ihrer Form vom quadratischen Grundriss hin zu den Dreibündelsäulen, die einen Eingang zum Stifts-Chor markieren sollen. In seiner Art ist der Knechtstedener Stützenwechsel also ein einmaliger, schöpferisch gelungener Versuch, dem westlichen und östlichen Mittelschiff-Joch einen eigenen Charakter zu geben.
Der Besucher der Knechtstedener Basilika erfreut sich feierlicher Ruhe und schlichter Erhabenheit, die der Raum ausstrahlt. Dies wird auch an dem sparsamen Schmuck liegen, den die Kirche, von dem Westapsis-Fresko abgesehen, bietet. Treten Sie gern einige Schritte Richtung Altarraum vor, bis Sie zur Höhe des Hauptportals gelangen. Wenden Sie sich noch einmal genauer den Säulen zu. Der Schmuck der Basilika beschränkt sich nämlich auf die vielfältigen und stilbildenden Kapitelle und Basen der Pfeiler und Säulen. Die gesamte zeitgenössische Schöpferkraft niederrheinischer Steinmetze manifestiert sich in ihnen. Die Kapitelle weisen eine Würfelform auf. Blätter und Ranken wurden üblicherweise als Schmuck in jene Würfel hineingemeißelt – nicht so in Knechtsteden: Es scheint so, als wären die Ornamente auf den Würfel gelegt, ja, nahezu plastisch hinzugegeben worden. Dies ist ein Nachweis besonders hoher Steinmetzkunst, die mit Sicherheit unterstützt worden ist durch französische und südländische Steinmetze. So wird die Verschmelzung französischer und niederrheinischer Romanik, die bereits von außen sichtbar wird, auch im Inneren deutlich.
Gehen Sie ein paar Schritte weiter bis zur letzten Säule vor dem Ostteil. An der rechten Säule thront das Gnadenbild. Die schmerzhafte Mutter Gottes hält ihren toten Sohn Jesus Christus in ihren Händen. Dass Knechtsteden einer der ältesten Marienwallfahrtsorte 
ist, ist bereits einleitend erwähnt worden. Dieses Bild ist eine aus Lindenholz geschnitzte Pietà aus dem 14. Jahrhundert. Der Leib Jesu scheint auffallend klein, sein Gesicht ausdrucksstark und gezeichnet. Maria schaut mit ihrem breiten, bäuerlichen Gesicht über ihren toten Sohn hinweg. Die Gesichtszüge sind zwar geprägt von Schmerz und Leid, doch sprechen sie auch von Ahnung von Erlösung. Der Kaisermantel, den Maria trägt, passt nicht zu ihrem wenig höfischen Gesicht. Diese Darstellung ist jedoch üblich bei den Prämonstratensern. Sie verbindet die herrschaftliche Erhabenheit der Gottesmutter mit der Einfachheit, die Pilgernden das Gefühl einer Identifikation gegeben haben muss.
Bis heute zieht das einen Meter große Bild Pilgernde an. Es überlebte alles Unglück, das Knechtsteden in den Jahrhunderten nach seiner Entstehung heimsuchen sollte. Die Neusser Fehde fügte dem Kloster und der Kirche wie bereits erwähnt 1474 großen Schaden zu. Neben den Plünderungen und Zerstörungen blieb die Knechtstedener Pietà aber erhalten. Auch die Schrecken des Dreißigjährigen Krieges von 1618 bis 1648 und die Pestzeit in Knechtsteden 1637 überlebte das Gnadenbild. Gerade im 17. Jahrhundert zu Pestzeiten spendete es Betern und Pilgernden Trost. Schließlich pilgerten etwa viele Mütter gefallener Söhne oder dahinsiechender Pestkranker nach Knechtsteden. Als „Not Gottes“ bezeichneten jene Betende die Knechtstedener Pietà, da Gottes Sohn die Not aller Menschen auf sich genommen hat. Der Betende legt seine Nöte im Gebet also ebenfalls Maria in den Schoß.
Waren das 12. und beginnende 13. Jahrhundert noch aufstrebende Zeiten des jungen Klosters, so folgten auf sie dunklere. Die wenigen Quellen berichten von finanziellen Problemen durch Misswirtschaft und Verschwendung der Äbte. Auch Kriegswirren, etwa die Schlacht von Worringen 1288, in denen das Kloster Abgaben zu leisten hatte, schädigten die finanzielle Lage Knechtstedens erheblich. Hinzu kommt, dass die Kleriker zunehmend ihre klösterlichen Regeln missachteten und ungehorsam wurden. Papst Alexander IV. rügte sie in einem Schreiben vom 11. März 1256. Schenkungen adliger Familien an Klöster gingen meist an Abteien besonders guten Rufs, die für die Seelen der Schenkenden beten sollten. Jene Zuwendungen an die Abtei Knechtsteden wurden mit schlechtem Ruf also seltener.      
Die Neusser Fehde 1474 war für das Kloster eine Katastrophe, auf die jedoch eine Zeit der Blüte folgte. Abt Ludger führte die vor der Gefahr geflüchteten Prämonstratenser zurück nach Knechtsteden und ließ die Schäden beseitigen sowie die Erneuerung einleiten. Auch der Altarraum, der Ostchor, ist im gotischen Stil neuerrichtet worden. Wenn Sie hinüber zum Altar blicken, erkennen Sie, dass der Altarraum ab der Fensterunterkante erneuert wurde. Die gotischen Fenster fügen sich in den Raum, mystifizieren ihn und lassen den Besucher den Blick gen Himmel heben. Offensichtlich führten die Zeiten höchster Not zur Besinnung. Schließlich regte Abt Ludger auch die Erneuerung geistlichen Lebens an. 1502 scheint sich auch die wirtschaftliche Lage stabilisiert zu haben, da mit dem Bau des neuen Refektoriums, eines Speisesaals, begonnen wurde. Die geistliche Standhaftigkeit und Treue gegenüber dem „alten katholischen Glauben“ bewiesen die Prämonstratenser aus Knechtsteden auch während der Reformation und bildeten eine Stütze für die Gegenreformation. 1570 entsandte Abt Gerhard etwa einige Kanoniker nach Magdeburg, um die alte Ordnung im dortigen Prämonstratenserstift wiederherzustellen. Kriegerische Auseinandersetzungen im Glaubenskampf zwischen Protestantismus und Katholizismus schadeten dem Kloster jedoch erheblich. So etwa im Kölner Krieg von 1583 bis 1588, als der Kölner Erzbischof zum Protestantismus übertrat. Knechtsteden hatte mit 25.000 Reichstalern die Gegenreformation zu versorgen.
Im darauffolgenden 17. und 18. Jahrhundert erfuhr Knechtsteden noch ein letztes Mal unter den Prämonstratensern eine Blüte. So wurde das Kloster weiter ausgeschmückt und barockisiert. Von dem barocken Schmuck ist hier in der Basilika wahrlich nichts übriggeblieben, da die französischen Truppen unter Napoleon plünderten, was getragen werden konnte. Nichtsdestotrotz sind einige wenige barocke Elemente geblieben. Schon der erste Eindruck Knechtstedens am Torhaus ist ein Zeugnis des 18. Jahrhunderts. Im Kloster selbst wurde im 17. Jahrhundert die geräumige Sakristei errichtet. Im Zuge der Erneuerung der Dächer wurde das gesamte Gebäude noch einmal erhöht. Auch wurde die heutige Hauskapelle zwischen 1678 und 1698 an die Nordseite des Querschiffs angebaut. Schauen Sie gleich gern einmal hinein. Begeben Sie sich aber zunächst an der Pietà vorbei zum südlichen Nebenschiff. Ins Auge fällt sofort die Grabplatte, die in der Wand eingelassen ist. Über der Grabplatte schmücken Heilige die Fenster des Nebenschiffs. Die Platte gehört zur Grablege des Abtes Petrus Teveren, der sich, ähnlich wie sein Onkel Leonhard Teveren, in Knechtsteden durch Reformbereitschaft und wirtschaftliche Stabilisierung verdient gemacht hat. Im Folgenden werden wir immer wieder auf Wappen von Äbten stoßen, die sich haben verewigen lassen. Gerade zur Zeit des Barocks regierten die Äbte wie kleine Kirchenfürsten. Die Wirkung nach außen und der Prunk, der den Herrschenden ehren sollte, stehen dabei im Zentrum barocker Kunst.
Gehen Sie nun hinüber zum Altarraum. Hier erinnert die im Boden eingelassene Gedenktafel an den letzten Ruheort Alberts von Aachen. Verweilen Sie hier entweder kurz zu seinem Gedenken oder gehen Sie weiter zur Sakramentskapelle an der Nordseite des Querschiffs.Beachten Sie vor Eintritt in die Kapelle die Gewölbekonsole im nördlichen Querhaus. Dem aufmerksamen Beobachter wird der dargestellte Kopf, der an Kaiser Friedrich I. erinnert, nicht entgehen. Die Konsole stammt wohl aus der Stauferzeit und fällt in die Bauphase unter Albert von Aachen – dies macht auch Sinn. Das Idealbild des Kaisers mit Krone sollte wohl auf den Schutz und die Anerkennung des Kaisers aufmerksam machen. Treten Sie nun kurz in die Sakramentskapelle ein. Den barocken Raum aus dem 17. Jahrhundert ziert ein Sterngratgewölbe. Die 18 Kapitelle und Konsolen markieren den Beginn der himmlischen Zone. Darüber hinaus ist die Kapelle allerdings einfach gehalten. Vermutlich wird der Schmuck, wie oben bereits erwähnt, durch die Plünderungen der Franzosen unter Napoleon entwendet worden sein.
Mit der Invasion Napoleons und dem Vordringen der Franzosen in das Rheinland endet wenig später auch die Geschichte der Prämonstratenser in Knechtsteden, die das Kloster unter ihrem letzten Abt Hendel am 04. Oktober 1794 fluchtartig verlassen mussten. Zwar kehrten die ehemaligen Bewohner nach etwa neun Monaten zurück, fanden allerdings eine geplünderte, verwüstete und heruntergekommene Klosteranlage wieder. 1802 folgte dann die Säkularisation und der Reichsdeputationshauptschluss durch Napoleon – die Abtei Knechtsteden teilte ihr Schicksal mit 17 anderen Klöstern des Rhein-Kreises Neuss und wurde aufgehoben. Einer der ehemaligen Mönche des Prämonstratenserstifts, der von vermögendem Hause stammende Winand Kayser, pachtete seine eigene Abtei und rettete sie so vor ihrem endgültigen Untergang. 1810 sollte das Kloster aber versteigert werden. Kayser ersteigerte es über die befreundete Industriellenfamilie Herbertz aus Uerdingen und richtete die Basilika und die Gebäude wieder her. Mit seinem Tod 1842 verließ ein Helfer für Notleidende diese Welt. Kayser wurde auf dem Melatenfriedhof in Köln beerdigt. Nach seinem Tod wechselten die Besitzer des Klosters mehrfach. 1867 kaufte dann die Armenverwaltung Kölns das Kloster mitsamt Besitz. Geplant war die Errichtung einer Heilanstalt für etwa 400 psychisch Kranke. Der verheerende Brand von 1869 machte dem Plan aber einen Strich durch die Rechnung. Wer nicht an Zufälle glaubt, will wohl eher dem Gerücht Glauben schenken, Straberger Unbekannte hätten den Brand absichtlich gelegt, um die Heilanstalt zu verhindern. Anton Scheben, der Großneffe des „letzten Mönches“, wie Winand Kayser genannt wurde, wollte das Werk seines Großonkels retten. Bei Kaiser Wilhelm I. machte er sich für Knechtsteden und dessen Erhalt stark, erhielt zu diesem Zweck 5.000 Taler Zuschuss und gründete einen „Bau- und Reparaturverein“. Ein weiterer Verein wurde in Neuss gegründet. Knechtsteden sollte bereits 1881 nach den alten Plänen erneuert werden. Die Prämonstratenser aber blieben nach fast 80 Jahren der Aufhebung des Klosters fern.
Verlassen Sie die Kapelle nun wieder und folgen Sie rechts dem nördlichen Nebenschiff Richtung Westapsis. Beachten Sie das zweite Fenster von rechts im Nebenschiff. Es zeigt eine Figur, die Ihnen bereits zu Beginn der Führung bekannt geworden ist – Franz Maria 
Paul Libermann, der Gründer der Kongregation vom Heiligsten Herzen Mariens, die nach der Vereinigung mit der Gemeinschaft vom Heiligen Geist 1845 zum Orden der Spiritaner wurde. Hören Sie sich unten gern die zusätzlichen Informationen zur Gründung des Spiritanerordens an. Pausieren Sie entweder die aktuelle Wiedergabe oder hören Sie sie bis zum Schluss, bevor Sie die historischen Hintergründe der Spiritaner zur Kenntnis nehmen. Die Spiritaner kennzeichnen jedenfalls die zweite Epoche Knechtstedens, deren Spuren in den kommenden Stationen deutlich zum Tragen kommen.
War bisher vor allen Dingen Sichtbares Gegenstand unserer Führung durch die Basilika, widmen wir uns nun auch der unsichtbaren Kunst des Klangs. Gehen Sie ein Stück weiter bis zur Orgel. Sie steht erst seit 2009 in der Basilika. Ursprünglich stammt dieses um 1850 von William Holt in Leeds erbaute Musikinstrument aus einer Methodistenkirche in Tockwith, einem Dorf 20 Kilometer westlich von der historischen englischen Großstadt und Kirchenmetropole York. Nach der Schließung der dortigen Kirche wurde die Orgel restauriert und gelangte nach Knechtsteden. Die Orgel verfügt über 15 klingende Register, verteilt auf zwei Manuale und Pedal.
- Ein weiterer klingender Schatz der Basilika ist das Geläut – mit etwas Glück werden Sie es zum Beispiel gegen Mittag bereits gehört haben. Das erste Fünf-Geläute wurde unter Prämonstratenser-Abt Leonhard Jansen, der auch den Abriss der Magdalenenkapelle veranlasst hat, angeschafft. Mit der Säkularisierung von 1802 wurde es jedoch von den Franzosen beschlagnahmt und verkauft. Der Glockenstuhl fiel außerdem 1869 den Flammen des Großbrandes zum Opfer. Heute trägt der 1890 wiederhergestellte Glockenstuhl ein fünfstimmiges Geläut aus dem Jahre 1932. Ihr Erhalt ist ein unglaublicher Glücksfall. Mit Ausnahme der größten Glocke, der im Durchmesser 1791 mm und 4021 kg messenden Dreifaltigkeitsglocke, wurden alle von den Nationalsozialisten 1940 konfisziert. Sie sollten zu Kriegszwecken eingeschmolzen werden. Die Dreifaltigkeitsglocke passte nicht durch die Kuppelöffnung und blieb in Knechtsteden. Die übrigen vier tauchten nach dem Krieg in Hamburg auf einem sogenannten „Glockenfriedhof“ zufällig wieder auf und wurden an ihren Platz zurückgebracht. Das Glockenwunder von Knechtsteden war perfekt!
Die Namen der mit Reliefs verzierten fünf Knechtstedener Glocken wurden bewusst gewählt: die im „B“ läutende Dreifaltigkeitsglocke, die Marien-Glocke im „des“ für den Marienwallfahrtsort Knechtsteden, die Andreas-Glocke im „es“ zu Ehren des Kirchenpatrons, die 
Norbertus-Glocke im Ton „f“ in Anlehnung an den Gründer des Prämonstratenserordens und die Amandus-Glocke im „ges“. Letzterer Name bezieht sich auf Amandus Acker. Der Spiritaner Pater Amandus Acker, vormals Missionar auf Sansibar, eröffnete 1895 auf Veranlassung der Ordensleitung die Niederlassung der Spiritaner in Knechtsteden. Acker sollte eine Schule zur Ausbildung von Missionaren für die deutschen Kolonien, insbesondere in Ostafrika, einrichten. Knechtsteden galt zwar als ein herrlicher Standort, die Abteikirche 
war wiederhergestellt, doch das Kloster lag noch in Ruinen und den Spiritanern fehlte das Geld. Die Bauvereine aus Köln und Neuss schlossen sich zusammen und generierten die notwendigen, fehlenden Gelder über 10.000 (!) zahlende Mitglieder. Der rekonstruierte Wiederaufbau im barocken Stil konnte beginnen. Die Spiritaner hatten ein neues Zuhause in Knechtsteden.
Wir neigen uns dem Ende dieser zugegebenermaßen langen Station in der Basilika zu. Gehen Sie weiter das Nebenschiff entlang, bis Sie vor einer Tür stehen. Sie gelangen über diese Tür in den Kreuzgang des Klosters. Widmen Sie Ihre Aufmerksamkeit kurz der kalksteinernen Antoniusstatue an der Westwand der Kirche. Sie wurde 1904 in der Basilika zu Ehren des für Knechtsteden bedeutenden Anton Scheben, der 1903 gestorben war, aufgestellt. Vermutlich in den 1960er Jahren wurde sie dann in einen kleinen Park neben dem Pilgerhaus versetzt. 2020 rettete man die Statue vor den ihr zusetzenden Witterungsbedingungen und holte sie in die Basilika zurück. Sie soll bis heute an die Verdienste des Förderers und Gestalters Scheben erinnern.
Bevor Sie die Tür rechts zum Kreuzgang betreten und damit die nächste Station beginnen, wenden Sie Ihren Blick kurz auf die eingerahmte Urkunde rechts der Tür. Es handelt sich um eine besondere Anerkennung aus dem Jahre 1974. Wegen ihrer überregionalen Bedeutung für die Seelsorge und Kunstgeschichte ist die Klosterkirche Knechtsteden zur päpstlichen „Basilica minor“ erhoben worden – aus unserer Sicht kaum überraschend, zieht man die vielen Besonderheiten, die wir eben erwähnt haben, in Betracht.''',
      video: "assets/guidevideos/Kapitel_3.mp4",
      zusatztext:
          '''Die Spiritaner, eigentlich Missionsgesellschaft vom Heiligen Geist und vom Unbefleckten Herzen Mariens, sind eine katholische, missionierende Gemeinschaft, deren Geschichte bereits 300 Jahre zurückreicht.
Einer der zwei Gründer, auf die die Spiritaner zurückgehen, ist Claude François Poullart des Places. In Paris kaufte dieser ein Haus, um jungen Männern aus armen Verhältnissen das Studium zum Priester zu ermöglichen. Ziel war es, dass die jungen Männer nach ihrer Ausbildung in jenen Gebieten arbeiten sollten, für die die Kirche nur schwer Seelsorger findet. Frankreich war schließlich Kolonialmacht. Gerade in Übersee und in ländlicheren Regionen Frankreichs fehlte es an Geistlichen. 1703 gründete Poullart des Places die Genossenschaft vom Heiligen Geist, um seine Ziele zu verwirklichen.
Poullart des Places ist nur einer der zwei Gründer des heutigen Spiritanerordens. 1845 vereinen sich die Genossenschaft des Places‘ mit der von Franz Maria Paul Libermann gegründeten Missionsgesellschaft vom Unbefleckten Herzen Mariens. Auch Libermann gründete seine Kongregation für die Seelsorge der Einheimischen in den französischen Kolonien, genauer: der befreiten Sklaven. Mit der Vereinigung lag der Fokus der Arbeit der Spiritaner also eindeutig auf der Mission in Übersee.       
Franz-Maria Paul Libermann war ein Konvertit. Er entstammte einer Rabbinerfamilie und ist streng jüdisch erzogen worden. Als er 1822 nach Metz in Lothringen zur Talmudschule geschickt wurde, erfuhr er von den dortigen Mitstudenten aufgrund seines Wunsches, seine Französischkenntnisse zu verbessern, Verachtung. Dies ist vor dem Hintergrund der Feindschaft zwischen den überwiegend deutschsprachigen Lothringern und den Franzosen zu verstehen, auf deren Staatsgebiet Metz lag. Jene Verachtung hatte eine Abkehr Libermanns, von Brüdern desselben Glaubens ausgegrenzt, zur Folge. Er begann, sich mit seinem Glauben kritisch auseinanderzusetzen. Dass für Gott ein Volk auf Kosten aller anderen auserwählt sein sollte, lehnte Libermann 
ab. Vielmehr seien alle Völker die Völker Gottes. Damit wurde in ihm der Grundstein für die Idee der Missionierung gelegt. In den folgenden Jahren näherte er sich dem Christentum an und ließ sich 1826 taufen.
Zwar trat Libermann in das Priesterseminar ein, scheiterte jedoch aufgrund eines epileptischen Anfalls. 1839 fühlte er sich innerlich aufgerufen, Menschen anderen Glaubens mithilfe eines Ordens zu missionieren. Zuvor hatte er über seine Mitstudenten von der Situation der Sklaven und Einheimischen in den Kolonien gehört. 1840 brach er nach Rom auf, um eine päpstliche Bestätigung seines Ordens zu erwirken, die ihm zugesprochen wurde, nachdem er 1841 seine Priesterweihe nachholen konnte. Sein verbesserter gesundheitlicher Zustand sei durch eine Heilung auf der Pilgerreise nach Loretto eingetreten. Nach der Vereinigung der Kongregationen wird er der erste Ordensobere der zusammengeschossenen Gemeinschaften, der Spiritaner, und förderte die Überseemission bedeutend. 1852 starb Libermann, die Legende besagt, im Geruch der Heiligkeit.
Dass die Spiritaner in Deutschland und Knechtsteden Fuß fassen konnten, ist nicht selbstverständlich. Die Ordensleute und ihre Missionsgesellschaft vom Heiligen Geist ließen sich nämlich schon einmal in Deutschland nieder. 1863 hatten die Spiritaner Niederlassungen in Düsseldorf-Kaiserswerth, Marienstatt und Mariental im Westerwald. Im Kulturkampf des Deutschen Reiches unter der Federführung Bismarcks ist der Orden aber 1873 verboten worden. Die Mitglieder wanderten damals vor allem 
in die Provinzen nach Polen und in die USA aus. Die Rückkehr nach Deutschland, erstmalig in Knechtsteden, war wohl auch deshalb möglich, weil die Spiritaner in ihrem Wirken für Kaiser Wilhelm II. attraktiv ausgerichtet waren. Die kolonialen Bestrebungen des Kaisers verlangten nämlich auch kirchliche und moralische Begleitung in den Kolonien. Die Spiritaner konnten daher staatspolitischen Interessen dienen und wurden so nicht nur erlaubt, sondern sogar gefördert. Die Wiederkehr in Knechtsteden unter Pater Amandus Acker haben Sie ja bereits vorhin zur Kenntnis genommen.
Auch heute wirken die Spiritaner und verkünden die Frohbotschaft. In mehr als 60 Ländern auf der Welt leben und arbeiten die Spiritaner gegenwärtig. Schon zur Zeit ihrer Gründung übernahmen sie seelsorgerische Aufgaben dort, wohin sonst niemand wollte. Ihr Auftrag beruft sich von Beginn an darauf, das Evangelium jenen zu verkünden, die es nicht oder kaum zu hören bekommen haben. Die Spiritaner stehen dabei für jene ein, die unterdrückt, entrechtet oder ausgegrenzt sind. Leider finden die Spiritaner wieder vermehrt Tätigkeitsfelder in Europa. Der Seelsorge von Flüchtlingen oder Drogenabhängigen nehmen sie sich ebenso an wie den klassischen Einsatzgebieten in Afrika und Südamerika.''',
      zusatzvideo: "assets/guidevideos/Zusatz_Spiritaner.mp4",
      mapvideo: "assets/navvideos/Nav_3.mp4",
      next: 3),
  StationInfo(
    4,
    xcoord: 51.07686539713518,
    ycoord: 6.752528216135492,
    name: 'Kloster\nund Kreuzgang',
    iconImage: 'assets/guideicons/kloster.png',
    fulltext:
        '''Treten Sie nun durch die Tür in den Kreuzgang. Sollte die Tür verschlossen sein, dürfen wir Sie mit Bildern auf Ihrem Endgerät vertrösten. Setzen Sie sich in diesem Fall gern auf eine der Bänke in der Basilika. Lassen Sie den Gang auf sich wirken.
Seit der ersten Klostergründung 529 durch den Heiligen Benedikt in Montecassino bestimmte die Gemeinschaftsregel den architektonischen Aufbau eines Klosters. Die Gemeinschaft der im Kloster lebenden Mönche oder Nonnen brauchte eine Kirche, die 
hier in Knechtsteden am Südgang angeschlossen ist, Räume der Versorgung, etwa eine Küche, einen Schlaf- und Speisesaal am Nordgang, Verwaltungsbereiche sowie eine Pforte mit Sprechzimmer am Westgang und nicht zuletzt jene Räume, die mit der Kirche zu tun hatten, am Ostgang, so z.B. die Sakristei. Die sakralen Räume sind deshalb gen Osten ausgerichtet, da die dort aufgehende Sonne bekanntermaßen symbolisch aufgeladen ist. Abgesehen von der Symbolik der Auferstehung, glaubte man das Paradies im Osten. All diese Bereiche wurden um den Kreuzgang herum gebaut, der einen Hof mit Brunnen umschloss. Das Wort Kloster stammt aus dem lateinischen „claustrum“, „verschlossener Ort“ zu Deutsch. Im Kloster macht der Bewohner so vor allen Dingen im Innenhof die transzendentale Erfahrung der sicheren und paradiesischen Abgeschiedenheit.
Der sparsame Bauschmuck, der auch in der Basilika deutlich wird, ist für die Reformorden der Zisterzienser und Prämonstratenser typisch. Der ehemalige Knechtstedener Kreuzgang galt als ein Höhepunkt spätromanischer Bauornamentik am Niederrhein. Im Zuge der Barockisierung zu Beginn des 18. Jahrhunderts ging jene romanische Kunst jedenfalls in Knechtsteden verloren. Die Prämonstratenser verwahrten die ehemals verbauten Kapitelle aus der Gründungszeit zwar im Lapidarium, einer eigenen Sammlung, viele der Teile sind jedoch zu napoleonischer Zeit und später verschollen, verkauft oder woanders verbaut worden. Besonders schmuckvolle Stücke sind im Landesmuseum in Bonn aufzufinden. Der Südgang, in dem Sie sich gerade befinden, wurde im 20. Jahrhundert im Stile der Neoromanik wiederaufgebaut. Besonders sichtbar wird dies wieder an der Decke. Schauen Sie gern einmal durch eines der Fenster zum Innenhof. Die typische Anlegung des Gartens im Innenhof des Klosters spielt bewusst an das biblische Paradies an, in dessen Mitte ein Brunnen steht. Nach Deutung der Kirchenväter baute man in Klosterkreuzgängen den sogenannten Vierströmebrunnen als Sinnbild für Christus und seine Frohe Botschaft, die über die vier Ströme 
in alle Teile der Welt getragen werden sollte. So war er auch in Knechtsteden angedacht. Der für Sie sichtbare Brunnen ist von Spiritanerpater Heinz Sand Ende des 20. Jahrhunderts entworfen worden, der ursprüngliche ist nicht erhalten geblieben.
Dem Kloster sehr wohl erhalten geblieben ist hingegen ein historischer Altbestand der Knechtstedener Hausbibliothek, die sich auf der Ostseite des Kreuzganges befindet und nicht öffentlich zugänglich ist. Sie gehörte außerdem der ehemaligen Ordenshochschule. Das älteste Werk der Sammlung ist eine Baseler Ausgabe der Augustinusschrift „De civitate Dei“ von 1490(!). Nach Absprache kann die Bibliothek besichtigt werden. Auch findet regelmäßig am letzten Mittwoch eines jeden Monats um 20 Uhr der Knechtstedener Bibliotheksabend statt. Die Vortragsthemen werden durch Aushang und Internetseite des Klosters bekanntgegeben. Spannend sind auch die Einblicke in historische Bücher, die passend zum Vortragsthema vorgestellt werden.    
Die vor Ihnen befindliche Ausstellung, die im Südgang immer wieder wechselt, fällt dem Besucher sofort auf. Nehmen Sie sich gern die Zeit und tauchen Sie etwas tiefer in das spannende Leben und Wirken der Knechtstedener Spiritaner ein.
Sind wir bisher eher auf der Stelle getreten, möchten wir mit Ihnen nun etwas mehr das weitläufige Terrain erkunden. Starten Sie hierfür die Navigation zur nächsten Station.''',
    video: "assets/guidevideos/Kapitel_4.mp4",
    mapvideo: "assets/navvideos/Nav_4.mp4",
    next: 4,
  ),
  StationInfo(
    5,
    xcoord: 51.07721720328484,
    ycoord: 6.752250162141913,
    name: 'Missionshaus\nund Pilgerhaus',
    iconImage: 'assets/guideicons/klosterladen.png',
    fulltext:
        '''Mit Übernahme Knechtstedens durch die Spiritaner 1895 wurde im Jahr darauf auch eine Missionsschule eingerichtet, in der künftige Missionare ihre gymnasiale Ausbildung erhielten, die auf die schwierige Missionsarbeit vorbereiten sollte. Über 700 Missionare sind bis heute aus Knechtsteden in alle Welt geschickt worden, um die Frohbotschaft zu verkünden. Auf diese Weise nutzten die Spiritaner Knechtsteden bis 1947. Dies belebte den damals langsam aussterbenden Ort Knechtsteden erneut – die Spiritaner waren ein Segen. Die Klostergebäude, so auch das rosafarbene Missionshaus, lagen in Schutt und Asche. Die Spiritaner bauten sie in ihrem ursprünglichen spätbarocken Stil wieder auf. Heute zeigt die Fassade das Wappen der Spiritaner über der Pforte. Schauen Sie sich dieses einmal genauer an. Vor dem Dreieck, das symbolisch in der Ikonographie für die Dreifaltigkeit Gottes steht, ist eine Taube abgebildet. Die Taube symbolisiert den Heiligen Geist und verweist somit auf die „Gesellschaft vom Heiligen Geist“, den 1703 in Paris gegründeten Männerorden, der sich 1845 mit der „Missionsgesellschaft vom unbefleckten Herzen Mariens“, deren Gründer Libermann war, vereinigte. Die Kongregation findet sich im unbefleckten Herzen Mariens auf dem Wappen wieder.
Drehen Sie sich nun zum Pilgerhaus auf der anderen Seite um. Es ist gewissermaßen der Beweis für die Wiederbelebung Knechtstedens. Seit die Spiritaner Knechtsteden wieder aufbauten, wurde es ein autarkes Dorf, das sich also selbst versorgen konnte. Dafür sorgte nicht nur die vorbildliche Landwirtschaft und die handwerkliche Ausbildung und Arbeit, sondern auch die Wiederaufnahme geistlichen Lebens in Knechtsteden. Der alte Pilgerort zur „Schmerzhaften Mutter Gottes“ erfuhr eine wahre 
Renaissance. 1925 wurde deshalb dieses Pilgerhaus errichtet, um den Pilgernden eine Unterkunft anbieten zu können. Heute befindet sich im Pilgerhaus eine Meisterschule des Zentralverbands des deutschen Augenoptikerhandwerks. Es diente aber unmittelbar nach dem II. Weltkrieg auch lange Zeit als Altenheim. Unter den Nationalsozialisten wurde das Pilgerhaus für Gehirnoperationen an verwundeten Soldaten genutzt. Darauf soll jedoch an späterer Stelle noch einmal eingegangen werden.       
Gehen Sie ein paar Schritte weiter und achten Sie auf das Wappen an der braunen Fassade. Es gehört Wilhelm von Hövel, einem Bergwerksbesitzer aus Dortmund. Bevor Knechtsteden von der Armenverwaltung übernommen wurde, kaufte von Hövel 1857 den gesamten Besitz und wollte seinen Herrensitz hier einrichten. Dabei galt von Hövel als „Kulturbanause“, weil er die Basilika pietätlos als Lagerraum nutzte. An der Stelle seines Wappens errichtete er als repräsentativen Eingang einen Torbogen mit Türmchen. Später riss man diesen wieder ab. Das Wappen wurde zu seinem Andenken an die Wand angebracht. Tatsächlich war man aber froh, dass von Hövel aufgrund seines finanziellen Konkurses Knechtsteden rasch wieder verkaufen musste – wer weiß, welche Untaten die Basilika andernfalls hätte ertragen müssen.
An dieser Stelle möchten wir Sie ganz herzlich einladen, eine kurze Pause zu machen und den Klosterladen gleich neben dem Wappen von Hövels zu besuchen. Im Klosterladen Knechtsteden gibt es ein umfassendes Angebot an regionalen und fair gehandelten Produkten sowie kunsthandwerklichen und religiösen Gegenständen. Es werden auch selbsthergestellte Lebensmittel angeboten, wie Marmelade, Schwarzbrot oder der klostereigene Likör. Beachten Sie: Knechtsteden ist reich an Obstwiesen. Obstprodukte werden deshalb nur wenige Meter entfernt hergestellt. Neben den regionalen und selbst hergestellten Produkten sind auch Produkte aus der Dritten Welt erhältlich. Den Betrieb ermöglichen erst die rund 40 ehrenamtlichen Mitarbeiter. Vielleicht möchten Sie ja mit dem Kauf eines Souvenirs das Kloster unterstützen. Sowie Sie so weit sind, fahren Sie mit der nächsten Station fort.''',
    video: "assets/guidevideos/Kapitel_5.mp4",
    mapvideo: "assets/navvideos/Nav_5.mp4",
    next: 5,
  ),
  StationInfo(
    6,
    xcoord: 51.077360657685986,
    ycoord: 6.752786484128415,
    name: 'Alte Prälatur',
    iconImage: "assets/guideicons/praelatur.png",
    fulltext:
        '''Wir reisen an dieser Stelle noch einmal zurück in die Zeit der Prämonstratenser: Eine Prälatur, wie Sie sie vor sich sehen, bezeichnet das Amts- und Wohngebäude des Prälaten, eines Geistlichen in Vorrangstellung. Die alte Prälatur in Knechtsteden ist das ehemalige Abtshaus. Petrus Gillrath, den wir zum Ausgang aus der Basilika bereits erwähnten, ließ diese damals neue Prälatur im barocken Stil um 1670 errichten. Dies weist auf das veränderte klösterliche Leben im 17. und 18. Jahrhundert hin. Das meist reich ausgeschmückte und architektonisch besondere Abtshaus diente repräsentativen Zwecken. Der Bau der Prälatur unterstreicht das Selbstverständnis der Knechtstedener Äbte als fürstenähnliche Geistliche. Ab dem 18. Jahrhundert sind sogar Pontifikalhandlungen, Handlungen, die eigentlich Bischöfen vorbehalten sind, durch Knechtstedener Äbte nachgewiesen. So weihen jene etwa andere Äbte ihnen unterstellter Abteien, Kapellen, Altäre und vieles mehr. 
Der Bau der Prälatur beweist aber auch, dass sich Knechtsteden von den Wirren der vergangenen Jahrhunderte des Glaubenskampfes erholt hatte. Offensichtlich stand das Kloster nicht nur wirtschaftlich stabil da, sondern konnte auch ein geordnetes Klosterleben nachweisen. Wer damals in den Orden eintrat, erhielt das weiße Ordensgewand der Prämonstratenser. Nach absolviertem Einführungsjahr, dem Noviziat, folgte das Theologie- und Philosophiestudium. Die Vorlesungen hielten die Knechtstedener bis 1615 selbst ab, dann nahmen sie am „Seminarum Norbertinum“ im Steinfelder Hof in Köln teil. Ein Dokument von 1639, also nicht einmal 30 Jahre vor der Weihe Gillraths, beziffert den Mitgliederstand in Knechtsteden auf 50 – 20 in der Abtei, 30 auswärts in 10 Pfarreien und 7 anderen Stiften. Der Abt hatte über seine Mitglieder des Konvents, die Konventualen, zu wachen, von denen er gewählt wurde. Er vergab Ämter, etwa das des Priors, der den Abt vertrat. Zum Erhalt und zur Pflege der Kirche brauchte es einen Sakristan. Den Chorgesang leitete der Cantor, dessen auf Pergament geschriebenes Missale noch heute in der historischen Bibliothek im Kreuzgang aufbewahrt wird. Die Verwaltung der umfassenden Besitztümer, Ländereien, Weinberge in Remagen, Getreide- und Ölmühlen, oblag dem Procurator. Handwerkliche oder landwirtschaftliche Arbeiten wurden von Laienbrüdern verrichtet. Die Abtei Knechtsteden konnte wirtschaftlich also nur florieren, wenn jeder seine Aufgaben angemessen und pflichtgemäß erfüllte.
Schauen Sie sich das prächtige Portal genauer an. Es ist geprägt von einem großdimensionierten Wappen. Jenes ließ der Abt Keuter 1773 im Zuge weiterer Renovierungen und Ausschmückungen der Prälatur anbringen. Die Blüte seiner Zeit, die sich in 
diesem Portal widerspiegelt, sollte bald vergehen. Die letzte Weihe in Knechtsteden fand 1780 statt, bevor die Prämonstratenser unter Abt Hendel vor den Franzosen flohen.
Die Spiritaner nutzten dann die Prälatur zu Schulzwecken. Zwar hat der Vorsteher der Spiritaner in Knechtsteden, der Superior, seine Räume in der Prälatur bezogen, um seinen klosterleitenden Aufgaben nachzugehen, Ausbildungsunterricht fand in den übrigen Räumen jedoch ebenfalls statt. Als in Knechtsteden dann nach dem II. Weltkrieg das Heilig-Geist-Gymnasium gegründet wurde, hatte der erste Schulleiter, Pater Baumjohann, in den heutigen Räumen 401 und 407 sein Direktorenzimmer. Heute werden die Räume der Alten Prälatur zu Unterrichtszwecken gänzlich vom Norbert-Gymnasium genutzt – hierzu später mehr.''',
    video: "assets/guidevideos/Kapitel_6.mp4",
    mapvideo: "assets/navvideos/Nav_6.mp4",
    next: 6,
  ),
  StationInfo(7,
      xcoord: 51.07753653918695,
      ycoord: 6.751702995818423,
      name: 'Brüderhof\nund Brüderhaus',
      iconImage: 'assets/guideicons/klosterhaus.png',
      fulltext:
          '''Abgebildet ist Josef mit dem Jesuskind auf dem Arm. Als Patron der Arbeiter steht er dort wohl genau richtig, da die Ordensbrüder in ihren meist handwerklichen Ausbildungsberufen auf die Mission vorbereitet wurden. Die Statue ziert bereits lange den Platz, auf dem Sie sich gerade befinden. Vermutlich ist sie ein Kunstwerk aus Paris, das das Kloster unmittelbar nach Einzug der Spiritaner in Knechtsteden erwarb. Der Brüderhof diente als Versammlungs- und Freizeitort. Hier wurden Andachten oder Feste, etwa das Joseffest, abgehalten. Auch als Ort des gemeinsamen Gebets wurde der Brüderhof genutzt.
Durch die linke Baumreihe hindurch erkennen Sie das ehemalige Brüderhaus, seit es zum Bildungshaus umfunktioniert wurde auch Libermannhaus genannt, das auf Veranlassung des Superiors Pater Emil Clauss 1916 erbaut worden ist und heute von der Pension „Augenblick“ genutzt wird. Ganz offensichtlich brauchte es eine Unterkunft für die Ordensschüler und Brüder. Die Knechtstedener Ordensschule florierte. 1908 beherbergte Knechtsteden 16 Patres, 38 Brüder, 21 Seminaristen, 34 Brüderpostulanten und Novizen sowie 85 Schüler, die alle einen Platz zum Schlafen brauchten. Das Brüderhaus verweist daher auf den stark angewachsenen Orden in Knechtsteden. Zu Hochzeiten lebten 450 Seelen im Klosterdorf Knechtsteden. Anfangs schliefen die etwa 70 Brüder noch auf Strohsäcken, während die Patres immer schon im Haupthaus, dem Missionshaus, nächtigten. Mit der Zeit kamen Betten dazu, später hatten die Brüder jeweils eigene Zimmer.
Dass die Spiritaner heute nicht mehr im Brüderhaus nächtigen, liegt an der stark gesunkenen Anzahl der verbliebenen Brüder. Heute ist das Kloster Heimat nur noch weniger Ordensleute, die als Rückkehrer von ihrer Missionarsarbeit in Afrika und Südamerika nach Knechtsteden zurückgekehrt sind. 1978, als der Orden wie viele andere bereits große Nachwuchssorgen hatte, wichen die Brüder daher in das Missionshaus aus und machten Einrichtungen Platz, die Knechtsteden heute beleben.
Bis heute ist von außen die Spur der ehemaligen Kapelle am Brüderhaus sichtbar. Schauen Sie auf die länglichen Buntglasfenster in der rechten Ecke, wo das ehemalige Brüderhaus auf das von der Musikfachschaft des Norbert-Gymnasiums genutzte Gebäude trifft. Dort beteten die Brüder vor Beginn der Arbeit in ihren jeweiligen Werkstätten oder Ausbildungsbetrieben gemeinsam. Auch schrieben und komponierten die jugendlichen Bewohner Knechtstedens hier Liturgien und Lieder, die bis heute in der Klosterbasilika gesungen werden. Vor wenigen Jahren ist der Raum zu einem Konzertraum renoviert worden, den das Norbert-Gymnasium nutzt.
Gehen Sie nun zum linken Gebäudeabschluss des ehemaligen Brüderhauses. Auffällig scheint die Seitenwand des Gebäudes, das einen ehemaligen Anbau vermuten lässt. Der Anbau beherbergte eine Bäckerei als einen Betrieb neben den vielen anderen, die Knechtsteden damals zu einem autarken Dorf machten. Aufgrund der Dämpfe, die die Bäckerei erzeugte, war die Bausubstanz, insbesondere das Dach morsch. Das Gebäude war nicht mehr zu retten und wurde deshalb abgerissen. Schauen wir einmal an den anderen Betrieben vorbei.''',
      video: "assets/guidevideos/Kapitel_7.mp4",
      mapvideo: "assets/navvideos/Nav_7.mp4",
      next: 7),
  StationInfo(8,
      xcoord: 51.07726506222155,
      ycoord: 6.7514651485320645,
      name: 'Werkstätten',
      iconImage: 'assets/guideicons/werkstatt.png',
      fulltext:
          '''Einen Handwerkertrakt gab es im Kloster Knechtsteden schon zu Zeiten der Prämonstratenser. Er war für die Selbstversorgung des Klosters essentiell und umschloss daher alle Gewerke. Diese Tradition wurde dann im Jahre 1895 fortgesetzt, als sich 
die Spiritaner in Knechtsteden ansiedelten. Neben Landwirtschaft und Imkerei führten sie, oft als Meister ihres Fachs, Handwerkerbetriebe aller Art. Die Tage der Brüder waren somit immer geprägt von Gebet und Arbeit. Sie begannen schon um fünf 
Uhr morgens. Gebet und Frühstück leiteten den Tag ein, damit dann um acht Uhr die Arbeit in den Handwerksbetrieben beginnen konnte. Zu den Werkstätten gehörten: eine Schreinerei, ein Sägewerk, eine Dachdeckerei, eine Sattlerei, die eben erwähnte Bäckerei, eine Metzgerei, eine Schneiderei, eine Schusterei, eine Druckerei, eine Schlosserei, eine Schmiede, die sich unter anderem auf orthopädische Hufschmiede spezialisierte, und eine Elektrowerkstatt.
Bis in die 1960er Jahre dienten diese zahlreichen Handwerksbetriebe unter anderem als Ausgangspunkt für die Ausbildung der Ordensbrüder für ihre Arbeit in den Missionsgebieten in Übersee. Oftmals leisteten sie dort Aufbauarbeiten. Die Berufungen zum Ordensleben ließen dann jedoch immer weiter nach und der Nachwuchsmangel der Brüder endete letztlich in der Schließung der Landwirtschaft und der Werkstätten. Schließlich musste man nicht mehr Ordensbruder werden, mit allen Entsagungen, die damit verbunden waren, um Entwicklungshilfe zu leisten. Dafür wählten viele stattdessen die weltliche Berufung des Entwicklungshelfers. Die Schließung der Druckerei, die 1899 eingerichtet worden war und in der zu Hochzeiten sowohl „Echo aus 
den Missionen“, die Monatszeitschrift der Spiritaner, als auch für die Kölner Messe gedruckt wurden, unterlag nicht nur dem Mangel an Ordensbrüdern, sondern zudem dem maschinellen Fortschritt in der Branche. Um gegen die Konkurrenz anzukommen und die Auftragsbücher zu füllen, wären immense Investitionen nötig gewesen. Die ehemalige Druckerei befand sich in den Räumlichkeiten der heutigen Norbert-Bibliothek, der Schulbibliothek des Norbert-Gymnasiums. Vielleicht ist Ihnen diese schon 
aufgefallen. Sie befindet sich gegenüber der Pension „Augenblick“, dem ehemaligen Brüderhaus.
Am Beispiel der ehemaligen Druckerei wird deutlich: Zwar lagen einige der Werkstätten unberührt brach, ein Großteil jedoch wurde komplett umfunktioniert. So wird zum Beispiel die alte Schreinerei heute als Bücherstube genutzt und die ehemalige 
Schneiderei ist nun der Standort der Provinzleitung des indischen Karmeliter-Ordens.
Es sind jedoch nicht alle Werkstätten verloren gegangen. Drei Betriebe werden heute zum ehemaligen Handwerkertrakt gezählt und als historische Werkstätten angesehen: Neben der Schuhmacherei sind, dem Engagement des Fördervereins und seiner ehrenamtlichen Helfer sei Dank, sowohl die Schlosserei als auch die Elektrowerkstatt mit ihrer Dampfmaschine erhalten geblieben. Die historischen Werkstätten können durchaus als Handwerkskunde-Museen angesehen werden.
Schauen Sie einmal durch die Fenster der Werkstätten. Etwa in der Mitte der Gebäudereihe finden Sie die Schlosserei. Die Schlosserei, wo auch heute noch geschmiedet wird, wurde so beibehalten, wie sie noch im letzten Jahrhundert genutzt wurde. 
Die Werkstätten, die sich bis heute erhalten haben, sind weitaus mehr als ein Relikt vergangener Zeiten. Die Maschinen werden von einem fachkundigen Team aus der Klosterumgebung betriebsfähig gehalten. Seit Mitte Januar 2013 treffen sich jeden 
Samstag zwischen 9 und 13 Uhr ehrenamtliche Helfer des Fördervereins in der Schlosserei und nehmen die Werkstatt in Betrieb. Das dazu erforderliche, traditionelle handwerkliche Können kommt unter anderem bei Reparaturarbeiten, insbesondere im Denkmalbereich, und beim Anfertigen von Gegenständen wie Kreuz-Briefbeschwerern, die im Klosterladen erworben werden können, zum Einsatz. Jedes der Produkte ist ein handwerkliches Unikat, da sie vom Schmied freiformgeschmiedet werden.
Gehen Sie einmal weiter hinunter in die entgegengesetzte Richtung des Klosterladens und suchen Sie nochmals durch die Fenster blickend eine imposante, augenscheinliche Dampfmaschine. Jenes historische Dieselaggregat des Klosters wurde 2013, nach über 36 Jahren Stillstand, instandgesetzt. Es handelt sich um einen Dieselmotor des Baujahres 1929. Angelassen wird der Motor mit 15 bar Druckluft. Zwischen 1920 und 1932 wurden von dem Hersteller Deutz 907 solcher Diesel-Motoren zur Stromerzeugung hergestellt. Heute existieren davon nur noch rund zehn Exemplare. Das Aggregat ist somit von unschätzbarem Wert und eine eigene Besichtigung von Technikkundigen wert.''',
      video: "assets/guidevideos/Kapitel_10.mp4",
      mapvideo: "assets/navvideos/Nav_8.mp4",
      next: 8),
  StationInfo(9,
      xcoord: 51.07640061070178,
      ycoord: 6.75265162077709,
      name: 'Klosterfriedhof',
      iconImage: 'assets/guideicons/friedhof.jpg',
      fulltext:
          '''Der sich vor Ihnen erstreckende Klosterfriedhof besteht aus zwei Teilen. Den vorderen Teil bildet der sogenannte Brüderfriedhof der Spiritaner, auf dem die verstorbenen Spiritanerbrüder und Patres ruhen. Die Patres sind Ordensleute mit Priesterweihe, die Spiritanerbrüder hingegen leben ihre Berufung als Handwerker, Landwirte, Ärzte, Künstler usw. Schauen Sie sich die Grabsteine in den Reihen links und rechts einmal genauer an. Auf ihnen sind unterschiedliche Kürzel zu erkennen. "F.C.S." - Das steht für Fervor (Eifer), Caritas (Liebe) und Sacrificium (Opfersinn) und bezieht sich auf die letzten Worte am Sterbebett des Ordensgründers der Spiritaner, Franz Maria Paul Libermanns. Die wenigen Grabsteine der Ruhenden, die dem Orden der Spiritaner nicht angehörten, zeigen das Kürzel „J.M.J.“. Jenes verweist auf Jesus, Maria und Josef. Alle Steine zeigen die Namen, die die Brüder bei Ordenseintritt bekamen. Neben dem Geburts- und Todesdatum ist außerdem das Datum der Priesterweihe verzeichnet, bei den Brüdern das des Ordenseintritts.
Zu Ihrer Linken befindet sich eine Gedenkstätte für die in fremder Erde ruhenden Ordensleute der Spiritaner. Als Missionare sind diese weit in der Welt herumgekommen. Schauen Sie sich mal ihre verzeichneten Wirkungsorte an, wo sie schlussendlich ihren Frieden gefunden haben und verstorben sind. Es wird deutlich: Die Spiritaner agierten insbesondere in Afrika und Südamerika. Die Gedenktafel erinnert an alle Spiritaner, die nicht in Knechtsteden ihre letzte Ruhe fanden – so auch an jene, die in den Weltkriegen in fremder Erde gefallen waren.
An die Wirren des 20. Jahrhunderts erinnert im Besonderen das große Denkmal, das sich inmitten des Friedhofs am auffälligsten hervorhebt. Schauen Sie einmal genau hin. Abgebildet ist der Gekreuzigte. Es stehen eingemeißelt die Jahre des Ausbruchs und der Beendigung des Ersten Weltkrieges 1914 und 1918 – darunter: „Im Weltkrieg gefallen ruhen in fremder Erde“ und die Namen der gefallenen Ordensleute. Mit dem Ersten Weltkrieg beginnt für Knechtsteden eine unruhige und leidvolle Epoche.Am 1. August 1914 ließ der Kaiser die Generalmobilmachung anordnen. Auch die Brüder hatten sich auf den Weg zu ihren Truppen zu machen. Die Primaner erhielten zum Zweck der Wehrfähigkeit ein Notabitur, die Jungpriester wurden Feldkapläne und übernahmen die Seelsorge der deutschen Truppen. Pater Acker protestierte gegen den Krieg in den deutschen Kolonien entgegen den internationalen Abmachungen. Über 250 Brüder, Seminaristen, Novizen und Schüler aus Knechtsteden standen unter Waffen. 57 von ihnen sind gefallen – ihre Namen sind auf dem Denkmal verewigt.
Zwar hatte das Kloster im Ersten Weltkrieg seine Gefallenen zu betrauern, jedoch erholte es sich schnell und gelangte zu seiner alten Blüte. Aufgrund der verlorenen deutschen Kolonien nach dem Ersten Weltkrieg widmete sich der Spiritanerorden vermehrt der Mission in Südamerika, insbesondere in Brasilien, aber auch in Südafrika und Nigeria. Im Vergleich dazu setzte dem Kloster die folgende Zeit des Nationalsozialismus ungleich schwerer zu.
Gehen Sie nun einmal weiter nach vorn, die Treppen herunter, um das Denkmal herum. Auf seiner Rückseite finden Sie nun ein Relief der Mutter Gottes abgebildet. Diese Seite ist den gefallenen Spiritanern der deutschen Provinz im Zweiten Weltkrieg gewidmet. Die Zeit des Nationalsozialismus war für Knechtsteden ein schweres Joch. Schauprozesse, Schülerverhöre zur Regimetreue, Untersuchungshaft und Schikane jedweder Form sollten die Ordensmänner und Schüler auf Linie bringen. Der Zweite 
Weltkrieg intensivierte die Repression schließlich. 100 Spiritaner wurden zum Kriegsdienst verpflichtet, deren Gefallene auf dem Denkmal verzeichnet sind. Am 18. Mai 1941 war es dann so weit: Die Gestapo klopfte an der Klosterpforte und ließ die Missionsschule schließen, das Kloster aufheben. Noch zum selben Abend mussten alle Patres das linke Rheinufer verlassen haben. Lediglich einige wenige durften zur Betreibung der kriegswichtigen Landwirtschaft in Knechtsteden bleiben und wurden arbeitsdienstverpflichtet.
Wenden Sie Ihren Blick nun hinter sich auf den hinteren und damit zweiten Teil des Friedhofs. Hier ruhen überwiegend Soldaten aus dem Zweiten Weltkrieg. Sie sind alle in Knechtsteden gestorben. Zwar hat es hier keine Gefechte gegeben, jedoch ist Knechtsteden nach Beschlagnahmung durch die Nationalsozialisten als Lazarett genutzt worden. Das Pilgerhaus, das Sie bereits vor einigen wenigen Schritten beschauen konnten, wurde dabei für Gehirnoperationen und die Entfernung von Granatensplittern genutzt. Bei diesen teils sehr heiklen Operationen sind viele Soldaten ums Leben gekommen oder infolge der Operation verstorben. Auf diesem 1957 eingeweihten Soldatenfriedhof, der Kriegsgräberstätte Knechtstedens, sind 157 Kriegstote verschiedener Nationen beigesetzt. Wenn Sie unten dem Weg rechts über den Soldatenfriedhof folgen, erkennen Sie einen verklinkerten, freistehenden Sockel. Bei der metallischen Platte mit der Aufschrift „Gräberverzeichnis“ handelt es sich um eine Klappe, die Sie gern öffnen dürfen. Der Blick auf das in einer Mappe befindliche Verzeichnis der gefallenen und hier ruhenden Soldaten verrät so einiges über sie, lässt aber auch viele Fragen zurück, die bis heute unbeantwortet sind. Licht ins Dunkel bei der Klärung von Vermissten- und Verstorbenenschicksalen versucht der Volksbund Deutsche Kriegsgräberfürsorge zu schaffen. Schauen Sie einmal in das Verzeichnis hinein. Auffällig sind die Todesjahre der Verstorbenen, die alle 1944 oder 1945 ablebten. Bis 1944 beerdigte man die wenigen Toten aus dem Reservelazarett Knechtsteden nämlich noch auf Ehrenfriedhöfen der Nachbargemeinden. 1944 näherte sich die Westfront aufgrund der absehbaren Kriegsniederlage Knechtsteden immer weiter, sodass das ehemalige Reservelazarett zum Kriegslazarett umfunktioniert wurde. Der Anstieg der Verstorbenen war enorm, schließlich hatte Knechtsteden nun die Frontsoldaten zu versorgen.
Bei den 157 bestatteten Toten auf dem Soldatenfriedhof handelt es sich nicht um eine statistische Größe. Jedes Leben schreibt seine eigene spannende Geschichte. Lernen Sie unten das Leben und Schicksal Gustav Harnischs, das ihn hierhin, nach Knechtsteden, gebracht hat, kennen. Sein Kreuz finden Sie gegenüber dem Gräberverzeichnis an der Mauer zum Plateau des Spiritanerfriedhofs. Pausieren Sie entweder an dieser Stelle die aktuelle Wiedergabe oder warten Sie bis zum Ende der Station ab.
Wenden Sie sich nun der anderen Seite des Friedhofs zu. Sie sehen ein von Grün umsäumtes, steinernes Relief des Erzengels Michael, dargestellt mit Flügeln. Die Aufschrift an den Flügeln links und rechts lautet: „Zum Leben rufe ich // Zum Herrn 
geleite ich“. Aufgestellt wurde es 1957 als Ehrenmal für die gefallenen deutschen Soldaten. Der Erzengel Michael gilt als Kämpfer Gottes und Patron der Deutschen. Mit ausgebreiteten Armen schreitet er durch die Gräberreihen, um die Toten nach ihrem Kampf in den ewigen Frieden zu begleiten. Dieses Ehrenmal fügt sich natürlich in die christliche Umgebung des Klosters ein und ist in seiner Frieden und Ruhe ausstrahlenden Form bewusst gewählt worden.''',
      video: "assets/guidevideos/Kapitel_9.mp4",
      zusatztext:
          '''Gustav Adolf Harnisch ist am 11.12.1906 in Schönborn im Kreis Luckau im heutigen Brandenburg geboren. Wie viele der hier Begrabenen, stammt Gustav Harnisch also nicht aus dem Rheinland, sondern kommt von weither. Harnisch war von Beruf Bergmann und Landwirt, der für die Eigenversorgung ca. 30 Morgen Land zuzüglich Vieh bewirtschaftete. Mit seiner ersten Frau Elsbeth Frieda Meta, geb. Schippan, hatte er die Söhne Karl Heinz und Günter Gustav sowie die Tochter Giesela Ingeburg.        
Die Kriegszeit traf Harnisch schwer. Im Juni 1940 kam es zu seiner ersten Einberufung zur 1. Kompanie des Infanterie-Regiments 663. Er war vom 07.08.1940 bis zum 03.02.1941 im Einsatz in der 5. Kompanie des Landesschützen-Bataillons 224. Im selben Jahr starb seine Frau Meta nach schwerer Erkrankung, wodurch die Vormundschaft des jüngeren, nicht einmal einjährigen Sohnes Günter auf eigenen Wunsch an die Familie seiner Schwester Emma und Reinhold Bachert übertragen wurde. Im Februar 1941 erfolgte dann Harnischs vorzeitige Entlassung aus dem Wehrdienst aus privaten Gründen. Offensichtlich setzten Harnisch der Tod der Ehefrau, die offenen Sorgerechtsfragen der Kinder oder der 1941 verstorbene Vater schwer zu.
Als Harnisch wieder in Brandenburg zuhause war, zog er gemeinsam mit seiner Nachbarin Elsbeth Altmann seine Kinder Heinz und Ingeburg groß. Die Beziehung zwischen Harnisch und Elsbeth entwickelte sich von einer Zweckgemeinschaft hin zu einer Ehe. Der Ehemann Elsbeths war bereits zuvor im Krieg gefallen. Die beiden heirateten am 12.06.1943. Die neue Ehefrau brachte einen älteren Sohn mit in die Ehe. Der zweite Sohn Günter verblieb auf Wunsch seines Vaters weiterhin in der Familie seiner Schwester und wurde bis zu seinem 16. Lebensjahr in deren Haus in Schönborn großgezogen.
Am 08.09.1944 erfolgte Harnischs zweite Einberufung nach Thorn zur 6. Kompanie des Grenadier-Regiments 696, das sich ab dem 20.11.1944 im Kampfeinsatz im Jülicher Brückenkopf im Verband der 340. Volksgrenadier-Division befand. Sogenannte Volksgrenadier-Divisionen wurden seit dem 20. Juli 1944 von der deutschen Wehrmacht zum Ausgleich der schweren Verluste im Zuge der Invasion in die Normandie gegründet und bestanden zum größten Teil aus Soldaten mit geringerer Ausbildung, was zu schweren Verlusten führte. Der Jülicher Brückenkopf, eine Festungsanlage aus napoleonischer Zeit, war Ende 1944 bis Anfang 1945 der Schauplatz erbitterter Kämpfe zwischen deutschen und amerikanischen Verbänden. Harnisch kämpfte am Südteil des Brückenkopfes von Bourheim bis Kirchberg.
Am 23.11.1944 zogen sich die deutschen Sicherungen zurück, um sich für eine Gegenoffensive bereit zu machen. Harnischs Einheit ist dabei durch den amerikanischen Angriff in Bourheim zerstört worden. Harnisch selbst ist tags darauf als vermisst 
gemeldet worden. Am 25.11.1944 wurde er dann durch Granatensplitter schwerverwundet geborgen und ins Kriegslazarett Knechtsteden abtransportiert, wo er am 26.11.1944 um 3:00 Uhr an den Folgen seiner schweren Verletzung verstarb. Seine Beisetzung fand im November 1944 auf dem Friedhof des Klosters Knechtsteden statt. Heinz Harnisch, der Sohn Gustav Harnischs, besuchte das Grab seines Vaters zur Eröffnung der Kriegsgräberstätte am 27.10.1957.
Seine letzte überlieferte Feldpost schrieb Harnisch an seine Nichte „Trautchen“ am 30.10.1944, also gut drei Wochen vor seinem Tod. In voller Erwartung an das Kriegsende schreibt er: „Wie Du schreibst willst Du mit dem Heiraten noch warten bis 
ich zu Hause bin, [das] [f]reu[t] mich aber. Denn wir wollen doch das Tanzbein tüchtig schwingen bei Deiner Hochzeit. […] [W]ir sollten erst zum 20. Oktober hier wegkommen, nun hat es sich aber noch verschoben, wann es nun wird[,] wissen wir auch nicht […]. Wann nun der Krieg zu Ende sein wird[,] ist noch nicht raus, ich denke aber es wird nun bald enden […].“ Seinen „Goldsohn Günter“, den Trautchen von ihm grüßen soll, konnte Gustav Harnisch nicht mehr wiedersehen.''',
      zusatzvideo: "assets/guidevideos/Zusatz_Friedhof.mp4",
      mapvideo: "assets/navvideos/Nav_9.mp4",
      next: 9),
  StationInfo(
    10,
    xcoord: 51.07861234748353,
    ycoord: 6.750253239539649,
    name: 'Kräutergarten',
    iconImage: 'assets/guideicons/kraeutergarten.png',
    fulltext:
        '''Auch am Beispiel des vor Ihnen befindlichen Kräutergartens ist es erkennbar, dass die Spiritaner Knechtsteden im wahrsten Sinne des Wortes wiederbelebten. Seit die Spiritaner Knechtsteden wieder aufbauten, wurde es ein autarkes Dorf, das sich selbst versorgen konnte. Dafür sorgte auch die vorbildliche Landwirtschaft, die bis heute fortgeführt wird. Der heutige Kräutergarten wurde früher als Hühnerhof genutzt, um ihn herum waren Felder, Äcker, Obstwiesen. Bis zu 450 Personen konnte der landwirtschaftliche Betrieb damals mit seinen Erzeugnissen versorgen. Auch heute ist direkt nebenan eine große Streuobstwiese, um welche sich das Haus der Natur in Knechtsteden kümmert. Der Kräutergarten wird von einem ehrenamtlichen, engagierten Team von 12 Personen gepflegt und erhalten. Das Ziel des Kräutergartens ist der Erhalt aussterbender und seltener Kräuter, die Schaffung biologischer Vielfalt sowie die Kräuterkunde selbst. Nicht zuletzt soll der Kräutergarten seine Besucher einladen, in der stillen Natur zu verweilen.
Sehen Sie sich mal um. Angelegt sind zehn Beete, die allesamt über die Holzspan-Wege begehbar sind. Auf den Bänken hier und dort können Sie sich auch hinsetzen und eine Weile die Ruhe genießen. Die Beete tragen unter anderem Küchenkräuter, Gemüse oder in Vergessenheit geratene Kräuter. Zwei Beete fallen jedoch besonders auf: Eines ist der Heiligen Maria, der Mutter Gottes, und eines den Symbolen des Christentums geweiht. In ersterem finden sich Kräuter, die sinnbildlich für die Eigenschaften der Gottesmutter Maria stehen. Kräuter der christlichen Symbolik wie beispielsweise Silbertaler sind entsprechend in letzterem Beet zu finden.
In der Mitte des Kräutergartens ist ein kleines Gebäude aus Backstein zu sehen. Geht man die hölzerne Treppe hinauf, bietet sich ein großartiger Ausblick auf den Kräutergarten sowie auf das Gelände, das ihn umgibt. In diesem Gebäude, welches früher der Hühnerstall war, werden Kräuter gelagert, getrocknet und vorbereitet. Anschließend werden sie in der Klosterküche zubereitet, um im Klosterladen in Form von Tinkturen, Tees, Salzen und anderen Produkten angeboten zu werden. Knechtsteden ist ein Ort der Kooperationen – 
das wird ein weiteres Mal deutlich. Auch die Kooperation mit dem Naturschutzbund ist hier zu nennen. Der Baumstumpf, der Ihnen sicherlich aufgefallen ist, erinnert an den gefällten, kranken Baum, der hier einst stand. Dafür hat man den Vögeln in Absprache mit dem Naturschutzbund bunt bemalte Vogelhäuschen geschenkt, die ihnen weiterhin Unterschlupf gewähren.
Was den Kräutergarten besonders auszeichnet, ist seine Form. Die Form, in der die Hecken geschnitten und angelegt sind, die die Beete umranden, lassen den Kräutergarten wie zwei Kirchenschiffe in Kreuzform erscheinen, die sich spiegeln. In der Mitte der beiden 
Schiffe ist jeweils ein hoher, hellgrauer Stein, welcher den zentralen Mittelpunkt der Schiffe darstellt und als Kreuz oder Altar interpretiert werden kann.
''',
    video: "assets/guidevideos/Kapitel_11.mp4",
    mapvideo: "assets/navvideos/Nav_10.mp4",
    next: 10,
  ),
  StationInfo(
    11,
    xcoord: 51.07852443117225,
    ycoord: 6.751014940273164,
    name: 'Kulturhof\nund Bullenstall',
    iconImage: 'assets/guideicons/kulturhof.png',
    fulltext:
        '''Haben wir uns bisher eher den handwerklichen Berufen gewidmet, steht nun die Landwirtschaft Knechtstedens im Vordergrund, die hier, im ehemaligen Bullenstall, noch wiederzuerkennen ist, sowie Sie sich einmal umschauen. Der Landwirtschaftsbetrieb des Klosters wurde vor dem Ersten Weltkrieg von den Spiritanern für die Versorgung von etwa 500 Menschen errichtet. Die Zucht Knechtstedener Zuchtbullen war zu ihrer Zeit bekannt und wurde mehrfach prämiert. Als die Nationalsozialisten 1941 Knechtsteden beschlagnahmten, sollte der Hof zu einem landwirtschaftlichen Mustergut umgebaut werden. Einige Brüder wurden zur Zwangsarbeit verpflichtet, wodurch ihnen jedoch der Dienst an der Front erspart blieb. Andere Patres und Brüder wurden aus Knechtsteden ausgewiesen. Zu seinen Hochzeiten konnte sich das Kloster dank seiner Landwirtschaft vollkommen autark halten und sich selbst versorgen. Bis in die 1960er Jahre wurde der landwirtschaftliche Betrieb im Kloster durch die Brüder aufrechterhalten.
Heute ist der Kulturhof, der ehemalige Bullenstall und die Theaterscheune, als Veranstaltungsort an den Klosterhof, unsere letzte Station, verpachtet. Dort finden Hochzeiten, Konzerte und auch Firmenfeiern statt. Die Felder rings um Knechtsteden werden von umliegenden Bauern bestellt. So bleibt Knechtsteden bis heute ein landwirtschaftlich geprägter Ort in der Region.''',
    video: "assets/guidevideos/Kapitel_12.mp4",
    mapvideo: "assets/navvideos/Nav_11.mp4",
    next: 11,
  ),
  StationInfo(
    12,
    xcoord: 51.07806413957527,
    ycoord: 6.751501836755097,
    name: 'Alte Feuerwehr',
    iconImage: 'assets/guideicons/feuerwehr.png',
    fulltext:
        '''An dieser Stelle möchten wir noch einmal an den verheerenden Brand von 1869 erinnern, der die gesamte Klosteranlage zerstörte. Sie erinnern sich: Als die Armenverwaltung von Köln die Klosteranlage übernommen hatte, sollte Knechtsteden als psychiatrische Klinik 
für etwa 400 Patienten genutzt werden. Einer großen Beliebtheit erfreute sich dieser Plan jedoch nicht. Insbesondere die Bauern der umliegenden Dörfer wollten die Heilanstalt verhindern. Zu therapeutischen Zwecken hätten die Patienten auf den umliegenden Feldern gearbeitet, sodass den Bauern die Pachtverträge gekündigt worden wären. Aus diesem Grund sagt man den Straberger Bauern nach, sie hätten den Brand von 1869 gelegt. Als Außenstehende den Brand zu löschen versuchten, sollen die Straberger jene daran gehindert haben. Einige Jahre nach dem Brand wurde jedoch die wahre Ursache bekannt. Ein alter Knecht hatte in der Scheune beim Anzünden einer Pfeife leichtsinnigerweise den Brand verschuldet. Sein Geheimnis trug der Mann bis an sein Lebensende mit sich. Erst auf dem Sterbebett hat er seine fahrlässige Tat reumütig gestanden. 
So oder so – als die Spiritaner 1895 Knechtsteden übernahmen, wollten sie einer vergleichbaren Brandkatastrophe vorbeugen. Dies zeigt eindrücklich, wie prägend jener Brand von 1869 gewesen sein muss. Pater Acker und die Spiritaner gründeten eine eigene Feuerwehr. Die Erfahrung hatte gelehrt, dass aufgrund der singulären Lage Knechtstedens eine Feuerwehr innerhalb der Klosteranlage nötig war. Bis die Einsatzkräfte von außerhalb in Knechtsteden ankämen, wäre es für das Klosterdorf zu spät. 
Mehrfach konnte die Knechtstedener Feuerwehr Abhilfe schaffen – etwa 1928 in den Räumlichkeiten der alten Schmiede. Das Feuer brach aus, weil sich beim Kochen aufgrund einer Unachtsamkeit ein Feuer entzündete. Gegen Ende des Zweiten Weltkrieges kam die Feuerwehr ebenfalls zum Einsatz, nachdem das Kloster von einer Brandbombe getroffen worden war. Als mit der Zeit die Feuerwehren mobiler und der Transport von Brandbekämpfungsmitteln einfacher wurde, gab man die eigene Feuerwehr in Knechtsteden auf und nutzte das Gebäude zuerst als kleine Autowerkstatt. In den Räumlichkeiten befindet sich heute die Fundgrube bzw. der Trödel- und Kleidermarkt, wo man noch alte Feuerwehrschläuche bestaunen kann. Vielleicht werden Sie ja auch fündig.
Schauen Sie aber erst einmal auf das kleine metallische Plättchen rechts der Fensterfront. Abgebildet ist der Schutzpatron der Feuerwehr, der Heilige Florian von Lorch. Dort, wo heute die Fensterfront Einblick gewährt, waren früher die Holztore verbaut, hinter 
denen die Feuerwehrwagen und -geräte bereitstanden.''',
    video: "assets/guidevideos/Kapitel_13.mp4",
    mapvideo: "assets/navvideos/Nav_12.mp4",
    next: 12,
  ),
  StationInfo(
    13,
    xcoord: 51.07758543614188,
    ycoord: 6.753780118854125,
    name: 'Norbert-Gymnasium',
    iconImage: 'assets/guideicons/gymnasium.jpg',
    fulltext:
        '''Knechtsteden erfüllen heute neben den Ordensmännern Optiker, Künstler, Biologen, Naturpädagogen, Landwirte, Musiker und Eventmanager und viele mehr mit Leben. Knechtsteden ist ein kulturelles Zentrum, etwa für Musikfestivals geworden, so auch für das überregional bekannte Festival der Alten Musik Knechtsteden. Viele Einrichtungen werden Sie während dieser Führung bemerkt oder kennengelernt haben.
Die größte und bekannteste Einrichtung auf dem Gelände des Klosters Knechtsteden ist das Norbert-Gymnasium. Die Namensherkunft muss an dieser Stelle wohl nicht weiter erläutert werden. Nach dem Zweiten Weltkrieg, 1947, eröffneten die Spiritaner unter Pater Baumjohann die Missionsschule neu. Die Ordensschule füllte sich wieder und nahm den Unterricht erneut auf. Jedoch hielt diese letzte Blüte nicht lange: In den späten 1950er Jahren erlebte das kirchliche Leben in Deutschland eine Krise, die sich auch auf die Klöster auswirkte. Die Religion verlor langsam ihre gesellschaftliche Relevanz, Knechtsteden wurde leerer. Die Ordensberufe sind ausgeblieben, viele Arbeiten mussten eingestellt werden, manche Einrichtungen wurden aufgegeben. Eine Neuerfindung Knechtstedens musste her und sollte kommen. Das Internat wurde 1967 geschlossen, die Schule vom Norbert-Verein als gemeinnütziger katholischer Schulträger übernommen. Seitdem prägen die Schülerinnen und Schüler des Norbert-Gymnasiums das Klosterleben, gegenüber den verbliebenen zwei Dutzend Ordensleuten sind sie heute mit etwa 1300 Kindern und Heranwachsenden eindeutig in der Überzahl. Die Schülerinnen kamen jedoch erst zum Schuljahr 1990/91 Jahre hinzu, als das Norbert-Gymnasium sich auch für Mädchen öffnete. Wieder retteten die Spiritaner also Knechtsteden, das erneut lebendig wurde. Bis heute hat der Norbert-Verein einen ständigen Vertreter der Spiritaner in seinem Vorstand.
Spazieren wir einmal an den Schulgebäuden gegenüber der Alten Feuerwehr vorbei. Viele zu Unterrichtszwecken genutzte Räume des Klosters haben Sie ja bereits gesehen, so etwa die Alte Prälatur oder das Libermannhaus, das das Musikzentrum des Norbert-Gymnasiums ist. Folgen Sie also dem Weg zwischen Gebäudereihe rechts und der Alten Feuerwehr links. Hinter den Holztoren, die heute zu Lagerzwecken genutzt werden, parkten dereinst Feuerwehrautos, wie Sie ja bereits vorhin erfuhren. In den Gebäuden rechts findet Unterricht statt. In der alten Scheune links, am Ende der Häuserreihe neben der alten Feuerwehr, tagt die Schülervertretung. Sie laufen nun auf einen Unterstand zu, der den Neubau links mit dem Altbau rechts, den Klostereinrichtungen, verbindet. Gehen Sie hindurch auf den Schulhof.
Beachten Sie die Marienstatue aus Sandstein im Grün des Vorgartens links an der Ecke zum Neubau. Die gekrönte Muttergottes trägt das Jesuskind auf dem linken Arm, mit der rechten Hand segnet sie. Jesus hält den Kreuzesstab, der die Schlange zu Füßen Mariens ersticht. Auf dem backsteinernen Sockel steht eingemeißelt: „Siegerin in allen Schlachten Gottes“. Die 3 Meter hohe Statue wurde 1950, also fünf Jahre nach Beendigung des Zweiten Weltkrieges, von dem Künstler Toni Stockheim entworfen. Vor diesem Hintergrund macht 
auch die Inschrift Sinn. Hier wollte man wohl auf die dunklen Zeiten der beiden Weltkriege anspielen. Als in den großen Kriegen besiegte Nation bedrückte die deutsche Öffentlichkeit das Stigma des Nationalsozialismus und seiner Verbrechen. Die Statue verweist darauf, dass die „wahre“ Siegerin aller Schlachten Gottes in der Heiligen Jungfrau Maria zu sehen sei. Am Fuße des Sockels trafen sich die Ordensschüler früher gern, um zu beten oder gemeinsam Zeit zu verbringen. Heute erinnert wenig daran, dass die Muttergottes ein beliebter Treffpunkt gewesen ist.
Gehen Sie einige Schritte weiter, sodass Sie mitten auf dem Schulhof stehen, und drehen Sie sich um. Links sehen Sie nun wieder das Kloster, in weiterer Ferne die Basilika. Rechts zu sehen ist die Frontansicht des Norbert-Gymnasiums mit seinem Haupteingang. Gegenüber dem Haupteingang, hinter den Tischtennisplatten, befindet sich das Sportzentrum des Gymnasiums.
Mit der Anerkennung als Sportschule 2014 und der Errichtung des Sportinternats gehört das Norbert-Gymnasium zur sportlichen Elite Deutschlands. Es vereint Schule, Lernen, Training und Freizeit. Die Internatsschüler vertreten Deutschland international auf Wettkämpfen und absolvieren parallel ihr Abitur. Dabei versteht sich das Norbert-Gymnasium aber nach wie vor in der Tradition seines Standortes als christliche Schule, die ihre Schülerinnen und Schüler befähigen möchte, die Gesellschaft im Geist der Frohen Botschaft 
mitzugestalten. So bleibt die Knechtstedener Schule auf eine eigene Weise mit dem Kloster und seiner Geschichte verbunden. Dieses Schulprojekt des Klosterführers ist nicht zuletzt ein Indikator für jene Verbundenheit. Wir begleiten Sie nun zur letzten Station unserer Führung.''',
    video: "assets/guidevideos/Kapitel_14.mp4",
    mapvideo: "assets/navvideos/Nav_13.mp4",
    next: 13,
  ),
  StationInfo(
    14,
    xcoord: 51.07660176969927,
    ycoord: 6.757339425377802,
    name: 'Klosterhof',
    iconImage: 'assets/guideicons/klosterhof.png',
    fulltext:
        '''1898, also kurz nach der Übernahme des Klosters durch den Spiritaner-Orden, wurde der Klosterhof erbaut. Dieses Projekt leitete Bruder Aristobul. Damals sind die Förderer und Mitglieder des „Vereins für das Missionshaus Knechtsteden“ regelmäßig gekommen, um den Fortschritt des Wiederaufbaus Knechtstedens unter der Leitung des Baumeisters und Bruders Ansberi zu begutachten, den sie finanzierten. Weil jene Förderer gern Zeit dort vorbrachten, wo sie den Wiederaufbau unterstützten, und sich nach Feierabend gesellig austauschten, schien ein Gasthaus notwendig, wo auch die Vereinssitzungen stattfinden konnten. Die Knechtstedener Spiritaner wollten sich für die großzügige Unterstützung der Vereinsmitglieder erkenntlich zeigen und begannen deshalb den Bau eines Restaurants mit Herberge. Auch diente der Klosterhof als Unterkunft für die Verwandten der Patres und Brüder, insbesondere die weiblichen, die ihre Familienmitglieder nur einmal im Jahr in Knechtsteden besuchen durften. Übernachtungen und Besuche innerhalb des Klosters waren dabei untersagt, weshalb der Klosterhof als Gasthaus nötig war.
Weil Bruder Ansbert bereits aufgrund der anderen Restaurationen in Knechtsteden viel zu tun hatte, fragten die Spiritaner Bruder Aristobul Lülsdorf, der als Maurer gelernt hatte. Dieser stammte zwar aus Köln Langel, war aber in den Orden in Frankreich eingetreten und wirkte zu dieser Zeit in Paris und Portugal. Diese Rekrutierung aus dem Ausland war nicht unüblich, denn die Ordensleitung in Paris entsandte in der Anfangszeit Knechtstedens einige Brüder, um den Wiederaufbau zu unterstützen. Als der Bruder dann aus Portugal nach Knechtsteden gekommen war, konnte mit dem Bau begonnen werden. Geplant wurde der Klosterhof von dem Architekten Bruder Raffael. Dass der Bruder Aristobul Lülsdorf in Paris gelebt hat, wird durch den französischen Baustil deutlich, den man auch heute 
noch am Klosterhof bewundern kann.
1976 wurde die Gaststätte renoviert, da sich das Kloster an überregionaler Beliebtheit erfreute. Der Klosterhof dient bis heute als Herberge und beliebter Gasthof. Hier kehrten und kehren Touristen, Pilgernde, aber auch Patres und Schülerinnen und Schüler des Norbert-Gymnasiums gerne ein. Wir können Ihnen den Besuch des Klosterhofs nur wärmstens ans Herz legen. Treten Sie ein und bestellen Sie doch schon einmal, bevor wir uns verabschieden. Allen Bierliebhabern können wir das Knechtstedener Kellerbier empfehlen. Über den untenstehenden Button gelangen Sie zur Getränke- und Speisekarte, die auch Saisonales bietet. Kehren Sie aber zum Abschluss unbedingt zurück zur Klosterführer-App, sowie Sie bestellt haben!''',
    video: "assets/guidevideos/Kapitel_15.mp4",
    mapvideo: "assets/navvideos/Nav_15.mp4",
    next: 0,
  ),
];
