class StationInfo {
  final int position;
  final double xcoord;
  final double ycoord;
  final String name;
  final String iconImage;
  final String description;
  final String fulltext;
  final String video;
  final int next;

  final String zusatzvideo;
  final String zusatztext;

  StationInfo(
    this.position, {
    this.xcoord = 0,
    this.ycoord = 0,
    this.name = "",
    this.iconImage = "",
    this.description = "",
    this.fulltext = "",
    this.video = "",
    this.next = 0,
    this.zusatzvideo = "",
    this.zusatztext = "",
  });
}

List<StationInfo> stationen = [
  StationInfo(1,
      xcoord: 51.076410,
      ycoord: 6.754703,
      name: 'Torhaus',
      iconImage: 'assets/guideicons/torhaus.jpg',
      description:
          "Brudi! Das ist voll Krass und so. Vor allen dingen ist das mega alt und so. Kann man mega geil schauen premium Statue!",
      fulltext:
          '''Welch ein Anblick sich dem Besucher Knechtstedens bei seiner Ankunft offenbart! Das imposante Portal begrüßt ihn und weist ihm den Weg zum Gotteshaus, das schon aus der Ferne sichtbar ist und sich ihm in seiner vollen Pracht präsentiert. Dabei besuchten
          Pilgernde Knechtsteden bereits weit vor Errichtung dieses Torbogens, wie Sie ihn hier sehen.
          Einer alten Legende nach soll ein unbekannter Knecht aus dem nahegelegenen Dieplinghoven, dem heutigen Delhoven, noch vor der Klostergründung im Wald ein steinernes Muttergottesbild gefunden und mit nach Hause gebracht haben. Am folgenden Tag stand das Bild jedoch wieder an derselben Stelle im Wald. Als ihm dies noch einmal geschah, soll er am Fundort zu Ehren der Mutter Gottes eine Kapelle errichtet haben. Deshalb soll der Ort „Knechtstein“ oder „Knechtsteden“ genannt worden sein. Diese Geschichte bleibt allerdings nur eine Legende, denn Historiker leiten die Herkunft des Namens „Knechtsteden“ von dem Wort „Knechtstätte“ ab. Das steinerne Abbild der Muttergottes wurde außerdem nie gefunden. So oder so blickt Knechtsteden auf eine sehr lange Wallfahrtsgeschichte zurück. Der Ort gilt zwar nicht als der größte Marienwallfahrtsort des Rheinlandes, zählt aber wohl zu den ältesten. Pilgernde kamen seit jeher vor allem aus Köln, aber auch aus dem Jülicher Land, aus Neuss und Düsseldorf und sogar vom fernen Niederrhein.
          Nun aber zum Torbogen: 12Das vor Ihnen befindliche zweistöckige barocke Torhaus ersetzte 1723 den ehemaligen romanischen Torbogen am Eingang des Klosterbezirks und wurde unter Abt Arnold Brewer (1703-1728), dessen Wappen am Portal eingearbeitet ist, als Teil der Umbauten im frühen 18. Jahrhundert errichtet. In Folge dieser Umbauten wurden die meisten Gebäude im barocken Stil neu errichtet, so auch das Torhaus.
          Verziert ist der Torbogen mit drei Statuen, zwei an den Seiten und eine oben. 13Die obere zeigt die Gottesmutter Maria mit dem Jesuskind auf dem Arm. Sie grüßt die Pilgernden bei Ankunft in die ihr gewidmete Wallfahrtsstätte.
          Die zwei Figuren an den Seiten stehen in gewisser Weise für zwei Epochen Knechtstedens. 14Links ist der Heilige Norbert dargestellt. Norbert von Xanten lebte von 1080/85 bis 1134 und ist der Ordensgründer der Prämonstratenser, die sich 1130 in Knechtsteden niederließen und 1138 mit dem Bau der Basilika begannen. Der Heilige Norbert, über den Sie gleich gern mehr in der App hören und lesen können, steht also für die Gründung des Klosters und seines Ordens. Vor Ihnen hält er in seiner linken Hand die Monstranz mit gewandelter Hostie. Seinerzeit galt der Heilige Norbert als deklarierter Gegner Tanchelms, der von der Kirche als Häretiker und Ketzer verurteilt wurde, weil er die wirkliche Gegenwart Jesu Christi in der gewandelten Hostie leugnete. So ist das Attribut Norberts als ein Symbol für sein Vertrauen auf die Heilige Kommunion zu verstehen.
          Rechts zu sehen ist Franz Maria Paul Libermann, der Neugründer der Missionsgesellschaft vom Heiligen Geist, kurz: des Spiritaner-Ordens. Das ausgehende 18. und das 19. Jahrhundert waren für das Kloster schwere Zeiten. Mit der Übernahme der Klosteranlage durch die Spiritaner 1895 beherbergte Knechtsteden endlich wieder Geistliche, nachdem Französische Revolution und napoleonische Säkularisation der
          ehemaligen Abtei der Prämonstratenser 1802 den Garaus gemacht hatten. Mit der rechten Figur des Torbogens besinnen sich die Knechtstedener also auf den zweiten Orden, der in Knechtsteden ansässig wurde. Abgebildet ist er mit einem Kreuz in seiner Hand. Dies ist ein Verweis auf die Kongregation, die Libermann gegründet hat. Zur Erklärung: Eine Kongregation ist eine religiöse Vereinigung, die sich im Unterschied zu den älteren Ordensgemeinschaften, die hauptsächlich auf das innerklösterliche Leben ausgerichtet waren, vor allem Aufgaben außerhalb des Klosters widmet. Libermann verschrieb sich dabei der Missionierung in Afrika, auf die das Kreuz in seiner Hand hindeuten soll.
          An den nächsten Stationen erfahren Sie über die beiden Epochen Knechtstedens mehr. Beginnen Sie hierfür die Navigation zur nächsten Station.
          ''',
      video: "assets/guidevideos/yee.mp4",
      next: 1),
  StationInfo(2,
      name: 'Norbertpark',
      xcoord: 51.076585,
      ycoord: 6.753799,
      iconImage: 'assets/guideicons/norbertpark.png',
      description:
          "Brudi das ist viel krasser. Hier hat man Natur und so! Das ist mega geil für Luft weil weniger CO2.",
      fulltext:
          '''Wenden Sie Ihren Blick zunächst dem Norbertpark zu. Wurde die große weitläufige Grünfläche früher zur Viehhaltung genutzt, hat der Norbertpark heutzutage eine andere Funktion. Nicht selten findet gerade an warmen Sommertagen Unterricht des in Sichtweite befindlichen Norbert-Gymnasiums, zu dem wir später noch kommen, im Freien statt. Auch Veranstaltungen an der frischen Luft, etwa Gottesdienste oder zuletzt die Vergabe der Zeugnisse an die Abiturienten, erfreuen sich im Norbertpark besonderer Beliebtheit. Der Norbertpark fungiert als ein Ort, der zusammenführt. Seine Anziehungskraft bezieht er nicht zuletzt aufgrund des wunderschönen Ausblicks, den die Basilika offeriert.
      Bitte wenden Sie sich nun der Klosterbasilika zu und lassen Sie die Hecken hinter sich, sodass Sie einen freien Blick auf das Gotteshaus werfen können. Sie sehen das Monument einer bewegten Zeit des 12. Jahrhunderts. Die Klostergründung in Knechtsteden von 1130 geht nämlich zurück  auf die Schenkung des ererbten Herrensitzes des Domdekans zu Köln, Hugos von Sponheim, an die Prämonstratenser. Dieser wurde zu seiner Schenkung durch den Kölner Erzbischof Friedrich I. angeregt. 
      Der Prämonstratenser-Orden ist ursprünglich vom Heiligen Norbert von Xanten, einem Priester des Erzbistums Köln, 1121 im namensgebenden Prémontré in Nordfrankreich gegründet worden und aus einer Reformbewegung heraus entstanden, die sich dem Ideal des gemeinsamen Lebens im Stile der Urkirche verpflichtete.  Wenn Sie nach Abschluss dieses Abschnitts auf Ihrem Gerät herunterscrollen, haben Sie die Möglichkeit, mehr über das aufregende Leben des Heiligen Norbert und seine bewegte Zeit zu erfahren. Sie können die aktuelle Wiedergabe aber auch pausieren und bereits jetzt den Heiligen Norbert kennenlernen.
      Dass dem Kölner Erzbischof eine Klostergründung in Knechtsteden attraktiv erschien, ist vor dem Hintergrund der Organisation des Ordens zu erklären: Für das klösterliche Leben galten die Augustinusregeln. Die Prämonstratenser verschrieben sich jedoch nicht nur dem kontemplativen monastischen Leben im Kloster, sondern übernahmen auch außerklösterliche Funktionen. Als „halbe Mönche und halbe Pastöre“ ermöglichten sie besonders in abgelegenen Gegenden die Seelsorge, für die sich adelige Priester kaum interessierten.
      Mit der Schenkung des Fronhofs Knechtsteden durch Hugo von Sponheim an die Prämonstratenser wurde 1134 zunächst eine Magdalenenkapelle errichtet, die nicht mehr erhalten geblieben ist. Auch genauere Hintergründe der Errichtung bleiben unklar. Sicher ist, dass die Mönche die Gründungskapelle erbauen ließen, da sie Gottesdienste zelebrieren wollten. Offensichtlich war die Kapelle nach wenigen Jahren zu klein für den aufstrebenden Orden geworden.  Bereits 1138 begannen die Prämonstratenser dann mit dem Bau der Klosterkirche, die bis in die Gegenwart ein Wahrzeichen der Region darstellt. Übrigens: Den Grundstein für den Bau legte eine Frau namens Udalinde. Sie war vermutlich die Schwester oder Mutter des Schatzmeisters Christian an St. Andreas in Köln, mit dessen Mitteln der Bau der Basilika begonnen wurde. Jener trat unter dem ersten Knechtstedener Propst, Heribert, in den Orden der Prämonstratenser ein und gab nach dem Vorbild seines Herkunfts-Stifts der Basilika ihren Patron Andreas.  Der Sarkophag, den Sie, Ihren Blick leicht nach links auf den Boden wendend, erblicken, war womöglich der letzte Ruheort Udalindes. Sicher kann das Grab ihr zwar nicht zugeordnet werden, die Grabplatte aus Sandstein stammt jedoch erwiesenermaßen aus der Stauferzeit und stimmt somit mit der Leb- bzw. Todeszeit Udalindes überein.
      Das Äußere der Basilika ist durch die drei Türme und das grauweiße Steinbild charakterisiert, die das Gebäude deutlich vom umliegenden Wald abheben und es so zu einem Wahrzeichen der Region machen. Die Klosterkirche ist 60 Meter lang und 19 Meter breit. Das Querschiff misst eine Länge von 26 Metern.  Der Vierungsturm, unter dem sich das Langhaus und das Querschiff kreuzen, hat eine Höhe von 35 Metern. Gebaut wurde die Basilika aus rheinischem Sand- und Tuffstein. Einige Ecken sind hingegen aus dem stabileren Trachyt gefertigt worden. Diese und weitere bauliche Verschiedenheiten sind vor dem Hintergrund der unterschiedlichen Bauphasen zu erklären.
      Die Basilika Knechtsteden ist ein kunsthistorisch überaus besonderes Gotteshaus. Dies wird nicht zuletzt durch die Verschmelzung der rheinisch-traditionellen Romanik sowie der durch die Prämonstratenser aus Nordfrankreich importierten Gotik verstärkt. Die Klosterkirche beurkundet so den Einfluss rheinischer und nordfranzösischer Kultur in ihrer Region. Am deutlichsten erkennbar scheint die Vereinigung der beiden architektonischen Epochen bereits von Ihrer Perspektive aus. Sind der Vierungsturm und die gesamte Drei-Türme-Anlage das Werk rheinischer Romanik, verweisen die Fenster des Ostchors eindeutig auf die Gotik. Jene auffällige architektonische Unterschiedlichkeit ist vor dem Hintergrund einer Erneuerung im 15. Jahrhundert, nach erheblichen Schäden durch Plünderungen während der Neusser Fehde 1474, einer kriegerischen Auseinandersetzung zwischen dem Erzbischof Ruprecht von Köln, und den Landständen des Erzstifts, zu erklären. Doch auch der ursprüngliche Bau in seiner vorliegenden Form verweist auf jene Vereinigung von Romanik und Gotik. War die rheinische Romanik eher bestrebt, dem Beispiel profaner Repräsentativbauten nach großflächig in die Breite, in die Horizontalität zu bauen, möchte die Gotik den Blick zu Gott in die Höhe, in die Vertikalität lenken. Die Außenwände des Ostbaus sind gegliedert und mit Ornamenten versehen, wie sie in Nordfrankreich ihrerzeit üblich gewesen sind. Das Langhaus und die Turmanlagen hingegen sind in niederrheinischen Bauformen gestaltet. Baulich besonders interessant sind die beiden Seitentürme: Die unteren beiden Geschosse sind französisch geprägt, die oberen niederrheinisch. Der Hang zur nordfranzösischen Vertikalität wird dabei durch den Trachytstein betont. Die Waagerechte betont hingegen der Tuffstein aus der Südeifel. Bauhistoriker erkennen in diesem französischen Einfluss erste gotische Elemente rheinischer Baukunst und zählen die Basilika Knechtsteden deshalb zu den bedeutendsten Bauwerken des 12. Jahrhunderts.
      Gehen Sie nun links entlang der Basilika an der Grabplatte vorbei Richtung Durchlass in der Mauer. Bevor Sie die Mauer durchlaufen, an der die 14 Stationen des Kreuzweges in Form gusseiserner Reliefs angebracht sind,  blicken Sie rechts am Fuß der Basilika hinunter. Dort ist bewusst als letzte, 15. Station des Kreuzweges an der Ostseite der Basilika ebenfalls eine alte Grabplatte drapiert, um an die Auferstehung nach dem Tod zu erinnern. Wem jenes Sarkophagfragment jedoch gehört, ist ungewiss. Durchqueren Sie nun die Mauer hin auf die Südseite der Klosterkirche mit Blick auf das dreischiffige Langhaus. Achten Sie je nach Körpergröße auf Ihren Kopf, Personen über 1,85m stoßen sich hier gelegentlich.
      Vor Ihnen befindet sich das südliche Nebenschiff mit dem Hauptportal.  Jenes Portal ist nachträglich eingefügt worden, da der ursprüngliche Osteingang nach Anbau des Querschiffes nicht mehr zu nutzen gewesen ist. Schauen Sie genau hin: Das Hauptportal ist verziert mit viermal abgetreppten Gewänden. Die Basaltsäulen setzen sich in den Bögen als Rundstäbe fort. Den innersten Portalbogen ziert ein schöner Akanthusblattfries, der in der Ornamentik für Leben und Unsterblichkeit steht.  Betrachten Sie nun die Wand des vor Ihnen befindlichen südlichen Nebenschiffes. Sie zeigt eindeutig Bogenspuren eines früher verbauten Kreuzganges, der nach den verschiedenen Formen dieser Bögen mehrmalige Umbauten erfahren haben muss.
      Wenden Sie Ihren Blick nach rechts. In der Nische zum östlichen Querschiff ist ein Relief eingelassen. Es zeigt die Heilige Magdalena zu Füßen Jesu Christi in dem Moment, als sie ihn als Auferstandenen erkennt. Das Relief verweist auf die ehemalige Gründungskapelle, die 1134 errichtet worden war und aufgrund ihres schlechten Zustandes Mitte des 18. Jahrhunderts, genauer 1731, abgerissen wurde. Das Relief erinnert daher an die ersten Anfänge klösterlichen Lebens in Knechtsteden.
      Zusatz: Leben und Wirken des Heiligen Norbert von Xanten
      Norbert von Xanten ist geboren in eine bewegte Zeit des Machtkampfes zwischen Papst und Kaiser.  Der Investiturstreit prägte die jungen Jahre des Heiligen Norbert, der 1080 vermutlich in Gennep, in den heutigen Niederlanden, geboren wurde – vermutlich, da nicht sicher überliefert ist, ob Norbert bereits zur Welt gekommen war, als sein Vater, Graf Heribert von Gennep, Burgvogt von Xanten wurde. Die Familie wechselte also den Wohnsitz von Gennep nach Xanten. Seine ersten von Stand privilegierten Lebensjahre verbrachte Norbert in Xanten.
      Sein Vater erwirkt für Norbert, Stiftsherr am Viktorstift in Xanten zu werden. Es handelt sich sozusagen um ein perfektes Absprungbrett, um eine kirchliche Karriere einzuschlagen. So verbringt Norbert unter anderem viel Zeit zu Hofe des Erzbischofs von Köln und des deutschen Königs Heinrich V. und kommt in den Genuss des höfischen Lebens.  Norbert begleitet etwa 1110 den König nach Italien, der in Rom vom Papst zum deutschen Kaiser gekrönt werden will.
      Aufgrund der Anspannungen zwischen weltlicher und geistlicher Gewalt, weigert sich der Papst den salischen Heinrich V., Sohn Heinrichs IV., zum Kaiser zu krönen. Heinrich nahm den Papst Paschalis II. gefangen und verlangte neben seiner Kaiserwürde das Recht der Investitur, also das Recht, Bischöfe zu ernennen und abzusetzen. Norbert von Xanten muss diese Vorgänge sehr intensiv erlebt haben. 
      Heinrich warb um Norbert und bat ihm sogar das Bischofsamt an, das Norbert ablehnte. Wann Norbert einen inneren Wandel vollzog oder gar eine transzendentale Erfahrung machte, ist unklar.  Die Legende besagt, dass er im Jahre 1115 auf dem Ausritt nach Vreden in ein Unwetter geriet. Vor ihm soll ein Blitz eingeschlagen sein, sodass Norbert samt Pferd zu Boden stürzte und aufgrund des knapp entkommenen Todes sein Leben hinterfragte. Für ihn stand fest: Es brauchte Erneuerung in ihm und in der Kirche. Um Vorbilder zu finden, ging er auf Wanderschaft. Auf seinen Wanderungen beherbergten ihn verschiedene Klöster. Norbert lernte die Klosterregeln, die Gemeinschaft und nicht zuletzt das asketische Leben kennen. Er ließ sich zum Diakon und daraufhin zum Priester weihen.
      Zurück in Xanten, versuchte er die Stiftsherren zu Viktor von dem Wandel im Sinne des Urchristentums zu überzeugen, den er in der Kirche anstrebte. Seine modische Seidenkleidung legte Norbert ab, verschenkte seinen Besitz und beschaffte sich eine raue Kutte, um mit gutem Beispiel voranzugehen. Norbert erntete dennoch lediglich Spott.
      Unverrichteter Dinge verließ Norbert sodann Xanten wieder und erkannte, dass Reform und Wandel nicht mit Weltfremdheit und Rückzug zu erreichen sind, sondern geistlichen Handelns bedarf. Norbert von Xanten wurde Wanderprediger. 1118 begab er sich in seine niederländische Heimat und predigte auf Wanderschaft bis nach Belgien.
      Norbert zeichnete sich als Prediger aus. Er begeisterte. Er ermunterte zu Demut und Bescheidenheit und prangerte Streit, Missgunst sowie Geiz und Habgier an. Dabei kam auch Kritik gegen Kirche und Fürsten nicht zu kurz. Jene Kirche hörte selbstredend nicht gern von einem Kritik übenden Wanderprediger, sodass Norbert in das Visier geriet und 1118 angeklagt wurde.  Auf der Synode, die über Norberts Schicksal verhandeln sollte, rechtfertigte er sich erfolgreich und erlangte sogar im Nachgang die Predigtvollmacht des Papstes in Nordfrankreich.
      So versuchte die Kirche, Norbert und seine unangenehme Beliebtheit in der einfachen Bevölkerung für sich zu nutzen.  Man ließ ihn gewähren und erlaubte ihm 1120 die Gründung eines eigenen Klosters im Tal von Prémontré bei Laon in Frankreich. Der Prämonstratenserorden, dessen Namensherkunft unschwer erkennbar vom Namen des Gründungsortes rührt, wurde gegründet. Das weiße Bußgewand aus ungebleichter Schafswolle wurde zur Ordenskleidung. In erstaunlicher Schnelle verbreitete sich der Orden der Prämonstratenser und gewann begeisterte Mitglieder für sich – ob Mann, ob Frau. Klöster wurden schnell auch in Belgien, Frankreich und Deutschland gegründet.  Das erste deutschsprachige Kloster der Prämonstratenser wurde 1122 in Cappenberg bei Dortmund errichtet. Der Graf von Cappenberg hatte nach einer persönlichen Begegnung mit Norbert von Xanten zuvor seinen gesamten Besitz übergeben und sich dem Orden angeschlossen. Ende des 12. Jahrhunderts zählten die sogenannten „Weißen Mönche“ 500 Niederlassungen.
      1126 begab sich Norbert nach Rom, um die offizielle Anerkennung seines Ordens zu erwirken. Die Verbindung asketischer Zurückgezogenheit mit der praktischen Seelsorge beeindruckte Papst Honorius II.. Die Ordensregel, die auf der Augustinusregel fußt, wurde vom Papst bestätigt. Auf seiner Rückreise wurde Norbert sogar in Würzburg festgehalten, um zu bleiben – Norbert ist ein Superstar. Im Sommer berief der Reichstag ihn schließlich zum Bischof von Magdeburg. Norbert wurde gedrängt, die Wahl anzunehmen. Er gab nach, seine Anhänger blieben enttäuscht zurück und fühlten sich im Stich gelassen. 
      Mit der Annahme der Verantwortung wollte Norbert seinen Einfluss zur Reform nutzen. Barfuß und im Büßerhemd ritt er in die Stadt Magdeburg ein. Laut Legende soll ihm zunächst sogar der Einlass in den Bischofspalast verweigert worden sein. Das Volk jubelte ihm zu. Die Reformen, die Norbert aber anstrebte, waren gerade für die alten kirchlichen Eliten des Bistums Magdeburg unangenehm. Der neue Bischof kontrollierte Rechnungen und beendete Geldverschwendungen. Ein missglückter Mordanschlag ist auf ihn verübt worden.
      Während seines Pontifikats nahm sich Norbert von Xanten unterschiedlicher Aufgaben an. Er trieb die Missionierung der Slawen im Osten an, als Erzkanzler begleitete er 1132 sogar König Lothar nach Italien auf dessen Romzug. 1134 kehrte er, vermutlich an Malaria erkrankt, zurück und verstarb am 6. Juni. 1582 sprach ihn Gregor XIII. heilig. 
      Der Heilige Norbert von Xanten war Zeuge einer bewegten Zeit. So wie auch sein Zeitgenosse, Bernhard von Clairvaux, Gründer des Reformordens der Zisterzienser. Beide Ordensgemeinschaften – Prämonstratenser und Zisterzienser – fanden von Frankreich aus eine erstaunlich schnelle Verbreitung. Ohne den Lebenswandel Norberts, seinen Entschluss der inneren und äußeren Reform, aber auch ohne sein Verantwortungsbewusstsein, doch das Bistum Magdeburg zu übernehmen, wäre dies wohl nicht möglich gewesen.
      ''',
      video: "assets/guidevideos/yeewars.mp4",
      zusatztext:
          '''Norbert von Xanten ist geboren in eine bewegte Zeit des Machtkampfes zwischen Papst und Kaiser.  Der Investiturstreit prägte die jungen Jahre des Heiligen Norbert, der 1080 vermutlich in Gennep, in den heutigen Niederlanden, geboren wurde – vermutlich, da nicht sicher überliefert ist, ob Norbert bereits zur Welt gekommen war, als sein Vater, Graf Heribert von Gennep, Burgvogt von Xanten wurde. Die Familie wechselte also den Wohnsitz von Gennep nach Xanten. Seine ersten von Stand privilegierten Lebensjahre verbrachte Norbert in Xanten.
            Sein Vater erwirkt für Norbert, Stiftsherr am Viktorstift in Xanten zu werden. Es handelt sich sozusagen um ein perfektes Absprungbrett, um eine kirchliche Karriere einzuschlagen. So verbringt Norbert unter anderem viel Zeit zu Hofe des Erzbischofs von Köln und des deutschen Königs Heinrich V. und kommt in den Genuss des höfischen Lebens.  Norbert begleitet etwa 1110 den König nach Italien, der in Rom vom Papst zum deutschen Kaiser gekrönt werden will.
            Aufgrund der Anspannungen zwischen weltlicher und geistlicher Gewalt, weigert sich der Papst den salischen Heinrich V., Sohn Heinrichs IV., zum Kaiser zu krönen. Heinrich nahm den Papst Paschalis II. gefangen und verlangte neben seiner Kaiserwürde das Recht der Investitur, also das Recht, Bischöfe zu ernennen und abzusetzen. Norbert von Xanten muss diese Vorgänge sehr intensiv erlebt haben. 
            Heinrich warb um Norbert und bat ihm sogar das Bischofsamt an, das Norbert ablehnte. Wann Norbert einen inneren Wandel vollzog oder gar eine transzendentale Erfahrung machte, ist unklar.  Die Legende besagt, dass er im Jahre 1115 auf dem Ausritt nach Vreden in ein Unwetter geriet. Vor ihm soll ein Blitz eingeschlagen sein, sodass Norbert samt Pferd zu Boden stürzte und aufgrund des knapp entkommenen Todes sein Leben hinterfragte. Für ihn stand fest: Es brauchte Erneuerung in ihm und in der Kirche. Um Vorbilder zu finden, ging er auf Wanderschaft. Auf seinen Wanderungen beherbergten ihn verschiedene Klöster. Norbert lernte die Klosterregeln, die Gemeinschaft und nicht zuletzt das asketische Leben kennen. Er ließ sich zum Diakon und daraufhin zum Priester weihen.
            Zurück in Xanten, versuchte er die Stiftsherren zu Viktor von dem Wandel im Sinne des Urchristentums zu überzeugen, den er in der Kirche anstrebte. Seine modische Seidenkleidung legte Norbert ab, verschenkte seinen Besitz und beschaffte sich eine raue Kutte, um mit gutem Beispiel voranzugehen. Norbert erntete dennoch lediglich Spott.
            Unverrichteter Dinge verließ Norbert sodann Xanten wieder und erkannte, dass Reform und Wandel nicht mit Weltfremdheit und Rückzug zu erreichen sind, sondern geistlichen Handelns bedarf. Norbert von Xanten wurde Wanderprediger. 1118 begab er sich in seine niederländische Heimat und predigte auf Wanderschaft bis nach Belgien.
            Norbert zeichnete sich als Prediger aus. Er begeisterte. Er ermunterte zu Demut und Bescheidenheit und prangerte Streit, Missgunst sowie Geiz und Habgier an. Dabei kam auch Kritik gegen Kirche und Fürsten nicht zu kurz. Jene Kirche hörte selbstredend nicht gern von einem Kritik übenden Wanderprediger, sodass Norbert in das Visier geriet und 1118 angeklagt wurde.  Auf der Synode, die über Norberts Schicksal verhandeln sollte, rechtfertigte er sich erfolgreich und erlangte sogar im Nachgang die Predigtvollmacht des Papstes in Nordfrankreich.
            So versuchte die Kirche, Norbert und seine unangenehme Beliebtheit in der einfachen Bevölkerung für sich zu nutzen.  Man ließ ihn gewähren und erlaubte ihm 1120 die Gründung eines eigenen Klosters im Tal von Prémontré bei Laon in Frankreich. Der Prämonstratenserorden, dessen Namensherkunft unschwer erkennbar vom Namen des Gründungsortes rührt, wurde gegründet. Das weiße Bußgewand aus ungebleichter Schafswolle wurde zur Ordenskleidung. In erstaunlicher Schnelle verbreitete sich der Orden der Prämonstratenser und gewann begeisterte Mitglieder für sich – ob Mann, ob Frau. Klöster wurden schnell auch in Belgien, Frankreich und Deutschland gegründet.  Das erste deutschsprachige Kloster der Prämonstratenser wurde 1122 in Cappenberg bei Dortmund errichtet. Der Graf von Cappenberg hatte nach einer persönlichen Begegnung mit Norbert von Xanten zuvor seinen gesamten Besitz übergeben und sich dem Orden angeschlossen. Ende des 12. Jahrhunderts zählten die sogenannten „Weißen Mönche“ 500 Niederlassungen.
            1126 begab sich Norbert nach Rom, um die offizielle Anerkennung seines Ordens zu erwirken. Die Verbindung asketischer Zurückgezogenheit mit der praktischen Seelsorge beeindruckte Papst Honorius II.. Die Ordensregel, die auf der Augustinusregel fußt, wurde vom Papst bestätigt. Auf seiner Rückreise wurde Norbert sogar in Würzburg festgehalten, um zu bleiben – Norbert ist ein Superstar. Im Sommer berief der Reichstag ihn schließlich zum Bischof von Magdeburg. Norbert wurde gedrängt, die Wahl anzunehmen. Er gab nach, seine Anhänger blieben enttäuscht zurück und fühlten sich im Stich gelassen. 
            Mit der Annahme der Verantwortung wollte Norbert seinen Einfluss zur Reform nutzen. Barfuß und im Büßerhemd ritt er in die Stadt Magdeburg ein. Laut Legende soll ihm zunächst sogar der Einlass in den Bischofspalast verweigert worden sein. Das Volk jubelte ihm zu. Die Reformen, die Norbert aber anstrebte, waren gerade für die alten kirchlichen Eliten des Bistums Magdeburg unangenehm. Der neue Bischof kontrollierte Rechnungen und beendete Geldverschwendungen. Ein missglückter Mordanschlag ist auf ihn verübt worden.
            Während seines Pontifikats nahm sich Norbert von Xanten unterschiedlicher Aufgaben an. Er trieb die Missionierung der Slawen im Osten an, als Erzkanzler begleitete er 1132 sogar König Lothar nach Italien auf dessen Romzug. 1134 kehrte er, vermutlich an Malaria erkrankt, zurück und verstarb am 6. Juni. 1582 sprach ihn Gregor XIII. heilig. 
            Der Heilige Norbert von Xanten war Zeuge einer bewegten Zeit. So wie auch sein Zeitgenosse, Bernhard von Clairvaux, Gründer des Reformordens der Zisterzienser. Beide Ordensgemeinschaften – Prämonstratenser und Zisterzienser – fanden von Frankreich aus eine erstaunlich schnelle Verbreitung. Ohne den Lebenswandel Norberts, seinen Entschluss der inneren und äußeren Reform, aber auch ohne sein Verantwortungsbewusstsein, doch das Bistum Magdeburg zu übernehmen, wäre dies wohl nicht möglich gewesen.
            ''',
      zusatzvideo: "assets/guidevideos/yeebusters.mp4",
      next: 2),
  StationInfo(3,
      xcoord: 51.07669594480124,
      ycoord: 6.752454033913944,
      name: 'Basilika',
      iconImage: 'assets/guideicons/basilika.png',
      description:
          "Alter! Das ist einfach Endgame. Vor allem ist die so groß. Deswegen haben die voll viel Weihrauch. Ich sag dir. Weihrauch bestes.",
      fulltext:
          '''Sie haben die Kirche nun von ihrer Westseite betreten. Halten Sie sich gleich beim Eintritt links, sodass Sie an der Westapsis stehend Halt machen. Lassen Sie das Innere der Klosterbasilika gern eine Weile auf sich wirken, bevor Sie sich dem großen Wandgemälde der Westapsis widmen. 
        Welch ein imposantes Fresko die Westapsis doch schmückt! Bei dem Kunstwerk handelt es sich um eines der ältesten Fresken des Rheinlandes. Da es vermutlich wenig später nach Errichtung des Langhauses im Jahr 1160 angefertigt wurde, ist es sogar das älteste des Niederrheins sowie das größte zwischen Rhein und Maas. Es ist kaum zu glauben, mit welchem Glücksfall sein Erhalt verbunden ist. Schließlich hat es gerade, weil es als unschön betrachtet wurde, überlebt. Im 17. Jahrhundert, als es dem Kloster in seiner Blütezeit finanziell gut ging, wurde Knechtsteden weitgehend barockisiert. Die romanische Kunst und das sehr auffällige Fresko wurden als nicht zeitgemäß betrachtet. In der Folge übertünchte man das Fresko mit einer weißen Kalkschicht.  Als die Basilika 1869 einem Brand zum Opfer fiel, blieb das Fresko aufgrund jener schützenden Kalkschicht erstaunlich gut erhalten. In der Folge des Wiederaufbaus und der Erneuerungen von 1882 trat das Fresko wieder zutage – eine Sensation.
        Durch das Fresko wird die alte Bedeutung der Apsis als Bogen und Tor zum Himmel sichtbar. Es zeigt den Heiland mit dem Buch des Lebens in seiner Linken vor dem gestirnten Himmel. Mit seiner Rechten segnet er. Das Buch des Lebens ist in der christlich-jüdischen Tradition eine Art des göttlichen Verzeichnisses aller ihm gefälligen Menschen. Christus ist von der sogenannten Mandorla umgeben, einer leuchtenden Aura. Er sitzt auf dem Sphärenbogen, seine Füße ruhen auf dem Bogen des Erdkreises. Die Mandorla umgeben und tragen die vier Wesen der Geheimen Offenbarung Johannes‘. Sie sind Symbole der vier Evangelisten: Der Mensch bzw. Engel oben links steht für Matthäus, der Adler rechts für Johannes. Der geflügelte Löwe unten links verkörpert Markus, während Lukas durch den Stier symbolisiert wird. Die Spruchbänder, die die vier Wesen halten, zeigen die ersten Worte der jeweiligen Evangelien. Links und rechts umschließen die Szenerie Petrus und Paulus. Inschriften bezeichnen Petrus als „princeps apostolorum“, den Ersten der Apostel, Paulus als „doctor gentium“, den Lehrer der Völker.  Unter dem Ornamentband, das die raum- wie zeitlose, jenseitige Seinsebene von dem Diesseits trennt, sind die übrigen Apostel abgebildet. Mit dem Buch der Frohbotschaft in der Hand werden alle Apostel durch Christus entsandt, um das Evangelium zu verkünden. Das phantasievolle, ordnende Ornamentband zeigt außerdem ein Schriftband: „Majestas atque figura Christi signatur per quem mundus reparatur.“ Zu Deutsch: Größe und Gestalt Christi werden bezeichnet, durch ihn wird die Welt erneuert.
        Der Künstler dieses Werks scheint weit herumgekommen zu sein, denn für das Rheinland im 12. Jahrhundert ist die Darstellung der Apostel unüblich, gar innovativ. Sie stehen nicht jeder für sich getrennt, sondern bilden eine Einheit. Sie befinden sich im Gespräch oder legen ihre Hand auf die Schulter des Nebenmannes. Nicht nur die Körperhaltung verbindet die Apostel, auch die übereinander gemalten Füße verweisen auf die Einheit der Jünger Jesu.
        Womöglich ist es Ihnen aufgefallen: Eine Figur ist ausgelassen worden. Zu Füßen Christi liegt ein betender, weißgewandeter Mönch. Bei diesem handelt es sich um den Stifter des zweiten Bauabschnitts, Albert von Aachen. Ist bislang vom Baustifter Christian und seiner Frau Udalinde die Rede gewesen, so prägte Christian lediglich den ersten Bauabschnitt. Er errichtete zeit seines Lebens den Ostchor, den Altarraum und das Querhaus samt Gewölben und Dächern. Nachdem er allerdings 1151 verstarb, waren die Arbeiten nicht fertiggestellt. Albertus Aquensis, Albert von Aachen, „vollendete die von Christian begonnene Kirche, zog beide Seiten hoch, errichtete drei Türme mit Giebeln und Dächern, ließ Glocken gießen und tat alles zur prächtigen Ausstattung des Baus.“ So heißt es in den historischen Quellen. Albert war zu jener Zeit von 1152 bis 1155 Domdechant in Köln, von 1155 bis 1158 außerdem Propst des Münsters in Aachen. Er entstammt außerdem dem Geschlecht der Sponheimer und tritt so in die familiäre Tradition der Stiftung. Zweifellos machte sich Albert verdient. 1155 erwirkte er mithilfe der guten Beziehungen zum Kölner Erzbischof die volle Anerkennung der Besitztümer und den kaiserlichen Schutz bei Kaiser Friedrich I. Barbarossa. Es folgt sogleich die Anerkennung des Papstes. Albert von Aachen erwies sich als bedeutsame Figur in die Blütezeit Knechtstedens bis in das 13. Jahrhundert hinein. Nicht zuletzt wird Knechtsteden spätestens 1185 durch den Generalabt in Prémontré zur Abtei erhoben. Die schillernde Figur Alberts von Aachen ließ sich daher als Stifter zu Diensten Christi abbilden. Seine letzte Ruhestätte, die Sie gleich bestaunen können, wurde 1962 hinter dem Hauptaltar im Zuge von Fußbodenarbeiten wiederentdeckt.
        Übrigens: Der Taufstein, der vor Ihnen steht, ist in etwa so alt wie die Kirche selbst. Er stammt aus dem 12. Jahrhundert. So können die Taufrechte der Kirche ebenfalls in das 12. Jahrhundert datiert werden. Geschmückt ist der aus Basalt geschlagene Taufstein mit doppeltem Zinnenfries. Sein Sockel hingegen entstand deutlich später.
        Widmen wir uns den weiteren Schätzen der Knechtstedener Basilika. Wenden Sie sich hierfür Richtung Altar von der Westapsis ab und richten Sie den Blick nach oben. Sicher ist Ihnen bereits aufgefallen, dass die Decke in vier quadratische Joche unterteilt ist. Jene Räume des Langhauses sind mit Rundwülsten auf Gurtbögen, die optisch an den Pfeilern bis zur Erde verlängert sind, markant voneinander getrennt. Dem Besucher scheint es fast so, als schreite er von Raum zu Raum. Die vier Joche sind überwölbt mit Kreuzgratgewölben. In den Räumen im Ostteil sind hingegen französische Bauideen zum Tragen gekommen. Sie sind mit Kuppeln überwölbt. Im gesamten niederrheinischen Raum gibt es kein Bauwerk aus dieser Zeit mit so vollendeten und zahlreichen Kuppeln. Nicht zuletzt deswegen ließen sich Baumeister im gesamten Rheinland von der Knechtstedener Basilika und ihren Kuppeln bei folgenden Kirchenbauten inspirieren.
        Auch der Wechsel von Pfeilern und Säulen lädt den Besucher dazu ein, das Langhaus andachtsvoll zu durchschreiten. Dieser für das Rheinland typische Stützenwechsel wurde in Knechtsteden mit besonderer Kunst versehen. Um den vor Ihnen liegenden Stifts-Chor im Osten vom Pfarr-Chor im Westen hinter Ihnen abzuheben, verändern sich die Säulen in ihrer Form vom quadratischen Grundriss hin zu den Dreibündelsäulen, die einen Eingang zum Stifts-Chor markieren sollen. In seiner Art ist der Knechtstedener Stützenwechsel also ein einmaliger, schöpferisch gelungener Versuch, dem westlichen und östlichen Mittelschiff-Joch einen eigenen Charakter zu geben.
        Der Besucher der Knechtstedener Basilika erfreut sich feierlicher Ruhe und schlichter Erhabenheit, die der Raum ausstrahlt. Dies wird auch an dem sparsamen Schmuck liegen, den die Kirche, von dem Westapsis-Fresko abgesehen, bietet. Treten Sie gern einige Schritte Richtung Altarraum vor, bis Sie zur Höhe des Hauptportals gelangen. Wenden Sie sich noch einmal genauer den Säulen zu.  Der Schmuck der Basilika beschränkt sich nämlich auf die vielfältigen und stilbildenden Kapitelle und Basen der Pfeiler und Säulen. Die gesamte zeitgenössische Schöpferkraft niederrheinischer Steinmetze manifestiert sich in ihnen. Die Kapitelle weisen eine Würfelform auf. Blätter und Ranken wurden üblicherweise als Schmuck in jene Würfel hineingemeißelt – nicht so in Knechtsteden:  Es scheint so, als wären die Ornamente auf den Würfel gelegt, ja, nahezu plastisch hinzugegeben worden. Dies ist ein Nachweis besonders hoher Steinmetzkunst, die mit Sicherheit unterstützt worden ist durch französische und südländische Steinmetze. So wird die Verschmelzung französischer und niederrheinischer Romanik, die bereits von außen sichtbar wird, auch im Inneren deutlich. 
        Gehen Sie ein paar Schritte weiter bis zur letzten Säule vor dem Ostteil.  An der rechten Säule thront das Gnadenbild. Die schmerzhafte Mutter Gottes hält ihren toten Sohn Jesus Christus in ihren Händen. Dass Knechtsteden einer der ältesten Marienwallfahrtsorte ist, ist bereits einleitend erwähnt worden. Dieses Bild ist eine aus Lindenholz geschnitzte Pietà aus dem 14. Jahrhundert.  Der Leib Jesu scheint auffallend klein, sein Gesicht ausdrucksstark und gezeichnet. Maria schaut mit ihrem breiten, bäuerlichen Gesicht über ihren toten Sohn hinweg. Die Gesichtszüge sind zwar geprägt von Schmerz und Leid, doch sprechen sie auch von Ahnung von Erlösung. Der Kaisermantel, den Maria trägt, passt nicht zu ihrem wenig höfischen Gesicht. Diese Darstellung ist jedoch üblich bei den Prämonstratensern.
        Bis heute zieht das einen Meter große Bild Pilgernde an. Es überlebte alles Unglück, das Knechtsteden in den Jahrhunderten nach seiner Entstehung heimsuchen sollte. Die Neusser Fehde von 1474 fügte dem Kloster und der Kirche wie bereits erwähnt großen Schaden zu. Neben den Plünderungen und Zerstörungen blieb die Knechtstedener Pietà aber erhalten. Auch die Schrecken des Dreißigjährigen Krieges von 1618 bis 1648 und die Pestzeit in Knechtsteden 1637 überlebte das Gnadenbild. Gerade im 17. Jahrhundert zu Pestzeiten spendete es Betern und Pilgernden Trost. Schließlich pilgerten etwa viele Mütter gefallener Söhne oder dahinsiechender Pestkranker nach Knechtsteden. Als „Not Gottes“ bezeichneten jene Betende die Knechtstedener Pietà, da Gottes Sohn die Not aller Menschen auf sich genommen hat. Der Betende legt seine Nöte im Gebet also ebenfalls Maria in den Schoß.
        Waren das 12. und einleitende 13. Jahrhundert noch aufstrebende Zeiten des jungen Klosters, folgten auf sie dunklere. Die wenigen Quellen berichten von finanziellen Problemen durch Misswirtschaft und Verschwendung der Äbte. Auch Kriegswirren, etwa die Schlacht von Worringen 1288, in denen das Kloster Abgaben zu leisten hatte, schädigten die finanzielle Lage Knechtstedens erheblich. Hinzu kommt, dass die Kleriker zunehmend ihre klösterlichen Regeln missachteten und ungehorsam wurden. Papst Alexander IV. rügte sie in einem Schreiben vom 11. März 1256. Schenkungen aufgrund besonders frommen Lebens wurden somit seltener.
        Die Neusser Fehde 1474 war für das Kloster eine Katastrophe, auf die jedoch eine Zeit der Blüte folgte. Abt Ludger führte die geflüchteten Prämonstratenser zurück nach Knechtsteden und ließ die Schäden beseitigen sowie die Erneuerung einleiten.  Auch der Altarraum, der Ostchor, ist im gotischen Stil neuerrichtet worden. Wenn Sie hinüber zum Altar blicken, erkennen Sie, dass der Altarraum ab der Fensterunterkante erneuert wurde. Die gotischen Fenster fügen sich in den Raum, mystifizieren ihn und lassen den Besucher den Blick gen Himmel heben. Offensichtlich führten die Zeiten höchster Not zur Besinnung. Schließlich regte Abt Ludger auch die Erneuerung geistlichen Lebens an. 1502 scheint sich auch die wirtschaftliche Lage stabilisiert zu haben, da mit dem Bau des neuen Refektoriums, eines Speisesaals, begonnen wurde. Die geistliche Standhaftigkeit und Treue gegenüber dem „alten Glauben“ bewiesen die Prämonstratenser aus Knechtsteden auch während der Reformation und bildeten eine Stütze für die Gegenreformation. 1570 entsandte Abt Gerhard etwa einige Kanoniker nach Magdeburg, um die alte Ordnung im dortigen Prämonstratenserstift wiederherzustellen. Kriegerische Auseinandersetzungen im Glaubenskampf zwischen Protestantismus und Katholizismus schadeten dem Kloster jedoch erheblich. So etwa im Kölner Krieg von 1583 bis 1588, als der Kölner Erzbischof zum Protestantismus übertrat. Knechtsteden hatte mit 25.000 Reichstalern die Gegenreformation zu versorgen.
        Im darauffolgenden 17. und 18 Jahrhundert erfuhr Knechtsteden noch ein letztes Mal unter den Prämonstratensern eine Blüte. So wurde das Kloster stetig weiter ausgeschmückt und barockisiert. Von dem barocken Schmuck ist hier in der Basilika wahrlich nichts übriggeblieben, da die französischen Truppen unter Napoleon plünderten, was getragen werden konnte. Nichtsdestotrotz sind einige barocke Elemente geblieben. Schon der erste Eindruck Knechtstedens am Torhaus ist ein Zeugnis des 18. Jahrhunderts. Im Kloster selbst wurde im 17. Jahrhundert die räumige Sakristei errichtet. Im Zuge der Erneuerung der Dächer wurde das gesamte Gebäude noch einmal erhöht. Auch wurde die heutige Hauskapelle zwischen 1678 und 1698 auf der Nordseite des Querschiffs erbaut. Schauen Sie gleich gern einmal hinein. Begeben Sie sich aber zunächst an der Pietà vorbei zum südlichen Nebenschiff.  Ins Auge fällt sofort die Grabplatte, die in der Wand eingelassen ist. Über der Grabplatte schmücken Heilige die Fenster des Nebenschiffs.  Die Grabplatte gehört dem Abt Petrus Teveren, der sich, ähnlich wie sein Onkel Leonhard Teveren, als Abt in Knechtsteden durch Reformbereitschaft und wirtschaftliche Stabilisierung verdient gemacht hat. Im Folgenden werden wir immer wieder auf Wappen von Äbten stoßen, die sich haben verewigen lassen. Gerade zur Zeit des Barocks regierten die Äbte wie kleine Kirchenfürsten. Die Wirkung nach außen und der Prunk, der den Herrschenden ehren soll, stehen dabei im Zentrum barocker Kunst.
        Gehen Sie nun hinüber zum Altarraum. Hier erinnert die im Boden eingelassene Gedenktafel an den letzten Ruheort Alberts von Aachen. Verweilen Sie hier entweder kurz zu seinem Gedenken oder gehen Sie weiter zur Sakramentskapelle.
        Beachten Sie vor Eintritt in die Kapelle die Gewölbekonsole im nördlichen Querhaus. Dem aufmerksamen Beobachter wird der dargestellte Kopf, der an Kaiser Friedrich I. erinnert, nicht entgehen. Die Konsole stammt wohl aus der Stauferzeit und fällt in die Bauphase unter Albert von Aachen – dies macht auch Sinn. Das Idealbild des Kaisers mit Krone sollte wohl auf den Schutz und die Anerkennung des Kaisers aufmerksam machen.  Treten Sie nun kurz in die Sakramentskapelle ein. Den barocken Raum aus dem 17. Jahrhundert ziert ein Sterngratgewölbe. Die 18 Kapitelle und Konsolen markieren den Beginn der himmlischen Zone. Darüber hinaus ist die Kapelle allerdings einfach gehalten. Vermutlich wird der Schmuck, wie oben bereits erwähnt, durch die Plünderungen der Franzosen unter Napoleon entwendet worden sein. 
        Mit der Invasion Napoleons und dem Vordringen der Franzosen in das Rheinland endet wenig später auch die Geschichte der Prämonstratenser in Knechtsteden, die das Kloster unter ihrem letzten Abt Hendel am 04. Oktober 1794 fluchtartig verlassen mussten. Zwar kehrten die ehemaligen Bewohner nach etwa neun Monaten zurück, fanden allerdings eine geplünderte, verwüstete und heruntergekommene Klosteranlage wieder. 1802 folgte dann die Säkularisation durch Napoleon – die Abtei Knechtsteden teilte ihr Schicksal mit 17 anderen Klöstern des Rhein-Kreises Neuss und wurde aufgehoben. Einer der ehemaligen Mönche des Prämonstratenserstifts, der von vermögendem Hause stammende Winand Kayser, pachtete seine eigene Abtei und rettete sie so vor ihrem endgültigen Untergang. 1810 sollte das Kloster aber versteigert werden. Kayser ersteigerte es über die befreundete Industriellenfamilie Herbertz aus Uerdingen und richtete die Basilika und die Gebäude wieder her. Mit seinem Tod 1842 verließ ein Helfer für Notleidende diese Welt.  Kayser wurde auf dem Melatenfriedhof in Köln beerdigt. Nach seinem Tod wechselten die Besitzer des Klosters mehrfach. 1867 kaufte dann die Armenverwaltung Kölns das Kloster mitsamt Besitz. Geplant war die Errichtung einer Heilanstalt für etwa 400 psychisch Kranke.  Der verheerende Brand von 1869 machte dem Plan aber einen Strich durch die Rechnung. Wer nicht an Zufälle glaubt, will wohl eher dem Gerücht Glauben schenken, Straberger Unbekannte hätten den Brand absichtlich gelegt, um die Heilanstalt zu verhindern. Anton Scheben, der Großneffe des „letzten Mönches“, wie Winand Kayser genannt wurde, wollte das Werk seines Großonkels retten. Beim Kaiser Wilhelm I. machte er sich für Knechtsteden und dessen Erhalt stark, wurde zu diesem Zweck mit 5.000 Talern bezuschusst und gründete einen „Bau- und Reparaturverein“. Ein weiterer Verein wurde in Neuss gegründet. Knechtsteden sollte bereits 1881 nach den alten Plänen erneuert werden. Die Prämonstratenser aber blieben nach fast 80 Jahren der Aufhebung des Klosters fern.
        Verlassen Sie die Kapelle nun wieder und folgen Sie rechts dem nördlichen Nebenschiff Richtung Westapsis.  Beachten Sie das zweite Fenster von rechts im Nebenschiff. Es zeigt eine Figur, die Ihnen bereits zu Beginn der Führung bekannt geworden ist – Franz Maria Paul Libermann, der Gründer der Kongregation vom unbefleckten Herzen Mariens, die in der Vereinigung mit der Missionsgesellschaft vom Heiligen Geist 1845 zum Orden der Spiritaner wurde. Hören Sie sich unten gern die zusätzlichen Informationen zur Gründung des Spiritanerordens an. Pausieren Sie entweder die aktuelle Wiedergabe oder hören Sie sie bis zum Schluss, bevor Sie die historischen Hintergründe der Spiritaner zur Kenntnis nehmen. Die Spiritaner kennzeichnen jedenfalls die zweite Epoche Knechtstedens, deren Spuren in den kommenden Stationen deutlich zum Tragen kommen.
        War bisher vor allen Dingen Sichtbares Gegenstand unserer Führung durch die Basilika, widmen wir uns nun auch der unsichtbaren Kunst des Klangs.  Gehen Sie ein Stück weiter bis zur Orgel. Sie steht erst seit 2009 in der Basilika. Ursprünglich stammt dieses um 1850 von William Holt in Leeds erbaute Musikinstrument aus einer Methodistenkirche in Tockwith, einem Dorf 20 Kilometer westlich von der historischen englischen Großstadt und Kirchenmetropole York. Nach der Schließung der dortigen Kirche wurde die Orgel restauriert und gelangte nach Knechtsteden. Die Orgel verfügt über 15 klingende Register, verteilt auf zwei Manuale und Pedal.
        - Ein weiterer klingender Schatz der Basilika ist das Geläut – mit etwas Glück werden Sie es zum Beispiel gegen Mittag bereits gehört haben. Das erste Fünf-Geläute wurde unter Prämonstratenser-Abt Leonhard Jansen, der auch den Abriss der Magdalenenkapelle veranlasst hat, angeschafft. Mit der Säkularisierung von 1802 wurde es jedoch von den Franzosen beschlagnahmt und verkauft. Der Glockenstuhl fiel außerdem 1869 den Flammen des Großbrandes zum Opfer. Heute trägt der 1890 wiederhergestellte Glockenstuhl ein fünfstimmiges Geläut aus dem Jahre 1932. Ihr Erhalt ist ein unglaublicher Glücksfall. Mit Ausnahme der größten Glocke, der im Durchmesser 1791 mm und 4021 kg messenden Dreifaltigkeitsglocke, wurden alle von den Nationalsozialisten 1940 konfisziert. Sie sollten zu Kriegszwecken eingeschmolzen werden. Die Dreifaltigkeitsglocke passte nicht durch die Kuppelöffnung und blieb in Knechtsteden. Die übrigen vier tauchten nach dem Krieg in Hamburg wieder auf und wurden an ihren Platz zurückgebracht. Das Glockenwunder von Knechtsteden war perfekt!
        Die Namen der mit Reliefs verzierten fünf Knechtstedener Glocken wurden bewusst gewählt:  die im „B“ läutende Dreifaltigkeitsglocke, die Marien-Glocke im „des“ für den Marienwallfahrtsort Knechtsteden, die Andreas-Glocke im „es“ zu Ehren des Kirchenpatrons, die Norbertus-Glocke im Ton „f“ in Anlehnung an den Gründer des Prämonstratenserordens und die Amandus-Glocke im „ges“.  Letzterer Name bezieht sich auf Amandus Acker. Spiritanerbruder Amandus Acker, Missionar auf Sansibar, gründete 1895 auf Veranlassung der Ordensleitung die Niederlassung der Spiritaner in Knechtsteden. Acker sollte eine Schule zur Ausbildung von Missionaren für die deutsche Kolonie in Ostafrika einrichten. Knechtsteden galt zwar als ein herrlicher Standort, die Abteikirche war wiederhergestellt, doch das Kloster lag noch in Ruinen und den Spiritanern fehlte das Geld. Die Bauvereine aus Köln und Neuss schlossen sich zusammen und generierten die notwendigen Gelder über 10.000 (!) zahlende Mitglieder. Der Wiederaufbau im barocken Stil konnte beginnen. Die Spiritaner hatten ein neues Zuhause in Knechtsteden.
        Wir neigen uns dem Ende dieser zugegebenermaßen langen Station in der Basilika zu.  Gehen Sie weiter das Nebenschiff entlang, bis Sie vor einer Tür stehen. Sie gelangen über diese Tür in den Kreuzgang des Klosters. Widmen Sie Ihre Aufmerksamkeit kurz der kalksteinernen Antoniusstatue an der Westwand der Kirche. Sie wurde 1904 in der Basilika zu Ehren des für Knechtsteden bedeutenden Anton Scheben, der 1903 gestorben war, aufgestellt. Vermutlich in den 1960er Jahren wurde sie in einem kleinen Park neben dem Pilgerhaus aufgestellt. 2020 rettete man die Statue vor den ihr zusetzenden Witterungsbedingungen und holte sie in die Basilika zurück. Sie soll bis heute an die Verdienste des Förderers und Gestalters Scheben erinnern.
        Bevor Sie die Tür rechts zum Kreuzgang betreten und damit die nächste Station beginnen, wenden Sie Ihren Blick kurz auf die eingerahmte Urkunde rechts der Tür. Es handelt sich um eine besondere Anerkennung aus dem Jahre 1974. Wegen ihrer überregionalen Bedeutung für die Seelsorge und Kunstgeschichte ist die Klosterkirche Knechtsteden zur päpstlichen „Basilica minor“ erhoben worden – aus unserer Sicht kaum überraschend, zieht man die vielen Besonderheiten, die wir eben erwähnt haben, in Betracht.

          ''',
      video: "assets/guidevideos/letityee.mp4",
      zusatztext:
          '''Die Spiritaner, eigentlich Missionsgesellschaft vom Heiligen Geist und vom Unbefleckten Herzen Mariens, sind eine katholische, missionierende Gemeinschaft, deren Geschichte bereits 300 Jahre zurückreicht.
      Einer der ersten Gründer ist Claude Francoise Poullart des Places. In Paris kaufte dieser ein Haus, um jungen Männern aus armen Verhältnissen das Studium zum Priester zu ermöglichen. Ziel war es, dass die jungen Männer nach ihrer Ausbildung in jenen Gebieten arbeiten sollten, für die die Kirche nur schwer Seelsorger findet. Frankreich war schließlich Kolonialmacht. Gerade in Übersee und in ländlicheren Regionen Frankreichs fehlte es an Geistlichen. 1703 gründete Poullart des Places die Kongregation vom Heiligen Geist, um seine Ziele zu verwirklichen.
      Poullart des Places ist nur einer der zwei Gründer des heutigen Spiritanerordens. 1845 vereinen sich die Kongregation des Places‘  mit der von François Libermann gegründeten Kongregation vom Unbefleckten Herzen Mariens. Auch Libermann gründete seine Kongregation für die Seelsorge der Einheimischen in den Kolonien. Mit der Vereinigung lag der Fokus der Arbeit der Spiritaner also eindeutig auf der Mission in Übersee. 
      Franz-Maria Paul Libermann war ein Konvertit. Er entstammte einer Rabbinerfamilie und ist streng jüdisch erzogen worden. Als er 1822 nach Metz zur Talmudschule geschickt wurde, erfuhr er von den dortigen aufgrund seiner Sprachkenntnisse Verachtung. Libermann begann, sich mit seinem Glauben kritisch auseinanderzusetzen. Dass für Gott ein Volk auf Kosten aller anderen auserwählt sein sollte, lehnte Libermann ab. Vielmehr seien alle Völker die Völker Gottes. Damit wurde in ihm der Grundstein für die Idee der Missionierung gelegt. In den folgenden Jahren des Studiums näherte er sich dem Christentum an und ließ sich 1826 taufen.
      Zwar trat Libermann in das Priesterseminar ein, scheiterte jedoch aufgrund eines epileptischen Anfalls. 1839 fühlte er sich innerlich aufgerufen, Heiden mithilfe eines Ordens zu missionieren. 1840 brach er nach Rom auf und ließ seinen Orden vom Papst bestätigen und konnte 1841 seine Priesterweihe nachholen. Mit der Vereinigung der Kongregationen wird er der erste Ordensobere der Spiritaner und förderte die Überseemission bedeutend. 1852 starb Libermann, die Legende besagt, im Geruch der Heiligkeit.
      Dass die Spiritaner in Deutschland und Knechtsteden Fuß fassen konnten, ist nicht selbstverständlich. Die Ordensleute vom Heiligen Geist ließen sich nämlich schon einmal in Deutschland nieder. 1863 lebten die Spiritaner in Düsseldorf-Kaiserswerth, Marienstatt und Mariental im Westerwald.  Im Kulturkampf des Deutschen Reiches unter der Federführung Bismarcks ist der Orden aber verboten worden. Die Rückkehr nach Deutschland, erstmalig in Knechtsteden, war wohl auch deshalb möglich,  weil die Spiritaner beim Kaiser Wilhelm II. beliebt waren. Die kolonialen Bestrebungen des Kaisers verlangten nämlich auch kirchliche und moralische Begleitung in den Kolonien. Die Spiritaner konnten daher staatspolitischen Interessen dienen und wurden so nicht nur erlaubt, sondern sogar gefördert. Die Wiederkehr in Knechtsteden unter Pater Amandus Acker haben Sie ja bereits vorhin zur Kenntnis genommen.
      Auch heute wirken die Spiritaner und verkünden die Frohbotschaft. In mehr als 60 Ländern auf der Welt leben und arbeiten die Spiritaner gegenwärtig. Schon zur Zeit ihrer Gründung übernahmen sie seelsorgerische Aufgaben dort, wohin sonst niemand wollte. Ihr Auftrag beruft sich von Beginn an darauf, das Evangelium jenen zu verkünden, die es nicht oder kaum zu hören bekommen haben. Die Spiritaner stehen dabei für jene ein, die unterdrückt, entrechtet oder ausgegrenzt sind. Leider finden die Spiritaner wieder vermehrt Tätigkeitsfelder in Europa. Der Seelsorge von Flüchtlingen oder Drogenabhängigen nehmen sie sich ebenso an wie den klassischen Einsatzgebieten in Afrika und Südamerika.
      ''',
      zusatzvideo: "assets/guidevideos/kommtanzmitmir.mp4",
      next: 0),
];
