class StationInfo {
  final int position;
  final double xcoord;
  final double ycoord;
  final String name;
  final String iconImage;
  final String description;
  final String fulltext;
  final String video;
  final int next;

  StationInfo(
    this.position, {
    this.xcoord = 0,
    this.ycoord = 0,
    this.name = "",
    this.iconImage = "",
    this.description = "",
    this.fulltext = "",
    this.video = "",
    this.next = 0,
  });
}

List<StationInfo> stationen = [
  StationInfo(1,
      xcoord: 51.076410,
      ycoord: 6.754703,
      name: 'Torhaus',
      iconImage: 'assets/guideicons/torhaus.jpg',
      description:
          "Brudi! Das ist voll Krass und so. Vor allen dingen ist das mega alt und so. Kann man mega geil schauen premium Statue!",
      fulltext:
          '''Welch ein Anblick sich dem Besucher Knechtstedens bei seiner Ankunft offenbart! Das imposante Portal begrüßt ihn und weist ihm den Weg zum Gotteshaus, das schon aus der Ferne sichtbar ist und sich ihm in seiner vollen Pracht präsentiert. Dabei besuchten
          Pilgernde Knechtsteden bereits weit vor Errichtung dieses Torbogens, wie Sie ihn hier sehen.
          Einer alten Legende nach soll ein unbekannter Knecht aus dem nahegelegenen Dieplinghoven, dem heutigen Delhoven, noch vor der Klostergründung im Wald ein steinernes Muttergottesbild gefunden und mit nach Hause gebracht haben. Am folgenden Tag stand das Bild jedoch wieder an derselben Stelle im Wald. Als ihm dies noch einmal geschah, soll er am Fundort zu Ehren der Mutter Gottes eine Kapelle errichtet haben. Deshalb soll der Ort „Knechtstein“ oder „Knechtsteden“ genannt worden sein. Diese Geschichte bleibt allerdings nur eine Legende, denn Historiker leiten die Herkunft des Namens „Knechtsteden“ von dem Wort „Knechtstätte“ ab. Das steinerne Abbild der Muttergottes wurde außerdem nie gefunden. So oder so blickt Knechtsteden auf eine sehr lange Wallfahrtsgeschichte zurück. Der Ort gilt zwar nicht als der größte Marienwallfahrtsort des Rheinlandes, zählt aber wohl zu den ältesten. Pilgernde kamen seit jeher vor allem aus Köln, aber auch aus dem Jülicher Land, aus Neuss und Düsseldorf und sogar vom fernen Niederrhein.
          Nun aber zum Torbogen: 12Das vor Ihnen befindliche zweistöckige barocke Torhaus ersetzte 1723 den ehemaligen romanischen Torbogen am Eingang des Klosterbezirks und wurde unter Abt Arnold Brewer (1703-1728), dessen Wappen am Portal eingearbeitet ist, als Teil der Umbauten im frühen 18. Jahrhundert errichtet. In Folge dieser Umbauten wurden die meisten Gebäude im barocken Stil neu errichtet, so auch das Torhaus.
          Verziert ist der Torbogen mit drei Statuen, zwei an den Seiten und eine oben. 13Die obere zeigt die Gottesmutter Maria mit dem Jesuskind auf dem Arm. Sie grüßt die Pilgernden bei Ankunft in die ihr gewidmete Wallfahrtsstätte.
          Die zwei Figuren an den Seiten stehen in gewisser Weise für zwei Epochen Knechtstedens. 14Links ist der Heilige Norbert dargestellt. Norbert von Xanten lebte von 1080/85 bis 1134 und ist der Ordensgründer der Prämonstratenser, die sich 1130 in Knechtsteden niederließen und 1138 mit dem Bau der Basilika begannen. Der Heilige Norbert, über den Sie gleich gern mehr in der App hören und lesen können, steht also für die Gründung des Klosters und seines Ordens. Vor Ihnen hält er in seiner linken Hand die Monstranz mit gewandelter Hostie. Seinerzeit galt der Heilige Norbert als deklarierter Gegner Tanchelms, der von der Kirche als Häretiker und Ketzer verurteilt wurde, weil er die wirkliche Gegenwart Jesu Christi in der gewandelten Hostie leugnete. So ist das Attribut Norberts als ein Symbol für sein Vertrauen auf die Heilige Kommunion zu verstehen.
          Rechts zu sehen ist Franz Maria Paul Libermann, der Neugründer der Missionsgesellschaft vom Heiligen Geist, kurz: des Spiritaner-Ordens. Das ausgehende 18. und das 19. Jahrhundert waren für das Kloster schwere Zeiten. Mit der Übernahme der Klosteranlage durch die Spiritaner 1895 beherbergte Knechtsteden endlich wieder Geistliche, nachdem Französische Revolution und napoleonische Säkularisation der
          ehemaligen Abtei der Prämonstratenser 1802 den Garaus gemacht hatten. Mit der rechten Figur des Torbogens besinnen sich die Knechtstedener also auf den zweiten Orden, der in Knechtsteden ansässig wurde. Abgebildet ist er mit einem Kreuz in seiner Hand. Dies ist ein Verweis auf die Kongregation, die Libermann gegründet hat. Zur Erklärung: Eine Kongregation ist eine religiöse Vereinigung, die sich im Unterschied zu den älteren Ordensgemeinschaften, die hauptsächlich auf das innerklösterliche Leben ausgerichtet waren, vor allem Aufgaben außerhalb des Klosters widmet. Libermann verschrieb sich dabei der Missionierung in Afrika, auf die das Kreuz in seiner Hand hindeuten soll.
          An den nächsten Stationen erfahren Sie über die beiden Epochen Knechtstedens mehr. Beginnen Sie hierfür die Navigation zur nächsten Station.
          ''',
      video: "assets/guidevideos/yee.mp4",
      next: 1),
  StationInfo(2,
      name: 'Norbertpark',
      xcoord: 51.076585,
      ycoord: 6.753799,
      iconImage: 'assets/guideicons/norbertpark.png',
      description:
          "Brudi das ist viel krasser. Hier hat man Natur und so! Das ist mega geil für Luft weil weniger CO2.",
      fulltext:
          '''Wenden Sie Ihren Blick zunächst dem Norbertpark zu. Wurde die große weitläufige Grünfläche früher zur Viehhaltung genutzt, hat der Norbertpark heutzutage eine andere Funktion. Nicht selten findet gerade an warmen Sommertagen Unterricht des in Sichtweite befindlichen Norbert-Gymnasiums, zu dem wir später noch kommen, im Freien statt. Auch Veranstaltungen an der frischen Luft, etwa Gottesdienste oder zuletzt die Vergabe der Zeugnisse an die Abiturienten, erfreuen sich im Norbertpark besonderer Beliebtheit. Der Norbertpark fungiert als ein Ort, der zusammenführt. Seine Anziehungskraft bezieht er nicht zuletzt aufgrund des wunderschönen Ausblicks, den die Basilika offeriert.
      Bitte wenden Sie sich nun der Klosterbasilika zu und lassen Sie die Hecken hinter sich, sodass Sie einen freien Blick auf das Gotteshaus werfen können. Sie sehen das Monument einer bewegten Zeit des 12. Jahrhunderts. Die Klostergründung in Knechtsteden von 1130 geht nämlich zurück  auf die Schenkung des ererbten Herrensitzes des Domdekans zu Köln, Hugos von Sponheim, an die Prämonstratenser. Dieser wurde zu seiner Schenkung durch den Kölner Erzbischof Friedrich I. angeregt. 
      Der Prämonstratenser-Orden ist ursprünglich vom Heiligen Norbert von Xanten, einem Priester des Erzbistums Köln, 1121 im namensgebenden Prémontré in Nordfrankreich gegründet worden und aus einer Reformbewegung heraus entstanden, die sich dem Ideal des gemeinsamen Lebens im Stile der Urkirche verpflichtete.  Wenn Sie nach Abschluss dieses Abschnitts auf Ihrem Gerät herunterscrollen, haben Sie die Möglichkeit, mehr über das aufregende Leben des Heiligen Norbert und seine bewegte Zeit zu erfahren. Sie können die aktuelle Wiedergabe aber auch pausieren und bereits jetzt den Heiligen Norbert kennenlernen.
      Dass dem Kölner Erzbischof eine Klostergründung in Knechtsteden attraktiv erschien, ist vor dem Hintergrund der Organisation des Ordens zu erklären: Für das klösterliche Leben galten die Augustinusregeln. Die Prämonstratenser verschrieben sich jedoch nicht nur dem kontemplativen monastischen Leben im Kloster, sondern übernahmen auch außerklösterliche Funktionen. Als „halbe Mönche und halbe Pastöre“ ermöglichten sie besonders in abgelegenen Gegenden die Seelsorge, für die sich adelige Priester kaum interessierten.
      Mit der Schenkung des Fronhofs Knechtsteden durch Hugo von Sponheim an die Prämonstratenser wurde 1134 zunächst eine Magdalenenkapelle errichtet, die nicht mehr erhalten geblieben ist. Auch genauere Hintergründe der Errichtung bleiben unklar. Sicher ist, dass die Mönche die Gründungskapelle erbauen ließen, da sie Gottesdienste zelebrieren wollten. Offensichtlich war die Kapelle nach wenigen Jahren zu klein für den aufstrebenden Orden geworden.  Bereits 1138 begannen die Prämonstratenser dann mit dem Bau der Klosterkirche, die bis in die Gegenwart ein Wahrzeichen der Region darstellt. Übrigens: Den Grundstein für den Bau legte eine Frau namens Udalinde. Sie war vermutlich die Schwester oder Mutter des Schatzmeisters Christian an St. Andreas in Köln, mit dessen Mitteln der Bau der Basilika begonnen wurde. Jener trat unter dem ersten Knechtstedener Propst, Heribert, in den Orden der Prämonstratenser ein und gab nach dem Vorbild seines Herkunfts-Stifts der Basilika ihren Patron Andreas.  Der Sarkophag, den Sie, Ihren Blick leicht nach links auf den Boden wendend, erblicken, war womöglich der letzte Ruheort Udalindes. Sicher kann das Grab ihr zwar nicht zugeordnet werden, die Grabplatte aus Sandstein stammt jedoch erwiesenermaßen aus der Stauferzeit und stimmt somit mit der Leb- bzw. Todeszeit Udalindes überein.
      Das Äußere der Basilika ist durch die drei Türme und das grauweiße Steinbild charakterisiert, die das Gebäude deutlich vom umliegenden Wald abheben und es so zu einem Wahrzeichen der Region machen. Die Klosterkirche ist 60 Meter lang und 19 Meter breit. Das Querschiff misst eine Länge von 26 Metern.  Der Vierungsturm, unter dem sich das Langhaus und das Querschiff kreuzen, hat eine Höhe von 35 Metern. Gebaut wurde die Basilika aus rheinischem Sand- und Tuffstein. Einige Ecken sind hingegen aus dem stabileren Trachyt gefertigt worden. Diese und weitere bauliche Verschiedenheiten sind vor dem Hintergrund der unterschiedlichen Bauphasen zu erklären.
      Die Basilika Knechtsteden ist ein kunsthistorisch überaus besonderes Gotteshaus. Dies wird nicht zuletzt durch die Verschmelzung der rheinisch-traditionellen Romanik sowie der durch die Prämonstratenser aus Nordfrankreich importierten Gotik verstärkt. Die Klosterkirche beurkundet so den Einfluss rheinischer und nordfranzösischer Kultur in ihrer Region. Am deutlichsten erkennbar scheint die Vereinigung der beiden architektonischen Epochen bereits von Ihrer Perspektive aus. Sind der Vierungsturm und die gesamte Drei-Türme-Anlage das Werk rheinischer Romanik, verweisen die Fenster des Ostchors eindeutig auf die Gotik. Jene auffällige architektonische Unterschiedlichkeit ist vor dem Hintergrund einer Erneuerung im 15. Jahrhundert, nach erheblichen Schäden durch Plünderungen während der Neusser Fehde 1474, einer kriegerischen Auseinandersetzung zwischen dem Erzbischof Ruprecht von Köln, und den Landständen des Erzstifts, zu erklären. Doch auch der ursprüngliche Bau in seiner vorliegenden Form verweist auf jene Vereinigung von Romanik und Gotik. War die rheinische Romanik eher bestrebt, dem Beispiel profaner Repräsentativbauten nach großflächig in die Breite, in die Horizontalität zu bauen, möchte die Gotik den Blick zu Gott in die Höhe, in die Vertikalität lenken. Die Außenwände des Ostbaus sind gegliedert und mit Ornamenten versehen, wie sie in Nordfrankreich ihrerzeit üblich gewesen sind. Das Langhaus und die Turmanlagen hingegen sind in niederrheinischen Bauformen gestaltet. Baulich besonders interessant sind die beiden Seitentürme: Die unteren beiden Geschosse sind französisch geprägt, die oberen niederrheinisch. Der Hang zur nordfranzösischen Vertikalität wird dabei durch den Trachytstein betont. Die Waagerechte betont hingegen der Tuffstein aus der Südeifel. Bauhistoriker erkennen in diesem französischen Einfluss erste gotische Elemente rheinischer Baukunst und zählen die Basilika Knechtsteden deshalb zu den bedeutendsten Bauwerken des 12. Jahrhunderts.
      Gehen Sie nun links entlang der Basilika an der Grabplatte vorbei Richtung Durchlass in der Mauer. Bevor Sie die Mauer durchlaufen, an der die 14 Stationen des Kreuzweges in Form gusseiserner Reliefs angebracht sind,  blicken Sie rechts am Fuß der Basilika hinunter. Dort ist bewusst als letzte, 15. Station des Kreuzweges an der Ostseite der Basilika ebenfalls eine alte Grabplatte drapiert, um an die Auferstehung nach dem Tod zu erinnern. Wem jenes Sarkophagfragment jedoch gehört, ist ungewiss. Durchqueren Sie nun die Mauer hin auf die Südseite der Klosterkirche mit Blick auf das dreischiffige Langhaus. Achten Sie je nach Körpergröße auf Ihren Kopf, Personen über 1,85m stoßen sich hier gelegentlich.
      Vor Ihnen befindet sich das südliche Nebenschiff mit dem Hauptportal.  Jenes Portal ist nachträglich eingefügt worden, da der ursprüngliche Osteingang nach Anbau des Querschiffes nicht mehr zu nutzen gewesen ist. Schauen Sie genau hin: Das Hauptportal ist verziert mit viermal abgetreppten Gewänden. Die Basaltsäulen setzen sich in den Bögen als Rundstäbe fort. Den innersten Portalbogen ziert ein schöner Akanthusblattfries, der in der Ornamentik für Leben und Unsterblichkeit steht.  Betrachten Sie nun die Wand des vor Ihnen befindlichen südlichen Nebenschiffes. Sie zeigt eindeutig Bogenspuren eines früher verbauten Kreuzganges, der nach den verschiedenen Formen dieser Bögen mehrmalige Umbauten erfahren haben muss.
      Wenden Sie Ihren Blick nach rechts. In der Nische zum östlichen Querschiff ist ein Relief eingelassen. Es zeigt die Heilige Magdalena zu Füßen Jesu Christi in dem Moment, als sie ihn als Auferstandenen erkennt. Das Relief verweist auf die ehemalige Gründungskapelle, die 1134 errichtet worden war und aufgrund ihres schlechten Zustandes Mitte des 18. Jahrhunderts, genauer 1731, abgerissen wurde. Das Relief erinnert daher an die ersten Anfänge klösterlichen Lebens in Knechtsteden.
      Zusatz: Leben und Wirken des Heiligen Norbert von Xanten
      Norbert von Xanten ist geboren in eine bewegte Zeit des Machtkampfes zwischen Papst und Kaiser.  Der Investiturstreit prägte die jungen Jahre des Heiligen Norbert, der 1080 vermutlich in Gennep, in den heutigen Niederlanden, geboren wurde – vermutlich, da nicht sicher überliefert ist, ob Norbert bereits zur Welt gekommen war, als sein Vater, Graf Heribert von Gennep, Burgvogt von Xanten wurde. Die Familie wechselte also den Wohnsitz von Gennep nach Xanten. Seine ersten von Stand privilegierten Lebensjahre verbrachte Norbert in Xanten.
      Sein Vater erwirkt für Norbert, Stiftsherr am Viktorstift in Xanten zu werden. Es handelt sich sozusagen um ein perfektes Absprungbrett, um eine kirchliche Karriere einzuschlagen. So verbringt Norbert unter anderem viel Zeit zu Hofe des Erzbischofs von Köln und des deutschen Königs Heinrich V. und kommt in den Genuss des höfischen Lebens.  Norbert begleitet etwa 1110 den König nach Italien, der in Rom vom Papst zum deutschen Kaiser gekrönt werden will.
      Aufgrund der Anspannungen zwischen weltlicher und geistlicher Gewalt, weigert sich der Papst den salischen Heinrich V., Sohn Heinrichs IV., zum Kaiser zu krönen. Heinrich nahm den Papst Paschalis II. gefangen und verlangte neben seiner Kaiserwürde das Recht der Investitur, also das Recht, Bischöfe zu ernennen und abzusetzen. Norbert von Xanten muss diese Vorgänge sehr intensiv erlebt haben. 
      Heinrich warb um Norbert und bat ihm sogar das Bischofsamt an, das Norbert ablehnte. Wann Norbert einen inneren Wandel vollzog oder gar eine transzendentale Erfahrung machte, ist unklar.  Die Legende besagt, dass er im Jahre 1115 auf dem Ausritt nach Vreden in ein Unwetter geriet. Vor ihm soll ein Blitz eingeschlagen sein, sodass Norbert samt Pferd zu Boden stürzte und aufgrund des knapp entkommenen Todes sein Leben hinterfragte. Für ihn stand fest: Es brauchte Erneuerung in ihm und in der Kirche. Um Vorbilder zu finden, ging er auf Wanderschaft. Auf seinen Wanderungen beherbergten ihn verschiedene Klöster. Norbert lernte die Klosterregeln, die Gemeinschaft und nicht zuletzt das asketische Leben kennen. Er ließ sich zum Diakon und daraufhin zum Priester weihen.
      Zurück in Xanten, versuchte er die Stiftsherren zu Viktor von dem Wandel im Sinne des Urchristentums zu überzeugen, den er in der Kirche anstrebte. Seine modische Seidenkleidung legte Norbert ab, verschenkte seinen Besitz und beschaffte sich eine raue Kutte, um mit gutem Beispiel voranzugehen. Norbert erntete dennoch lediglich Spott.
      Unverrichteter Dinge verließ Norbert sodann Xanten wieder und erkannte, dass Reform und Wandel nicht mit Weltfremdheit und Rückzug zu erreichen sind, sondern geistlichen Handelns bedarf. Norbert von Xanten wurde Wanderprediger. 1118 begab er sich in seine niederländische Heimat und predigte auf Wanderschaft bis nach Belgien.
      Norbert zeichnete sich als Prediger aus. Er begeisterte. Er ermunterte zu Demut und Bescheidenheit und prangerte Streit, Missgunst sowie Geiz und Habgier an. Dabei kam auch Kritik gegen Kirche und Fürsten nicht zu kurz. Jene Kirche hörte selbstredend nicht gern von einem Kritik übenden Wanderprediger, sodass Norbert in das Visier geriet und 1118 angeklagt wurde.  Auf der Synode, die über Norberts Schicksal verhandeln sollte, rechtfertigte er sich erfolgreich und erlangte sogar im Nachgang die Predigtvollmacht des Papstes in Nordfrankreich.
      So versuchte die Kirche, Norbert und seine unangenehme Beliebtheit in der einfachen Bevölkerung für sich zu nutzen.  Man ließ ihn gewähren und erlaubte ihm 1120 die Gründung eines eigenen Klosters im Tal von Prémontré bei Laon in Frankreich. Der Prämonstratenserorden, dessen Namensherkunft unschwer erkennbar vom Namen des Gründungsortes rührt, wurde gegründet. Das weiße Bußgewand aus ungebleichter Schafswolle wurde zur Ordenskleidung. In erstaunlicher Schnelle verbreitete sich der Orden der Prämonstratenser und gewann begeisterte Mitglieder für sich – ob Mann, ob Frau. Klöster wurden schnell auch in Belgien, Frankreich und Deutschland gegründet.  Das erste deutschsprachige Kloster der Prämonstratenser wurde 1122 in Cappenberg bei Dortmund errichtet. Der Graf von Cappenberg hatte nach einer persönlichen Begegnung mit Norbert von Xanten zuvor seinen gesamten Besitz übergeben und sich dem Orden angeschlossen. Ende des 12. Jahrhunderts zählten die sogenannten „Weißen Mönche“ 500 Niederlassungen.
      1126 begab sich Norbert nach Rom, um die offizielle Anerkennung seines Ordens zu erwirken. Die Verbindung asketischer Zurückgezogenheit mit der praktischen Seelsorge beeindruckte Papst Honorius II.. Die Ordensregel, die auf der Augustinusregel fußt, wurde vom Papst bestätigt. Auf seiner Rückreise wurde Norbert sogar in Würzburg festgehalten, um zu bleiben – Norbert ist ein Superstar. Im Sommer berief der Reichstag ihn schließlich zum Bischof von Magdeburg. Norbert wurde gedrängt, die Wahl anzunehmen. Er gab nach, seine Anhänger blieben enttäuscht zurück und fühlten sich im Stich gelassen. 
      Mit der Annahme der Verantwortung wollte Norbert seinen Einfluss zur Reform nutzen. Barfuß und im Büßerhemd ritt er in die Stadt Magdeburg ein. Laut Legende soll ihm zunächst sogar der Einlass in den Bischofspalast verweigert worden sein. Das Volk jubelte ihm zu. Die Reformen, die Norbert aber anstrebte, waren gerade für die alten kirchlichen Eliten des Bistums Magdeburg unangenehm. Der neue Bischof kontrollierte Rechnungen und beendete Geldverschwendungen. Ein missglückter Mordanschlag ist auf ihn verübt worden.
      Während seines Pontifikats nahm sich Norbert von Xanten unterschiedlicher Aufgaben an. Er trieb die Missionierung der Slawen im Osten an, als Erzkanzler begleitete er 1132 sogar König Lothar nach Italien auf dessen Romzug. 1134 kehrte er, vermutlich an Malaria erkrankt, zurück und verstarb am 6. Juni. 1582 sprach ihn Gregor XIII. heilig. 
      Der Heilige Norbert von Xanten war Zeuge einer bewegten Zeit. So wie auch sein Zeitgenosse, Bernhard von Clairvaux, Gründer des Reformordens der Zisterzienser. Beide Ordensgemeinschaften – Prämonstratenser und Zisterzienser – fanden von Frankreich aus eine erstaunlich schnelle Verbreitung. Ohne den Lebenswandel Norberts, seinen Entschluss der inneren und äußeren Reform, aber auch ohne sein Verantwortungsbewusstsein, doch das Bistum Magdeburg zu übernehmen, wäre dies wohl nicht möglich gewesen.
      ''',
      video: "assets/guidevideos/yeewars.mp4",
      next: 0),
];
